TanStack/query

src/index.js
=> remove code a !== null

src/index.js
=> Delete all queries when clearing query cache

src/index.js
=> refetchAllQueries promises error would not be raised anymore

README.md
There is a typo in prefetch async function.
=> Fix prefetch function typo in readme

examples/auto-refetching/package.json, examples/auto-refetching/yarn.lock, examples/basic/package.json, examples/basic/yarn.lock, examples/custom-hooks/package.json, examples/custom-hooks/yarn.lock, examples/focus-refetching/package.json, examples/focus-refetching/yarn.lock, examples/load-more-infinite-scroll/package.json, examples/load-more-infinite-scroll/yarn.lock, examples/optimistic-updates/package.json, examples/optimistic-updates/yarn.lock, examples/pagination/package.json, examples/pagination/yarn.lock
Fixes examples with current nextjs requirements.
Projects:
- auto-refetching
- basic
- custom-hooks
- focus-refetching
- load-more-infinite-scroll
- optimistic-updates
- pagination
=> Fix examples package.json

src/queryCache.js
Hello,
I found some problem when i am using `failureCount` it's not reset to zero as your readme say.
Thanks
=> Reset failureCount to zero

src/tests/useQuery.test.js
Covers https://github.com/tannerlinsley/react-query/issues/199
=> add unit test

src/queryCache.js, src/tests/useQuery.test.js
I've discovered this bug using React Query Devtools! 🚀
=> fix query marked as fetching, when setting initialData

README.md
Hi @tannerlinsley 
I came across this #229 when I was opening an issue.
=> updated useIsFetching readme (returns number not bool)

package.json
=> Include scripts in NPM package

src/tests/useQuery.test.js
=> Add unit test for cacheTime: Infinity

src/tests/utils.test.js, src/utils.js
See https://github.com/tannerlinsley/react-query/discussions/433
=> fix isDataEqual dates comparison

.all-contributorsrc, README.md
=> docs: add avinash as a contributor

types/index.d.ts
A new parameter was added in #584 by @Ephem. This PR adds the types for that change.
=> Add parameter for makeQueryCache to types

types/index.d.ts
Hello! 
Just add missing second argument on MutationFunction.
=> fix(types): add mutateOptions on MutationFunction

types/index.d.ts, types/test.ts, yarn.lock
This PR adds the new status flags to the type definition as discriminated unions
=> feat: Add TypeScript definitions for status flags

docs/src/components/LayoutDocs.js
this PR fixes the same issue addressed here https://github.com/tannerlinsley/react-table/pull/2527
=> docs: fix incorrect active nav link

types/index.d.ts
Context: https://github.com/tannerlinsley/react-query/pull/626#issuecomment-651018363
=> fix(types): Add typings for queryCache.clear({ notify: false })

types/index.d.ts
=> fix(types): make options undefinable

types/index.d.ts
=> fix(types): add queryFn to ReactQueryProviderConfig

examples/prefetching/package.json, examples/prefetching/yarn.lock, src/react/useBaseQuery.js
This PR is related this issue #783
=> fix: adding a axios library

docs/src/pages/docs/guides/ssr.md
📝  https://react-query-git-fork-macklinu-patch-1.tannerlinsley.vercel.app/docs/guides/ssr
=> docs(ssr): fix typo

docs/src/pages/docs/guides/updates-from-mutation-responses.md
Fix code exmaple for creating a custom mutation hook
=> docs: fix code for custom mutation hook

src/core/utils.ts
Closes https://github.com/tannerlinsley/react-query/issues/816
=> fix: check if the document global exists before usage

src/react/tests/suspense.test.tsx, src/react/tests/useQuery.test.tsx
Probably good to check if the functionality actually works ;)
=> test: fix suspense test

README.md
=> fix: readme header image

hydration.d.ts, package.json
Fixes https://github.com/tannerlinsley/react-query/issues/970
=> fix: export hydration types

docs/src/pages/docs/comparison.md, rollup.config.js, src/core/index.ts, src/core/notifyManager.ts, src/core/query.ts, src/core/queryCache.ts, src/core/queryObserver.ts, src/core/tests/queryCache.test.tsx, src/core/tests/utils.test.tsx, src/core/utils.ts, src/index.ts, src/react/reactBatchedUpdates.native.ts, src/react/reactBatchedUpdates.ts, src/react/tests/ReactQueryCacheProvider.test.tsx, src/react/tests/ReactQueryConfigProvider.test.tsx, src/react/tests/ssr.test.tsx, src/react/tests/suspense.test.tsx, src/react/tests/useInfiniteQuery.test.tsx, src/react/tests/useIsFetching.test.tsx, src/react/tests/useMutation.test.tsx, src/react/tests/usePaginatedQuery.test.tsx, src/react/tests/useQuery.test.tsx, src/react/useBaseQuery.ts, src/react/useIsFetching.ts, src/react/utils.ts
Fixes https://github.com/tannerlinsley/react-query/discussions/983
=> feat: implement batch rendering

src/core/types.ts
Fixes https://github.com/tannerlinsley/react-query/issues/1032
=> fix: accept any promise in useMutation callbacks

docs/src/pages/index.js
The quotes were breaking the links ;)
=> fix: remove trailing quotes from supporters links

docs/src/pages/docs/guides/queries.md
Hi Tanner, I've found a typo in docs.
It's a great library!!
=> docs: fix typo in queries page

docs/src/pages/docs/overview.md
I've adjusted the link to the installation page, I think that's the right page.
=> Adjust link into overview page

src/core/query.ts, src/react/tests/useInfiniteQuery.test.tsx
=> fix: refetching on infinite query when a page was deleted

docs/src/manifests/manifest.json, docs/src/pages/docs/guides/testing.md
I can't promise it's the best written documentation page, but it's a starting point for people to read to understand how they can test their code that makes use of React Query :)
Cheers
=> Guide page for testing - first draft

docs/src/pages/guides/infinite-queries.md, docs/src/pages/guides/migrating-to-react-query-3.md, docs/src/pages/guides/paginated-queries.md, docs/src/pages/guides/query-functions.md, docs/src/pages/reference/useInfiniteQuery.md, docs/src/pages/reference/useQuery.md, examples/basic/src/index.js, examples/custom-hooks/src/hooks/usePost.js, examples/default-query-function/src/index.js, examples/load-more-infinite-scroll/pages/index.js, examples/nextjs/hooks/usePosts/index.js, examples/pagination/pages/index.js, examples/playground/src/index.js, examples/prefetching/pages/[user]/[repo].js, examples/prefetching/pages/index.js, src/core/infiniteQueryBehavior.ts, src/core/query.ts, src/core/queryClient.ts, src/core/types.ts, src/core/utils.ts, src/hydration/tests/react.test.tsx, src/react/tests/ssr.test.tsx, src/react/tests/useInfiniteQuery.test.tsx, src/react/tests/useQuery.test.tsx
Closes https://github.com/tannerlinsley/react-query/discussions/1246
=> feat: add query function context

package.json, src/core/retryer.ts, yarn.lock
Upgrade to the latest version of TypeScript
=> chore: update TypeScript version

src/core/query.ts, src/react/useBaseQuery.ts
optimization(query): reduce unnecessary recursion
=> optimization(query): reduce unnecessary recursion

docs/src/pages/docs/guides/testing.md
Please let me know if you need something changed or can improve my phrasing, English isn't my native language.
=> Add infinite scrolling specific test examples

docs/src/pages/docs/guides/mutations.md
Add emoji to the mutations docs page for better UX.
=> docs: add emoji to mutations docs page

docs/src/pages/reference/QueryClient.md, src/core/tests/queryCache.test.tsx
=> Reset query docs and tests

docs/src/pages/guides/caching.md, docs/src/pages/guides/invalidations-from-mutations.md, docs/src/pages/guides/placeholder-query-data.md, docs/src/pages/guides/prefetching.md
Found a broken link. Quickly scanned through the repo for other links starting with `..` to see if there were more. These were all I could find that appeared to need updating.
=> docs: Fix broken links

docs/src/pages/guides/migrating-to-react-query-3.md
Great work on the v3 btw! Really appreciate the work.
=> docs: Fix syntax error (just a ' missing)

docs/src/pages/reference/QueryClient.md, src/core/queryClient.ts, src/core/tests/queryCache.test.tsx, src/core/types.ts
Fixes https://github.com/tannerlinsley/react-query/issues/1426
=> feat: add imperative infinite query methods

docs/src/pages/react-native.md
=> fix: typo on react-native doc page

docs/src/pages/guides/queries.md
=> Grammar correction

docs/src/pages/guides/query-invalidation.md
Spotted a small type when perusing the docs 😅
=> docs: fix typo in query-invalidation.md

docs/src/pages/guides/mutations.md
Since we await in the function body, onMutate should be an async function.
=> docs(useMutation): onMutate should be async

docs/src/pages/guides/query-keys.md
I believe this code example is broken
=> docs: Fix misleading code example

src/core/onlineManager.ts
=> fix(onlineManager): listen to 'offline' events

docs/src/pages/reference/useMutation.md
From documentation below it seems, code example missing `mutationKey`
=> Adding missing config property

src/core/mutationObserver.ts, src/core/tests/mutations.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/1632
=> fix: accept null values in mutate function

src/core/index.ts, src/core/query.ts, src/core/retryer.ts, src/react/tests/useQuery.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/1666
=> fix: update synchronously to make sure observers always have the latest state

docs/src/pages/reference/useQuery.md
I was confused what that meant when I first started. Added a link to the end to help clarify!
=> Add default query function reference

docs/src/pages/guides/infinite-queries.md
Added a note about a frequent question I had and see in the discord once in a while about why the data structure for `useInifiniteQuery`.
Also added an example for updating a single value in a page's data array. Sorry if that isn't written well enough, that was my best effort but I'm not that advanced yet! Feel free to edit or reject if it's not good enough and I can try again :)
=> Add data structure note and another example

src/devtools/useLocalStorage.ts
Closes https://github.com/tannerlinsley/react-query/issues/1726
=> hotfix: devtools hydration error

docs/src/pages/plugins/persistQueryClient.md
fixed link for `createLocalStoragePersistor`
=> docs: Update persistQueryClient.md

src/core/queryObserver.ts, src/core/tests/queryObserver.test.tsx
fixes #1855 
This ensures that the selector function is re-executed, and the catch block is reached and error is handled, leading to the correct isError state.
=> fix(queryObserver): re-run selector if it throws error

docs/src/manifests/manifest.json, docs/src/pages/guides/filters.md, docs/src/pages/guides/query-invalidation.md, docs/src/pages/reference/QueryCache.md, docs/src/pages/reference/QueryClient.md, docs/src/pages/reference/useIsFetching.md, docs/src/pages/reference/useIsMutating.md, src/core/mutationCache.ts, src/core/queryClient.ts, src/core/tests/mutationCache.test.tsx, src/core/utils.ts, src/react/index.ts, src/react/tests/useIsMutating.test.tsx, src/react/useIsMutating.ts
This PR adds a useIsMutating hook as discussed in #1298.
Let me know if it needs any changes.
=> feat: add useIsMutating hook

docs/src/manifests/manifest.json, docs/src/pages/reference/QueryClient.md, docs/src/pages/reference/useIsMutating.md
I made some mistakes updating the documentation in my last PR https://github.com/tannerlinsley/react-query/pull/1971.
Sorry about that. Everything should be correct now.
=> docs: fix useIsMutating docs

docs/src/pages/guides/infinite-queries.md
- Fix minor typos on infinite-queries.md file 
edit: I can push up additional commits for other markdown files (for typos) if you'd like to have a larger PR for minor doc fixes. I'm reading through the docs right now.
=> [docs] Update infinite-queries.md typos

examples/optimistic-updates/pages/index.js
Based on the comment above and the text in the paragraph tags below, I believe onSuccess is supposed to be onSettled instead.
=> fix(examples/optimistic-updates): fix typo

docs/src/pages/guides/migrating-to-react-query-3.md
While migrating I failed to spot this change and almost caused a prod bug, so I'm proposing this change to avoid anyone else also doing so 👍
=> Highlighting change of the default config key.

docs/src/pages/reference/useQuery.md
Add default value to staleTime option and add the fact it's optional
=> Add some details to staleTime documentation

.github/workflows/test-and-publish.yml
https://nodejs.medium.com/node-js-16-available-now-7f5099a97e70
=> chore: add tests for Node 16

docs/src/pages/guides/testing.md
Replaces obsolete `fetchMore()` with the almost similar API in v3
=> docs(testing): Update example to v3

examples/nextjs/package.json, examples/nextjs/yarn.lock
=> fix: add missing dependency web-streams-polyfill in nextjs example

docs/src/pages/guides/initial-query-data.md
=> docs: remove unnecessary apostrophe

docs/src/pages/guides/mutations.md
* Updates the copy to be consistent with the success state copy below it.
=> fix(typo): Update isError to error

src/createWebStoragePersistor-experimental/index.ts
=> fix(createAsyncStoragePersistor-experimental) fix throttle func

examples/basic-typescript/package.json
eslint-config-prettier is missing in basic-typescript example,
=> fix: add missing eslint-config-prettier in package.json,

src/core/logger.ts, src/core/tests/utils.test.tsx
Finally. 
Impact on existing code:
- `logger.ts`:  assume that `console` cannot be undefined at runtime
=> test(core):  100% code coverage

docs/src/pages/guides/optimistic-updates.md
the introductionary text for optimistic update was in my opinion not easily understandable. Thus, i tried to improve the wording a little bit, to make it easier to grasp the objective.
=> docs(optimistic-updates): ease wording in introduction

docs/src/components/LayoutDocs.js
This is the possible solution of this issue #2943
=> docs(reference): fixed right sidebar width issue

src/core/query.ts, src/core/tests/query.test.tsx
=> fix(useQuery): cleanup queries even if they have been fetching

docs/src/pages/guides/window-focus-refetching.md
Documentation section for window focus refetching caveats as discussed in #2960
=> docs: add pitfalls section for  window focus refetching

src/core/queryObserver.ts, src/react/tests/suspense.test.tsx
closes #2434
(would a description be enough as an issue link?)
=> fix(core): remove enabled condition in queryObserver

docs/src/pages/reference/useQuery.md
As seen in https://github.com/tannerlinsley/react-query/blob/dc2df1066fb35593ab9f7b852ee250424f212737/src/core/query.ts#L190-L194
=> Add cacheTime default

docs/src/pages/community/tkdodos-blog.md
=> docs: Fix a typo in tkdodos-blog.md

examples/react-native/yarn.lock
Regenerate a clean `yarn.lock` file without package version issues.
=> fix(examples): react-native: fix yarn.lock file

docs/src/pages/guides/testing.md
removing a word to fix the sentence.
=> docs(testing): remove word to fix sentence

docs/src/pages/plugins/persistQueryClient.md
Per discussion https://github.com/tannerlinsley/react-query/discussions/3198#discussioncomment-2273611
Since this became a bigger change than I expected, I broke it into several smaller commits (hopefully it is clear).
=> docs: update persistQueryClient.md with Persister docs

docs/src/pages/guides/mutations.md
=> docs: fix a typo in mutations.md

CONTRIBUTING.md
- update Gitpod button link to `https://gitpod.io/#<project-url>`
=> docs: update gitpod link in `contributing.md`

examples/offline/package.json, examples/offline/src/App.js, examples/offline/src/index.js
=> docs(examples): fix offline example

docs/src/pages/guides/mutations.md, src/persistQueryClient/persist.ts, src/persistQueryClient/tests/persist.test.tsx
=> fix(persistQueryClient): add a failing test for persisting mutations

docs/src/components/LayoutDocs.js, docs/src/components/PPPBanner.js, docs/src/pages/index.js, docs/src/pages/overview.md
Updates links from checkout page to landing page
=> Update links to course landing page

src/react/tests/useQuery.test.tsx
Related to https://github.com/trpc/trpc/pull/1645
=> add test for `status`=`error`

docs/src/pages/reference/useQuery.md, src/core/queryObserver.ts, src/core/types.ts, src/react/tests/useQuery.test.tsx
=> feat(query): functions for refetchOn options

src/core/queryObserver.ts, src/core/tests/queryObserver.test.tsx, src/react/tests/useQuery.test.tsx
refs #3530
there is no need to re-run the select function if it is referentially stable, even when it throws an error. if no dependency has changed, we can re-use the cached error, as the select function should be idempotent and thus return the same error anyway.
further, if we have cached data from a previously successful select, that should be returned as `data` alongside the error.
=> fix: cache select errors

docs/reference/useQueries.md
I have used as an example "staleTime: Infinity", but it can be whatever makes sense here. 
I've had a hard time figuring out where to put my options just by reading the explanation below the code example.
=> Update useQueries hook example

docs/guides/query-functions.md
Current url doesn't work. Replaced it with working one.
=> Change Query Keys Url

packages/react-query-devtools/package.json
https://github.com/TanStack/query/pull/3884#issuecomment-1191264046
Sorry about the previous PR.
The current build system is actually somehow messy. We might need to tidy it up once v4 is stable.
@TkDodo
=> fix(react-query-devtool): correct the noop entry for cjs

docs/adapters/react-query.md
Change `value` to `client` of `QueryClientProvider`
```ts
declare type QueryClientProviderPropsBase = {
client: QueryClient;
children?: React.ReactNode;
};
```
https://github.com/TanStack/query/blob/c5c4417f430a58b2dc7911cee99837b68f44a59c/packages/react-query/src/QueryClientProvider.tsx#L55
=> docs: update react-query.md

CONTRIBUTING.md, docs/src/siteConfig.js, examples/basic-graphql-request/public/favicon.ico, examples/basic-typescript/public/favicon.ico, examples/basic/public/favicon.ico, examples/custom-hooks/public/favicon.ico, examples/default-query-function/public/favicon.ico, examples/playground/public/favicon.ico, examples/rick-morty/public/favicon.ico, examples/simple/public/favicon.ico, examples/star-wars/public/favicon.ico, examples/suspense/public/favicon.ico
update urls to use v3 branch instead of master
=> docs: point resources to v3 instead of master

docs/adapters/vue-query.md
=> Update Vue-query document: rename Solid to Vue

packages/query-core/src/types.ts
Fixes #3981 
I think that's about it?
=> Allow returning non-promise values from mutation callbacks

packages/query-broadcast-client-experimental/package.json, packages/query-broadcast-client-experimental/yarn.lock
Fixes: https://github.com/TanStack/query/issues/3965
=> fix(query-broadcast-client-experimental): upgrade broadcast-channel

README.md
| BEFORE | AFTER |
|-|-|
|`Best of JS badge link was pointing to not existing project`<br><img width="1067" alt="Screen Shot 2022-08-16 at 2 02 23 PM" src="https://user-images.githubusercontent.com/60817786/184865014-49b41aff-b1f7-4396-a7a6-11915fed1465.png">|`since now points to a tanstack query project`<br><img width="1056" alt="Screen Shot 2022-08-16 at 2 02 30 PM" src="https://user-images.githubusercontent.com/60817786/184865245-c46d5483-087b-4785-8cb8-e9a3d9a29f48.png">|
|`bundlephobia badge was showing mizipped size for v3`<br><img width="186" alt="Screen Shot 2022-08-16 at 2 10 47 PM" src="https://user-images.githubusercontent.com/60817786/184865714-4d92b104-e49c-4611-bc48-63ed3219f91a.png">|`now shows minzipped size for v4`<br><img width="176" alt="Screen Shot 2022-08-16 at 2 10 …
=> docs: Update Best of JS and Bundlephobia badges links in README

docs/guides/disabling-queries.md, docs/reference/QueryClient.md
=> Docs: Fix typos

docs/guides/queries.md
Fixes a small link typo on the Queries doc page.
=> Fix link to Mutations page from Queries page

rollup.config.ts
fix: https://github.com/TanStack/query/issues/4142
=> fix: cjs extensionsless import for .native files

docs/guides/ssr.md
I was asked in the [discussion](https://github.com/TanStack/query/discussions/3270) to update the guide. Sorry it took me a while, but I was busy.
=> Add a guide for SSR with Suspense

examples/react/react-native/src/lib/api.ts
Delay function returned a function and data were never return. I change the delay function by removing the function passed and awaited it before the data were return.
=> docs(react-native): delay fn returned a function insted of data

.eslintrc, packages/react-query-devtools/src/devtools.tsx
and fix the warnings in devtools
=> refactor: set exhaustive deps eslint rule to error

docs/community/lukemorales-query-key-factory.md
=> productId to todoId

docs/guides/mutations.md
fixed a spelling error in a function call from a code example
=> docs(mutations): Fix spelling error

docs/config.json
=> docs: add ReactQueryKit link

packages/query-core/src/queryObserver.ts, packages/query-core/src/tests/queryObserver.test.tsx
=> fix(queryObserver): always structurally share placeholderData

packages/eslint-plugin-query/src/utils/create-rule.ts
=> fix(eslint-plugin): change docs urls to the website

packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.rule.ts, packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.test.ts
fixes https://github.com/TanStack/query/issues/4459
=> fix(eslint-plugin): omit generics/types from dependencies

docs/guides/updates-from-mutation-responses.md
=> docs(updates-from-mutation-responses.md): typo in "immutable"

docs/guides/disabling-queries.md
=> docs(disabling-queries.md): typo in disabling query example

packages/vue-query/src/useQueries.ts
hot-fix: https://github.com/TanStack/query/issues/4473
=> fix(vue-query): useQueries options allow empty array

docs/guides/dependent-queries.md
=> docs: Add a missing closing bracket

examples/react/offline/src/movies.js, examples/react/playground/src/index.jsx, examples/react/react-router/src/index.jsx, examples/react/react-router/src/routes/index.jsx, examples/react/rick-morty/src/Character.jsx, examples/react/rick-morty/src/Characters.jsx, examples/react/rick-morty/src/Episode.jsx, examples/react/rick-morty/src/Episodes.jsx, examples/react/rick-morty/src/Home.jsx, examples/react/rick-morty/src/Layout.jsx, examples/react/rick-morty/src/fetch.jsx, examples/react/simple/src/index.jsx, examples/react/star-wars/src/Home.jsx, examples/react/star-wars/src/Layout.jsx, examples/react/star-wars/src/fetch.jsx, examples/react/suspense/src/components/Button.jsx, examples/react/suspense/src/components/Projects.jsx, examples/react/suspense/src/components/Spinner.jsx, package.json
Examples were not checked nor formatted due to invalid glob pattern
=> chore: fix prettier script, format examples

docs/guides/ssr.md
Hello,
I was setting up @tanstack/query in a Remix project and as a first time Query user I had to adapt the Next.js guide to my use case. I had to write a simple utility Hook to make it work so I thought I'd publish that as a NPM package and share my findings here.
Hope this helps,
Have a nice day.
=> docs: Adds Using Remix to SSR guide.

lerna.json
I noticed this file was missed for removal during https://github.com/TanStack/query/commit/dce2815b951b59963949b70e34df39868de549d9
=> chore(deps) removes lerna config

docs/guides/updates-from-mutation-responses.md
=> Update missing bracket in code example updates-from-mutation-responses.md

docs/react/guides/migrating-to-react-query-5.md, docs/react/typescript.md, examples/react/basic-typescript/package.json, examples/react/optimistic-updates-typescript/package.json, examples/solid/basic-graphql-request/package.json, examples/solid/basic-typescript/package.json, examples/solid/default-query-function/package.json, examples/solid/simple/package.json, examples/vue/basic/package.json, package.json, packages/solid-query/src/createBaseQuery.ts, packages/vue-query/src/useBaseQuery.ts, pnpm-lock.yaml
closes https://github.com/TanStack/query/issues/4674
=> Feature/ts 4.7

examples/react/react-router/src/routes/contact.jsx
Use `queryKey` attribute to check for existing data.
=> docs(examples): Fix react-router example

examples/react/react-router/src/routes/contact.jsx, packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.rule.ts, packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.test.ts, packages/eslint-plugin-query/src/utils/ast-utils.ts
fixes https://github.com/TanStack/query/issues/4724
=> fix(eslint-plugin): exhasutive-deps false positives

docs/react/plugins/createAsyncStoragePersister.md
There was a mismatch between the type declaration and the documentation.
=> Update documentation to match type

packages/query-core/src/mutationCache.ts, packages/query-core/src/tests/queryClient.test.tsx
=> Revert "fix(core): make sure pausedMutations always execute in serial"

packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.test.ts, packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.ts
fixes https://github.com/TanStack/query/issues/4889
=> fix(eslint-plugin): don't remove options passed as variable

docs/config.json, docs/vue/guides/migrating-to-v5.md, packages/vue-query/__mocks__/vue-demi.ts, packages/vue-query/package.json, packages/vue-query/src/__tests__/queryCache.test.ts, packages/vue-query/src/__tests__/useQueries.test.ts, packages/vue-query/src/__tests__/vueQueryPlugin.test.ts, packages/vue-query/src/useQueries.ts, pnpm-lock.yaml
Fixes: https://github.com/TanStack/query/issues/4563
=> fix(vue-query): useQueries length change detection fix for vue2

packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.test.ts, packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.ts
Fix https://github.com/TanStack/query/issues/4938
=> fix(eslint-plugin): mutation function is turned into mutation key

packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.test.ts, packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.ts
fixes https://github.com/TanStack/query/issues/4938#issuecomment-1426988008
=> fix(eslint-plugin): autofix for useMutation with options

docs/react/guides/ssr.md
=> Revert "docs(react): Fix SSR custom framework guide -  `dehydratedState ` should be deconstructed"

packages/solid-query/src/createBaseQuery.ts
This change brings solid-query support for Astro like UI frameworks that use the component islands architecture. Astro works a little differently and supports top level await for loading data that can be passed in with `initialData` to server render the queries.
=> feat(solid-query): Component Islands support

package.json, packages/solid-query/package.json, packages/solid-query/tsconfig.json, pnpm-lock.yaml, rollup.config.ts
This change introduces a separate function in rollup.config.ts that leverages the `rollup-plugin-solid` to generate a consistent package for `solid-query`. Each Module target will be contained inside its own directory.
Please let me know if something should be changed here.
=> fix(solid-query): Fix Solid Query v5 Alpha Build

packages/react-query-devtools/src/index.ts
This PR fixes #4876, and completes #4738.
=> fix(react-query-devtools): add 'use client' directive to disable SSR

.github/ISSUE_TEMPLATE/bug_report.yml
Just cause some issue reports are hard to guess
@TkDodo
=> docs: add adapter dropdown to issue template

.github/workflows/ci.yml, .github/workflows/pr.yml
@TkDodo - confirmed this removes our Nx Daemon errors in CI now! (https://github.com/ZackDeRose/query/actions/runs/4415145519/jobs/7737740023 👀)
=> fix: turning off Nx daemon in CI

packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.test.ts, packages/eslint-plugin-query/src/utils/ast-utils.ts
fixes https://github.com/TanStack/query/issues/5088
=> fix(eslint-plugin): ignore internal properties

docs/react/community/lukemorales-query-key-factory.md
This PR updates the `@lukemorales/query-key-factory` example to reflect the changes in the latest major version, fixing the issue in the following discussion: https://github.com/TanStack/query/discussions/5254
=> docs: Update `@lukemorales/query-key-factory` example

docs/react/guides/migrating-to-v5.md, packages/react-query/package.json
=> fix: make sure codemods are included in react-query

.prettierignore, nx.json, package.json, pnpm-lock.yaml
=> nx 16 migration

packages/query-core/src/focusManager.ts, packages/query-core/src/mutationCache.ts, packages/query-core/src/mutationObserver.ts, packages/query-core/src/onlineManager.ts, packages/query-core/src/queriesObserver.ts, packages/query-core/src/queryCache.ts, packages/query-core/src/queryObserver.ts, packages/query-core/src/subscribable.ts, packages/react-query/src/__tests__/suspense.test.tsx, packages/solid-query/src/__tests__/suspense.test.tsx
prompted by https://twitter.com/BenLesh/status/1656747203531079680
=> fix(perf): optimized perf of listeners removal

docs/config.json, docs/react/community/suspensive-react-query.md
This reverts commit 3ec6693ba49078d51119ac50290a2bff8bc61d51.
related Pull Request: https://github.com/TanStack/query/pull/5259, https://github.com/TanStack/query/pull/5303
We solved problem about LICENSE with this https://github.com/suspensive/react/pull/42
I added `Copyright (c) 2021 Viva Republica, Inc.` in LICENSE.md of @suspensive/react-query as @raon0211, @BasixKOR's guide.
we can check it LICENSE.md in https://www.npmjs.com/package/@suspensive/react-query?activeTab=code
Thanks for helping solve this problem.
cc. @BasixKOR, @raon0211, @ChanhyukPark-Tech
=> Revert "docs: Revert "docs(community): add @suspensive/react-query community contribution (#5259)" (#5303)"

packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.test.ts, packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.utils.ts, packages/eslint-plugin-query/src/utils/ast-utils.ts
fixes https://github.com/TanStack/query/issues/5446
=> fix(eslint-plugin): lookup for any function ancestor

packages/query-core/src/onlineManager.ts
optimization addEventListener events with forEach
=> refactor(query-core): optimization addEventListener events with forEach

package.json, pnpm-lock.yaml, scripts/publish.mjs
See https://github.com/conventional-changelog/commitlint/pull/3614
=> fix: Bump @commitlint/parse

.eslintrc.cjs, examples/svelte/auto-refetching/package.json, examples/svelte/basic/package.json, examples/svelte/load-more-infinite-scroll/package.json, examples/svelte/optimistic-updates-typescript/package.json, examples/svelte/playground/package.json, examples/svelte/simple/package.json, examples/svelte/ssr/package.json, examples/svelte/star-wars/package.json, nx.json, package.json, pnpm-lock.yaml
Checks `.browserlistrc` against code during linting.
=> chore: Add eslint-plugin-compat

packages/query-devtools/src/Devtools.tsx
taken from: https://github.com/TanStack/query/commit/8fa59154aa361f64097569047db9ebf57c8c3eb0
=> fix(query-devtools): inform onlineManager when offline mode is simulated

docs/react/guides/optimistic-updates.md
I'm taking a note from https://www.twitch.tv/videos/1829920965?t=1h56m2s
I'm not sure if I worded it in the best way, just wanted to bring this back to the attention of @TkDodo :)
p.s. maybe it doesn't need the `return` either
=> make returning a promise for optimistic updates more explicit

packages/query-async-storage-persister/package.json, packages/query-broadcast-client-experimental/package.json, packages/query-devtools/package.json, packages/query-persist-client-core/package.json, packages/query-sync-storage-persister/package.json, packages/react-query-devtools/package.json, packages/react-query-persist-client/package.json, packages/react-query/package.json, packages/solid-query/package.json, packages/svelte-query-devtools/package.json, packages/svelte-query/package.json, packages/vue-query/package.json, pnpm-lock.yaml
pnpm transforms these fields on publish (https://pnpm.io/workspaces#publishing-workspace-packages)
=> fix: Use pnpm workspace protocol

packages/solid-query/package.json
=> fix(solid-query): revert package.json typo

packages/vue-query/src/__mocks__/useQueryClient.ts, packages/vue-query/src/__tests__/useQuery.test.ts, packages/vue-query/src/useBaseQuery.ts, packages/vue-query/src/useIsFetching.ts, packages/vue-query/src/useIsMutating.ts, packages/vue-query/src/useMutation.ts, packages/vue-query/src/useQueries.ts, packages/vue-query/src/utils.ts, packages/vue-query/src/vueQueryPlugin.ts
This reverts commit f16e413a8f7b9a5fc53a71502b7e7bacd21b2507.
=> Revert "fix(vue-query): do not subscribe on server - nuxt2 memory leak fix (#5576)

package.json, packages/react-query-persist-client/package.json, packages/react-query-persist-client/src/PersistQueryClientProvider.tsx, packages/react-query/package.json, packages/react-query/src/QueryClientProvider.tsx, packages/react-query/src/useBaseQuery.ts, packages/react-query/src/useInfiniteQuery.ts, packages/react-query/src/useIsFetching.ts, packages/react-query/src/useIsMutating.ts, packages/react-query/src/useMutation.ts, packages/react-query/src/useQueries.ts, packages/react-query/src/useQuery.ts, pnpm-lock.yaml
=> Revert "refactor(rect-query): prefer client-only import over 'use client'"

packages/query-devtools/src/Devtools.tsx
global `button` styles would otherwise affect buttons
=> fix(devtools): padding for action buttons

packages/vue-query/src/devtools/devtools.ts
=> fix(vue-query): show timeline events in the Vue.js devtools

packages/svelte-query/package.json
=> fix(svelte-query): Mark svelte v4 as supported

docs/react/overview.md
The repo url seems stable in the example code. I wish to update the code on CodeSandbox but have no idea how to do that.
=> Update the repo url in the example code

packages/eslint-plugin-query/tsup.config.js
=> fix(eslint-plugin-query): Update build entry files

.eslintignore, .gitignore, scripts/publish.ts
I added eslint ignoring rule like [nextjs](https://github.com/vercel/next.js/blob/canary/.eslintignore)
=> chore(.eslintignore): add eslint ignoring rule

packages/vue-query/src/__tests__/useMutation.test.ts, packages/vue-query/src/__tests__/useQuery.test.ts, packages/vue-query/src/useBaseQuery.ts, packages/vue-query/src/useMutation.ts, packages/vue-query/src/utils.ts
---------
Co-authored-by: Anton Kolesov <headcrabogon@gmail.com>
Co-authored-by: Damian Osipiuk <osipiukd+git@gmail.com>
=> fix(vue-query): useErrorBoundary support in useQuery and useMutation

pnpm-lock.yaml
When I work on beta branch and main branch, I used `pnpm install`. this is result. so I add this Pull Request
=> fix(pnpm-lock.yaml): update

docs/react/guides/queries.md
Added explanation of isFetching.
The wording is the same as in the [v3 document](https://tanstack.com/query/v3/docs/react/guides/queries).
=> docs(queries):add description of isFetching

docs/react/guides/infinite-queries.md, docs/react/guides/migrating-to-v5.md, docs/react/guides/prefetching.md, docs/react/reference/useInfiniteQuery.md, examples/react/algolia/src/useAlgolia.ts, examples/react/infinite-query-with-max-pages/src/pages/index.js, examples/react/load-more-infinite-scroll/src/pages/index.js, examples/svelte/load-more-infinite-scroll/src/lib/LoadMore.svelte, packages/codemods/src/v5/rename-properties/__testfixtures__/rename-cache-time.input.tsx, packages/codemods/src/v5/rename-properties/__testfixtures__/rename-cache-time.output.tsx, packages/query-core/src/infiniteQueryBehavior.ts, packages/query-core/src/tests/infiniteQueryBehavior.test.tsx, packages/query-core/src/tests/infiniteQueryObserver.test.tsx, packages/query-core/src/tests/queryClient.test.tsx, packages/query-core/src/types.ts, packages/react-query/src/__tests__/ssr.test.tsx, packages/react-query/src/__tests__/suspense.test.tsx, packages/react-query/src/__tests__/useInfiniteQuery.test.tsx, packages/react-query/src/__tests__/useInfiniteQuery.type.test.tsx, packages/solid-query/src/__tests__/createInfiniteQuery.test.tsx, packages/solid-query/src/__tests__/suspense.test.tsx, packages/vue-query/src/__tests__/queryClient.test.ts, packages/vue-query/src/__tests__/useInfiniteQuery.test.ts, packages/vue-query/src/__tests__/useInfiniteQuery.types.test.tsx
=> refactor(infinite-queries): rename defaultPageParam to initialPageParam

packages/react-query/src/types.ts
=> fix(infinite query): fix inferrence issue

docs/react/guides/optimistic-updates.md
This PR is a simple typo fix. I believe "... works very will ..." should be "... works very well ..."
=> fix: typo will -> well in optimistic-updates.md

docs/react/community/suspensive-react-query.md
I updated contents about @tanstack/react-query v5's public apis(useSuspenseQuery, useSuspenseQueries, useSuspenseInfiniteQuery) in suspensive-react-query.md
=> docs: update suspensive-react-query.md

packages/query-core/src/query.ts, packages/query-core/src/tests/query.test.tsx
fixes https://github.com/TanStack/query/issues/5968 , cc @TkDodo @KartheekJavvaji
=> fix: avoid reverting state to a fetching one

docs/react/plugins/persistQueryClient.md
Add missing await in Indexed DB persister example
=> Add missing await in Indexed DB persister example

docs/react/guides/dependent-queries.md
=> docs: Update dependent-queries.md

packages/query-core/src/hydration.ts, packages/query-core/src/tests/hydration.test.tsx
=> fix(hydration): do not alter fetchStatus when hydrating existing queries

packages/vue-query/src/useBaseQuery.ts
=> fix(vue-query): solve type error about `useQuery`

docs/solid/devtools.md, packages/solid-query-devtools/.eslintrc.cjs, packages/solid-query-devtools/package.json, packages/solid-query-devtools/src/devtools.tsx, packages/solid-query-devtools/src/index.tsx, packages/solid-query-devtools/tsconfig.json, packages/solid-query-devtools/tsup.config.js, packages/solid-query-devtools/vitest.config.ts, pnpm-lock.yaml, scripts/config.js
This PR adds the solid-query-devtools package for solid-query. This should just work out of the box with SolidJS and Solid-Start apps
https://github.com/TanStack/query/assets/45807386/f96a58cc-fcab-4bc0-b1ef-861a9902df5e
TODO
- ~~Add documentation~~
- ~~Include in all examples for solid-query~~  Need to be released first so will include them in a separate PR
=> feat(solid-query-devtools): Add Devtools

docs/config.json, examples/solid/basic-graphql-request/package.json, examples/solid/basic-graphql-request/src/index.tsx, examples/solid/basic-typescript/package.json, examples/solid/basic-typescript/src/index.tsx, examples/solid/default-query-function/package.json, examples/solid/default-query-function/src/index.tsx, examples/solid/simple/package.json, examples/solid/simple/src/index.tsx, examples/solid/solid-start-streaming/package.json, examples/solid/solid-start-streaming/src/root.tsx, integrations/solid-vite/package.json, integrations/solid-vite/src/index.jsx, pnpm-lock.yaml
Adds devtools to examples and also updates the docs
=> chore(solid-query): Add devtools to examples

examples/solid/basic-graphql-request/package.json, examples/solid/basic-typescript/package.json, examples/solid/default-query-function/package.json, examples/solid/simple/package.json, examples/solid/solid-start-streaming/package.json, pnpm-lock.yaml
solid-start example is broken because the dependencies were outdated.
I updated all the solid examples.
=> Update solid examples

packages/svelte-query-devtools/package.json, packages/svelte-query-persist-client/package.json, packages/svelte-query/package.json, pnpm-lock.yaml
This fixes the lockfile and makes sure that the build pipeline is functional again.
This issue was accidentally introduced in #6169
=> fix(query): Fix lockfile and build pipeline

docs/react/community/suspensive-react-query.md, docs/react/reference/useMutationState.md
https://suspensive.org is migrated from docusaurus to nextra
so I updated suspesnive-react-query.md's links
=> docs(suspensive-react-query): update links

.github/workflows/ci.yml, scripts/config.js, scripts/publish.js, scripts/types.d.ts
@TkDodo @lachlancollins FYI
Fixing release script for v4
Already merged it to v4 to release latest change
=> chore: add v4 branch to release scripts

.codesandbox/ci.json
I update node version of .codesandbox/ci.json
=> chore(.codesandbox/ci.json): update node

docs/react/guides/query-keys.md
Resolves https://github.com/TanStack/query/discussions/6286#discussioncomment-7468330
=> Fix link to community Query Key Factory Package

packages/vue-query/src/queryClient.ts
Fixes: https://github.com/TanStack/query/issues/6299
=> fix(vue-query): queryClient overloads compat with queryOptions

packages/query-core/src/queryObserver.ts, packages/query-core/src/tests/queryObserver.test.tsx
=> fix(core): make sure queries that re-subscribe will have the correct result

packages/query-core/src/types.ts
=> docs: add in editor-docs for gcTime key

packages/query-core/src/types.ts
Every pull request meet this prettier error. so I resolve it
=> chore(query-core): resolve prettier error

docs/react/community/community-projects.md
Doc update to add `http-wizard` in the Community Projects page.
I just released the `@http-wizard/react-query` package. Any feedback is welcome :)
Full doc [here](https://http-wizard.com/).
=> docs(community): adding http-wizard

docs/react/guides/window-focus-refetching.md
=> docs: Fix example for focusManager.setEventListener

docs/react/guides/dependent-queries.md
Changed from (Line 77): `usersId` 
To (Line 77): `userIds`
=> docs(dependent-queries.md): Syntax change

packages/react-query/src/__tests__/suspense.test.tsx, packages/react-query/src/__tests__/useQuery.test.tsx, packages/react-query/src/useBaseQuery.ts, packages/react-query/src/useQueries.ts
=> fix(react-query): make sure options are up-to-date when a mounted component re-suspends

CONTRIBUTING.md
This is a minor improvement for contributors (`CONTRIBUTING.md`).
While working on `angular-query` there were issues with missing dependencies (I had them as well). Following commands helped (credits go to @arnoud-dv). Hope it helps others too.
=> troubleshooting commands for contributors

packages/query-devtools/src/Devtools.tsx
Fixes #6508
And also adds consistent scrollbar styling to devtools
=> fix(query-devtools): Fix scroll on container

docs/react/installation.md
=> docs(docs/react): update spelling opera consistency

packages/vue-query/src/useInfiniteQuery.ts, packages/vue-query/src/useQuery.ts
fix: https://github.com/TanStack/query/issues/6543
=> fix(vue-query): fix `select` type inference

.github/workflows/ci.yml, .github/workflows/pr.yml
=> ci(.github/workflows): update version of actions/setup-node

packages/angular-query-experimental/src/__tests__/inject-mutation.test.ts, packages/angular-query-experimental/src/__tests__/test-utils.ts, packages/angular-query-experimental/src/create-base-query.ts, packages/angular-query-experimental/src/inject-mutation.ts
Also fixes a problem where core was run unexpectedly in Angular reactive context
=> fix(angular-query): add notifyManager to query and mutation

packages/query-core/src/queriesObserver.ts, packages/react-query/src/__tests__/useQueries.test.tsx
=> fix: revert early bailout improvements

knip.ts, packages/angular-query-experimental/src/__tests__/inject-mutation.test-d.ts, packages/angular-query-experimental/src/__tests__/inject-query.test-d.ts, packages/angular-query-experimental/src/create-base-query.ts, packages/angular-query-experimental/src/inject-mutation.ts, packages/angular-query-experimental/src/types.ts
This PR contains the resolution for the tests provided in #6634 and should fix the issues raised in #6635.
=> chore(angular-query): type narrowing on query and mutation results

package.json
=> Revert "fix(sherif): remove unnecessary option and ignore directory"

docs/vue/guides/ssr.md
Update documentation for https://github.com/TanStack/query/issues/6668
=> docs: correct nuxt2 example

packages/vue-query/src/__tests__/queryOptions.types.test.ts, packages/vue-query/src/queryClient.ts
Fix type inference from issue #6566 and fix queryOptions false positive test because of bad import of QueryClient.
=> Fix type inference

docs/angular/devtools.md, packages/angular-query-devtools-experimental/package.json, packages/angular-query-devtools-experimental/src/angular-query-devtools.component.ts
Skip hydration
Core devtools handles defaults
Enable all core devtools functionality
=> fix(angular-query-devtools): Reimplement Angular devtools

packages/angular-query-devtools-experimental/package.json, packages/angular-query-devtools-experimental/src/angular-query-devtools.component.ts, packages/angular-query-experimental/package.json, pnpm-lock.yaml
By running devtools code on browser platform only
=> fix(angular-query-devtools): fix SSR errors

docs/config.json
Update the config to use the new standardized config format.
See https://github.com/TanStack/tanstack.com/pull/135
=> chore: Use the new docs config format

docs/config.json
Update the config to use the new standardized config format.
See https://github.com/TanStack/tanstack.com/pull/135
=> docs: Use the new config format (v4)

docs/config.json
Update the config to use the new standardized config format.
See https://github.com/TanStack/tanstack.com/pull/135
=> docs: Use the new config format (v3)

docs/framework/react/reference/useMutation.md
Hello. 
Just tiny typo fix
Thanks for the great tool.
=> docs: Change the useMutation networkMode optional description to capitalize.

package.json, pnpm-lock.yaml
See https://github.com/TanStack/config/pull/35
=> ci: Update example dependencies when publishing

.codesandbox/ci.json, package.json
=> ci: Revert "Remove codesandbox"

package.json, pnpm-lock.yaml
Main feature: https://github.com/nrwl/nx/pull/21357
=> ci: Update Nx to v17.3.2

packages/solid-query/src/createBaseQuery.ts
Fixes #6312
This was a bug in the codebase that was trying to send the functions `fetchPreviousPage` and `fetchNextPage` functions as SSR payload. And functions (as we all know it) cannot be serialized over the wire. I have fixed the error and tested it out. Works now
=> fix(solid-query): Fix Infinite Query SSR payload

packages/query-devtools/src/Devtools.tsx
Adds tsqd prefixed classname to devtools button for custom styling
=> fix(query-devtools): Include class name to devtools button component

packages/solid-query/src/createBaseQuery.ts
Fixes #6961
There are times when we run a query on the server but the resource is never read. This could lead to times when the queryObserver is unsubscribed before the resource has loaded causing a time out error because the resource prevents render to flush. To prevent this we will queue the unsubscribe function if the cleanup is called before the resource has loaded.
=> fix(solid-query): Defer observer unsubscribe untill resource resolves

docs/framework/react/guides/prefetching.md, docs/framework/vue/guides/prefetching.md
Modified prefetch function name
=> docs: modify typo

packages/eslint-plugin-query/src/__tests__/exhaustive-deps.test.ts, packages/eslint-plugin-query/src/utils/ast-utils.ts
fixes https://github.com/TanStack/query/issues/7077
=> fix: query key with nullish coalescing operator

docs/config.json
Implements changes from https://github.com/TanStack/tanstack.com/pull/193
=> docs: Update docs/config.json (v4)

docs/config.json
Implements changes from https://github.com/TanStack/tanstack.com/pull/193
=> docs: Update docs/config.json (v3)

docs/framework/react/guides/disabling-queries.md, packages/vue-query/src/__tests__/useQuery.test.ts, packages/vue-query/src/useBaseQuery.ts
Fixes: https://github.com/TanStack/query/issues/6606, Fixes https://github.com/TanStack/query/issues/5976
=> fix(vue-query): respect `throwOnError` in `suspense`

docs/framework/react/devtools.md
The dev tools support mutations now (was unsure if I should remove it altogether?).
=> add a note for mutations in the dev tools

packages/query-core/src/queryClient.ts
The CI is failing on because of a format test failing. This fixes the CI pipeline
=> style(query-core): Fix prettier formatting error

packages/eslint-plugin-query/src/__tests__/exhaustive-deps.test.ts, packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.rule.ts
=> test(eslint-plugin): add missing dependencies test for FunctionExpression syntax

docs/framework/react/guides/render-optimizations.md
=> Update with typo render-optimizations.md

package.json, pnpm-lock.yaml
Looked at the build errors on main and updating vite and vitest should fix them
=> chore: update vite and vitest

packages/solid-query/src/createBaseQuery.ts
=> fix(solid-query): Resolve resource before unmounting query

docs/framework/react/devtools.md
Pretty straightforward, just noticed a misspelled word while reading the docs.
=> docs(react): Update spelling in devtools.md

packages/solid-query/src/createBaseQuery.ts
Noticed while creating another example with Astro integration that a query with `select` option did not correctly hydrate the underlying query. This simplifies the hydration payload by adding a hydrationData to the SSR payload
=> fix(solid-query): Simplify SSR Hydration Strategy

packages/solid-query/src/createBaseQuery.ts
=> fix(solid-query): Trigger refetch when query changes before hydration

docs/framework/vue/guides/custom-client.md
=> docs: update custom-client.md

docs/framework/react/devtools.md
Changes `instad` to `instead` in devtools.md file
=> Update typo devtools.md

docs/framework/react/guides/advanced-ssr.md
* https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr
Answers https://github.com/TanStack/query/discussions/7367
=> docs: Remove unused useState import from example

docs/framework/react/guides/suspense.md
=> update useSuspenseQuery error example

.github/workflows/ci.yml, .github/workflows/pr.yml
ref: https://github.com/TanStack/query/pull/7503#issuecomment-2143453137
=> ci(codecov): update version with token

.gitignore, package.json, pnpm-lock.yaml
- Adds per-project grouping to the Nx cloud interface
- Adds support for TS 5.5
=> ci: Update Nx and @tanstack/config

docs/framework/react/guides/advanced-ssr.md, docs/framework/vue/devtools.md
=> Fix: docs typo

docs/framework/vue/community/community-projects.md
Added a new community package, Query Rewind. https://reactqueryrewind.com/
=> Added Vue Community Project

docs/framework/angular/devtools.md, docs/framework/angular/guides/background-fetching-indicators.md, docs/framework/angular/guides/disabling-queries.md, docs/framework/angular/guides/infinite-queries.md, docs/framework/angular/guides/mutations.md, docs/framework/angular/guides/optimistic-updates.md, docs/framework/angular/guides/paginated-queries.md, docs/framework/angular/guides/queries.md, docs/framework/angular/guides/query-cancellation.md, docs/framework/angular/overview.md, docs/framework/angular/quick-start.md
Shikijs supports [TypeScript](https://github.com/shikijs/textmate-grammars-themes/blob/main/packages/tm-grammars/grammars/angular-ts.json) and [HTML](https://github.com/shikijs/textmate-grammars-themes/blob/main/packages/tm-grammars/grammars/angular-html.json) dialects, which improves the syntax highlighting for the Angular samples.
=> docs: update the syntax highlighting for angular

.github/workflows/autofix.yml, .github/workflows/ci.yml, .github/workflows/labeler.yml, .github/workflows/pr.yml, nx.json, package.json
- Covered by autofix.ci
- Also pinned patch versions of github actions
=> ci: remove test:format from Nx workflow

README.md
Adds a section in README file: `"Contributing"` which provides a link to the `CONTRIBUTING.md` file.
=> chore(readme): add contributing section

docs/framework/react/guides/request-waterfalls.md
=> fix(docs): typos

packages/angular-query-devtools-experimental/package.json, packages/angular-query-experimental/package.json, packages/eslint-plugin-query/package.json, packages/query-async-storage-persister/package.json, packages/query-broadcast-client-experimental/package.json, packages/query-core/package.json, packages/query-devtools/package.json, packages/query-persist-client-core/package.json, packages/query-sync-storage-persister/package.json, packages/react-query-devtools/package.json, packages/react-query-next-experimental/package.json, packages/react-query-persist-client/package.json, packages/react-query/package.json, packages/solid-query-devtools/package.json, packages/solid-query-persist-client/package.json, packages/solid-query/package.json, packages/svelte-query-devtools/package.json, packages/svelte-query-persist-client/package.json, packages/svelte-query/package.json, packages/vue-query-devtools/package.json, packages/vue-query/package.json
[rimraf](https://www.npmjs.com/package/rimraf) can take multiple arguments
=> chore: simplify clean commands

packages/react-query/src/__tests__/prefetch.test-d.tsx, packages/react-query/src/index.ts, packages/react-query/src/usePrefetchInfiniteQuery.tsx, packages/react-query/src/usePrefetchQuery.tsx
Other hooks in each files one by one. so I split it
=> fix(react-query): split prefetch.ts

docs/framework/solid/reference/createQuery.md
I noticed a missing `</Show>` tag here in the Solid docs; this PR adds it.
=> add missing </Show> closing tag to Solid docs

docs/framework/react/reference/useMutation.md
=> Fix typo in useMutation.md

packages/query-core/src/types.ts
Addresses #8453 https://github.com/TanStack/query/discussions/6293#discussioncomment-11647295
Sister tRPC PR proofing this fix: https://github.com/trpc/trpc/pull/6332
=> Investigating type naming issues with symbols

CONTRIBUTING.md
Updating the CONTRIBUTING docs since we are now using pnpm v9,
=> docs(contributing): update pnpm version

packages/query-core/src/index.ts, packages/query-core/src/notifyManager.ts
so that users can set a different scheduler and fall back to the default, too
=> feat: export defaultScheduleFn

package.json
this aligns with tanstack/config
https://github.com/TanStack/config/blob/main/package.json#L8
=> bump pnpm to 10.7

examples/solid/astro/package.json, examples/solid/basic-graphql-request/package.json, examples/solid/basic/package.json, examples/solid/default-query-function/package.json, examples/solid/simple/package.json, examples/solid/solid-start-streaming/package.json, integrations/solid-vite/package.json, packages/query-devtools/package.json, packages/solid-query-devtools/package.json, packages/solid-query-persist-client/package.json, packages/solid-query/package.json, pnpm-lock.yaml
This is part of avoiding this error:
- https://github.com/TanStack/query/issues/8799
=> fix(solid-query,query-devtools): bump solid (1.9.5) and vite-plugin-solid (2.11.6)

docs/framework/react/overview.md
✏️ Fix typo in `docs/framework/react/overview.md`, "React Query" to "TanStack Query" for consistency
=> ✏️ Fix typo in `docs/framework/react/overview.md`, "React Query" to "TanStack Query" for consistency

docs/config.json, docs/framework/solid/reference/useQuery.md, examples/solid/astro/src/components/SolidApp.tsx, examples/solid/basic-graphql-request/src/index.tsx, examples/solid/basic/src/index.tsx, examples/solid/default-query-function/src/index.tsx, examples/solid/simple/src/index.tsx, examples/solid/solid-start-streaming/src/components/post-viewer.tsx, examples/solid/solid-start-streaming/src/components/query-boundary.tsx, examples/solid/solid-start-streaming/src/components/user-info.tsx, examples/solid/solid-start-streaming/src/routes/batch-methods.tsx, examples/solid/solid-start-streaming/src/routes/hydration.tsx, integrations/solid-vite/src/App.jsx
Use same syntax as react for the examples/docs
=> chore(solid-query): update examples, integration, docs

docs/framework/solid/overview.md, docs/framework/solid/quick-start.md, docs/framework/solid/typescript.md
update quickstart, typescript guide, to use same syntax as react/vue
=> chore(solid-query): update docs

docs/framework/vue/guides/disabling-queries.md
1. Make status display more clear: isIdle -> isLoading
2. Fix typescript error: refetch has a different type signature with click event
=>  docs(vue-query): update example in disabling-queries.md

docs/framework/angular/guides/caching.md, docs/framework/angular/guides/invalidations-from-mutations.md, docs/framework/angular/guides/mutation-options.md, docs/framework/angular/overview.md
=> docs(angular-query): fix links

packages/query-core/src/__tests__/hydration.test.tsx, packages/react-query-persist-client/src/__tests__/PersistQueryClientProvider.test.tsx
ref: https://github.com/TanStack/query/pull/9011#issuecomment-2804846344
=> test(*): remove unnecessary async

packages/vue-query/src/types.ts
Suggesting fix for https://github.com/TanStack/query/issues/9034
=> fix(types): remove 'queryFn' from OmitKeyof in DefaultOptions

docs/framework/react/guides/advanced-ssr.md
“Let’s next look” – This is slightly awkward
=> docs(react-query): Small rephrase of adavnced-ssr.md (react)

packages/angular-query-experimental/README.md
Revert commit didn't trigger a release
=> fix(angular-query): fix types missing in published package

packages/react-query/src/__tests__/usePrefetchQuery.test-d.tsx, packages/react-query/src/types.ts, packages/react-query/src/usePrefetchQuery.tsx
discussion here: https://github.com/TanStack/query/pull/9301#issuecomment-3013376004
=> fix(react-query): throw type error when skipToken is present in prefetch query
