- README.md
Accroding to [the src of `useQuery`](https://github.com/tannerlinsley/react-query/blob/master/src/index.js#L414) and [the infinite scroll example](https://github.com/tannerlinsley/react-query#load-more--infinite-scroll-pagination), the config key to enable pagination is `paginated:boolean` instead of `pagination:boolean`.
> API doc typo for useQuery param: 'pagination' -> 'paginated'

- src/index.js
Fixes https://github.com/tannerlinsley/react-query/issues/39
> guard against missing `document` on React Native

- README.md
The prefetchQuery link was not working due to it being camel cased instead of lower case.  This will fix that and make the link work again!
> Fix prefetchQuery link

- src/useMutation.js
This will fix the issue identified here https://github.com/tannerlinsley/react-query/issues/165, however I am not sure if the check on the status in the useCallback was needed for a particular reason?
This will allow the mutation function to safely be included in a dependency array of an effect, like below.
```javascript
const [mutate]  = useMutation(SOME_MUTATION);
React.useEffect(() => {
mutate();
}, [mutate]);
```
> Update useMutation memoization

- src/tests/usePaginatedQuery.test.js
Covers #169 
As always, I've double checked that it fails without the fix
> Add test for usePaginatedQuery state

- src/tests/useQuery.test.js
Tests this piece of code:
https://github.com/tannerlinsley/react-query/blob/213df4a4fd87b705789c09d6eb63491e6c7b74c7/src/queryCache.js#L209-L219
Test fails, when cache timeout is set to `query.config.cacheTime`, i.e.:
```diff
query.scheduleGarbageCollection = () => { 
query.cacheTimeout = setTimeout( 
() => { 
cache.removeQueries(d => d.queryHash === query.queryHash) 
}, 
-     typeof query.state.data === 'undefined' && 
-       query.state.status !== 'error' 
-       ? 0 
-       : query.config.cacheTime
+      query.config.cacheTime 
) 
} 
```
> Test garbage collection of queries without data

- examples/suspense/package.json
Csb reports missing dependency when trying to run.
> Add missing axios dependency used by queries.js

- README.md
- src/queryCache.js
- src/tests/queryCache.test.js
Hey Tanner,
currently queryCache.prefetchQuery only explicitly returns if a fetch was actually attempted, due to `query.state.isStale || force`. This leads to it returning `undefined` for cache hits.
This PR naively fixes my failing test, let me know if there's more to be considered here.
codesandbox repro https://codesandbox.io/s/react-query-bug-repro-gi7oy
> queryCache.prefetchQuery should return cache contents on cache hit

- src/queryCache.js
- src/tests/queryCache.test.js
Turns out, that when query with initialData is added, `notifyGlobalListeners` is never called, since `dispatch` is never called.
> fix queryCache not notifying listeners, when query with initialData is added

- src/tests/useQuery.test.js
- src/useBaseQuery.js
Fixes #214 
I don't like test implementation, but I didn't find another way to test infinite loop.
Also, it logs `test was not wrapped in act(...)` warning, but I had no luck avoiding it.
> Fix useQuery infinite loop after query key is changed to falsy

- src/tests/useQuery.test.js
- src/utils.js
Fixes #217 
Use the already provided `isObject` to not accept `null` as a valid `object`.
I also added a test to run over this behavior.
> Fix type error when a null query key is used

- src/tests/useQuery.test.js
I noticed that CI was failing intermittently on a test and it was receiving an `act()` warning. I believe it's because we should be awaiting the find of the text to allow for async work to happen in `useQuery`.
To reproduce locally, run `yarn test` then `a` for all tests, then hit `Enter` twice to do two full test runs in sequence. The subsequent runs should fail reliably on this test.
This seemed to be introduced after my PR #332 perhaps due to fixing the GC issue, and a state update happening that isn't waited for during the test. Other tests do use `act` to do assertions as well, plus using `find` for components that do async work seems a lot more reliable.
- Fix `act` warning that happens on subsequent test runs for test `should be in "success" state by default in manual mode`
> test(useQuery): Ensure we await the rendered text we expect

- README.md
AFAIK this isn't an acceptable way to import (my editor was complaining)
```
const { useQuery } from 'react-query'
```
> minor: fix instruction typo in readme

- examples/focus-refetching/package.json
- examples/focus-refetching/yarn.lock
The `focus-refetching` example is missing the `axios` dependency in the
package.json, if we run the example locally there isn't any problem, but
if we use the `CodeSandbox` documentation link, the example is showing a problem with the missing dependency.
- Link to `CodeSandbox` failing: [focus-refetching](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/focus-refetching)
> fix missing dependency in an example

- package.json
- yarn.lock
This change bumps the version of Scarf, to ensure react-query continues to use the latest version of the package.
> Update @scarf/scarf version to ^1.0.0

- README.md
This is my small suggestion to change docs for more readability. :-)
It's basically extracting status code to the separate `if` statements instead of having everything inlined as it makes a little bit confusing when you are reading it. :-)
> Extract status for the easier readability in simple example - docs

- types/index.d.ts
This adds `retry` as a function to the types, so it matches the documentation.
https://github.com/tannerlinsley/react-query#retries
> types: add retry function to query options

- README.md
Closes #374 
Hi Tanner, hope this is good enough, let me know if you had imagined it differently.
> Add note to the docs about shared options

- types/index.d.ts
While using the `queryCache.refetchQueries` method with a predicate, I noticed that the `query.state` was typed as `unknown`. This blocks retrieval of the `data` member of `state`.
I have added types to the `state` member, `CachedQueryState<T>`. I decided to make it generic in order to be able to constrain the type for `data` - however, it could also be `any` just as easily.
Should this be backported back to DefinitelyTyped?
> Update CachedQuery to add type to state member

- examples/load-more-infinite-scroll/hooks/useIntersectionObserver.js
The `load-more-infinite-scroll` example in `react-query` only loads more results when the `loadMoreButtonRef` DOM element is within the viewport.
The `load-more-infinite-scroll` example in `react-query` loads results exhaustively, even when the `loadMoreButtonRef` DOM element is not within the viewport.
The `useIntersectionObserver` hook, which uses `useEffect` under the hood, does not pass any dependencies as the second argument of `useEffect`; therefore, the hook's callback executes upon every render. This means the IntersectionObserver gets instantiated every render - which in turn means IntersectionObserver calls _its_ callback every render, because IntersectionObserver's API specifies that the callback is called upon intersection _and upon initial observation_. Source: …
> Fix useIntersectionObserver hook in infinite scroll example

- src/queryCache.js
- src/useBaseQuery.js
Use queryRef to avoid infinite loop in refetch interval effect.
Fixes https://github.com/tannerlinsley/react-query/discussions/399
> Fix refetchInterval infinite loop

- src/queryCache.js
fixes #528 stops refetching every time the window is focused.
> fix:remove shouldContinueRetryOnFocus on success

- types/index.d.ts
Fixed return type of `queryCache.removeQueries`. The function has no return value but was incorrectly labeled as returning a promise.
> fix(types): change return type of removeQueries

- types/index.d.ts
- types/test.ts
This change enables more types beyond just `string` for the first QueryKey but still ensures that it's not `null`/`undefined`.
* The current type is too strict
* The `queryKeySerializerFn` doesn't play well with TypeScript when removing the first key so TypeScript users will benefit from being able to move their string key to the end of the list instead of having to add an additional argument to their functions.
This change will enable the following TypeScript code:
```ts
function doAdd(num: number): Promise<number> {
return Promise.resolve(num + 1);
}
useQuery<number, [number, string]>([10, "adder"], doAdd);
```
Before this change you'd have to modify your function to accept an additional argument which was unnecessary:
```ts
function doAdd(key: string, num: number): Promise<number>{ …
```
> fix(types): enable more types for first QueryKey

- types/index.d.ts
I'm just trying out v2 while a lot of our code is in a non-release phase (not sure when you plan on fully releasing v2?), so happy to throw any PRs for bits and pieces.
This started as a single quick type fix but it's turned into a general "fix the types" PR...
- The makeQueryCache config should be optional
- Adding the `enabled` option to the query opts
- Updating ReactQueryProviderConfig type to reflect the new 3-part structure
- I've removed the `force` flag from everywhere as it's no longer used
- I've added `idle` to the list of statuses
- I've also exported this as `QueryStatus` as I was often having to manually write `status: 'success' | 'loading' | 'error'` when we're passing the status into other components
> fix: makeQueryCache config was not optional in the type def

- types/index.d.ts
The `setQueryData` call also accepts a config object. This was not defined in the types yet.
> Add config parameter to `setQueryData` call

- docs/src/pages/docs/guides/mutations.mdx
I was working off the examples for useMutation trying to get a form submission to throw with errors from the back-end.
The rejected Promise from mutate wasn't getting caught in the try/catch. I now see in the API an option for throwOnError which is defaulted to false, so I added it to the useMutation example with the try/catch block.
> docs(guides/mutations): add 'throwOnError' option

- docs/src/pages/docs/comparison.md
Apollo does a deep comparison of the variables object when deciding whether or not the query needs to be re-executed. 
I can’t find this explicitly stated in the documentation unfortunately, but I know it to be true from experience. A quick squiz at the source code seems to indicate this is where it’s implemented:
https://github.com/trojanowski/react-apollo-hooks/blob/master/src/useQuery.ts#L119
(‘objToKey’ serialises the variables object.)
> Fix incorrect statement about Apollo

- docs/src/pages/docs/api.md
`useQuery` hook links in `usePaginatedQuery` and `useInfiniteQuery` are pointing to `#options` and such anchor doesn't even exist. This PR fixes that.
> Docs: Fix links to useQuery hook anchor

- docs/src/components/LayoutDocs.js
the search modal appears twice when a user opens it with cmd + k.
> fix: docsearch is rendered twice with keyboard shortcuts

- types/index.d.ts
- types/test.ts
fixes #737 
Let me know if it needs more work.
> fix: include undefined in IniniteQueryResult data type

- README.md
Hello again Tanner @tannerlinsley !
Following the discussion here https://github.com/michaelrambeau/bestofjs/issues/323#issuecomment-650675957 this PR adds a badge that shows the number of stars added on GitHub since the previous day.
It should render this:
[![Best of JS](https://img.shields.io/endpoint?url=https://bestofjs-serverless.now.sh/api/project-badge?fullName=tannerlinsley%2Freact-query%26since=daily)](https://bestofjs.org/projects/react-query)
It's only a suggestion, feel free to reject this PR if you feel that you have already too many badges or if you think this data is not useful.
Thank you!
> Add Best of JS badge to README.md

- docs/src/pages/docs/api.md
useQuery's API reference code is missing these while they are in the options below it - refetchIntervalInBackground, initialData, initialStale,
This PR adds them.
> docs: add missing options in useQuery's api reference

- types/index.d.ts
> fix: use generic Error type in ReactQueryProviderConfig.queries

- src/core/queryCache.js
- src/core/tests/queryCache.test.js
> fix:(prefetchQuery): override default retry behaviour to false

- types/index.d.ts
- types/test.ts
- Allow passing `CachedQuery<T, TError>` down to `CachedQueryState<T, TError>` for casting purposes
When you **know** the query typings you expect (such as when wrapping with your own abstraction like we do), you should be able to safely cast the type of `CachedQuery`.
```js
interface MyCustomResult<TResult, TError> {
data: TResult | undefined
error: TError | null
}
// Somewhere else...
function wrap(): MyCustomResult<TResult, TError> {
const queryData = queryCache.getQueryData<TResult>(queryKey);
const query = queryCache.getQuery(queryKey) as CachedQuery<TResult, TError> | undefined ;
return {
data: queryData,
error: query?.state.error ?? null
}
}
```
> fix(types): pass CachedQuery TError down to CachedQueryState

- docs/src/pages/docs/api.md
- src/core/query.js
- src/core/queryCache.js
- src/core/tests/queryCache.test.js
- types/index.d.ts
Any cache update triggered by a query will pass the query as the second argument to subscribers.
This enables executing side-effects for specific query updates.
BREAKING CHANGE: none
> feat(queryCache): pass query to subscribers

- src/core/queryCache.js
- src/react/tests/ssr.test.js
Closes #706
This PR makes it so caches returned from `makeQueryCache` will always be unfrozen, and therefor cache data, by default. This now includes on the server.
The global cache on the server is still frozen by default and does not cache data, this is to avoid leaking data across requests as per #70.
This makes it so the behaviour of `makeQueryCache` matches the one described in the Readme.
I also made the tests around this more explicit.
> Fix makeQueryCache default caching behaviour in node

- src/react/ReactQueryCacheProvider.js
`ReactQueryCacheProvider` uses own `queryCaches`, looks like a typo after refactoring.
Due to that typo, `onWindowFocus` is completely broken when isolated query cache is used.
> fix(ReactQueryCacheProvider): use shared `queryCaches`

- docs/src/components/Nav.js
- docs/src/components/Search.js
- docs/src/components/Sidebar.js
- docs/src/components/useSearch.js
- docs/src/pages/_app.js
- docs/yarn.lock
This PR refactors the Search logic to allow you to launch a search from the landing page and cleans up the Search component generally.
- state/Modal has been moved into a SearchProvider and passed down via context
- `<Search />` is basically just the UI "button" and doesn't render the modal anymore
- keyboard shortcut works everywhere (even without rendering `<Search />`)
- rendering `<Search />` twice won't cause the keyboard shortcut to render 2 modals
- removed props, states, and variables that were unused/misspelled
- renders the Search "button" in the nav for larger displays (not changed on tablet/mobile)
> docs: refactor search modal

- src/core/queryCache.js
- src/core/tests/queryCache.test.js
Providing a `defaultConfig` to `makeQueryCache` will merge `shared`, `queries`, and `mutations`
objects instead of overwriting. This allows you to configure only some options.
> feat(queryCache): merge defaultConfig options

- package.json
As react-query docs are now on a separate site maybe there is no need for jump2header, doctoc scripts
> refactor: remove jump2header, doctoc scripts

- docs/src/pages/docs/api.md
There was a reference to a previous API instead of `getFetchMore`
> (docs) fix `fetchMoreVariableOverride` description

- src/core/query.js
- src/core/tests/queryCache.test.js
- src/core/tests/utils.test.js
- src/core/utils.js
- src/react/tests/useInfiniteQuery.test.js
- src/react/tests/usePaginatedQuery.test.js
- src/react/tests/useQuery.test.js
- src/react/useBaseQuery.js
- src/react/useIsFetching.js
- src/react/utils.js
Hi there! This PR includes the following changes:
- Make sure the hook return values match the public APIs.
- Make sure the hooks only re-render when something has changed.
- Make sure the hook return values are stable / memoized.
- Batch the isStale and succes update together when possible.
- Batch the failureCount and error update together when possible.
With these changes, the number of renders for successful and unsuccessful queries can be reduced from 4 to 2.
PS: While working on the tests, I noticed the `canFetchMore` and `isFetchingMore` properties are sometimes set to `undefined`. I guess this is not correct? For now I matched the assertions with the current behaviour.
> fix: reduce the number of renders

- docs/src/pages/docs/api.md
Hey, no big deal, but just noticed a small typo in the API docs for `initialData` and thought I might help out!
> docs: fix typo for initialData API

- src/react/ReactQueryConfigProvider.js
- src/react/tests/ReactQueryConfigProvider.test.js
`useConfigContext` will always be populated. Checking the context value before defaultConfig update.
I was assuming that this was the original intent of the code and this change fixes an issue I was experiencing where `queryCache.prefetchQuery` was not seeing the default `queryFn` set in the provider.
> feat(ReactQueryConfigProvider): update defaultConfigRef

- docs/src/pages/docs/guides/ssr.md
Simply updates the document from `build in` to `built in`
> simple documentation update 🙂

- docs/src/pages/docs/api.md
Dependent Queries & Query Keys are pointing to api.md headers when they're documented in /guides/queries/(...)
> docs: fixes markdown links

- src/core/query.ts
- src/react/tests/useInfiniteQuery.test.tsx
canFetchMore should be false for falsy getFetchMore return value
> fix(useInfiniteQuery): correctly set canFetchMore

- src/core/queryInstance.ts
- src/react/tests/useQuery.test.tsx
This PR fixes #823.
In updateConfig some() was used in a way that doesn't make sense to me. I think this is the way it should be, but let me know if there is anything special about it.
> fix: fetch query when any instance is enabled

- docs/src/pages/docs/typescript.md
The new type defs include the `export type` syntax that was added in TS 3.8
Add this to the docs to inform people of the version requirement
> Adds TS version requirement

- docs/src/pages/docs/api.md
Fixes broken anchor to invalidateQueries in the api reference.
> docs: fix markdown anchor

- .github/workflows/test-and-publish.yml
This uses [bahmutov/npm-install](https://github.com/bahmutov/npm-install) to install NPM dependencies with caching without any configuration.
Also uses [cycjimmy/semantic-release-action](https://github.com/cycjimmy/semantic-release-action) as a wrapper for [Semantic Release](https://github.com/semantic-release/semantic-release).
> chore(actions): add cache to NPM dependencies on GitHub actions

- src/core/queryObserver.ts
- src/react/tests/useQuery.test.tsx
- src/react/useBaseQuery.ts
Fixes https://github.com/tannerlinsley/react-query/issues/896
> fix: make sure observers only subscribe to queries when started

- src/core/queryCache.ts
- src/react/tests/useIsFetching.test.tsx
- src/react/useBaseQuery.ts
- src/react/useIsFetching.ts
- src/react/utils.ts
Move prevent set state in render logic to useIsFetching hook to make QueryCache less aware of React
> refactor: move prevent set state in render logic to useIsFetching hook

- docs/src/pages/docs/guides/mutations.md
As seen at https://react-query.tanstack.com/docs/api#usemutation, 
> mutationFn: Function(variables) => Promise
Required
A function that performs an asynchronous task and returns a promise.
variables is an object that mutate will pass to your mutationFn
I correct the demo code
> chore: mutationFn should return a Promise type

- src/core/types.ts
This PR fixes a possible regression from #897. The typing matches the JSDoc again now.
> Fix typing for refetchInterval

- src/core/index.ts
- src/core/query.ts
- src/core/queryCache.ts
- src/core/queryObserver.ts
- src/core/setFocusHandler.ts
- src/core/tests/queryCache.test.tsx
- src/core/utils.ts
- src/react/tests/ReactQueryCacheProvider.test.tsx
- src/react/tests/suspense.test.tsx
- src/react/tests/useIsFetching.test.tsx
- src/react/tests/useMutation.test.tsx
- src/react/tests/useQuery.test.tsx
- src/react/tests/utils.tsx
This PR addresses three issues:
- Make sure existing promises also resolve when fetching is paused and resumed because of a window unfocus.
- Make sure existing promises also reject when fetching is cancelled. They will be rejected with a `CancelledError`.
- Make sure queries are still cached when the transport layer does not support cancellation.
- Set `CancelledError` as `error` to allow users to check if the query was cancelled (the `isCancelledError` helper function can be used to check if an error is a cancelled error).
> feat: make sure paused queries resolve

- .eslintrc
- src/core/query.ts
- src/core/queryObserver.ts
- src/core/types.ts
- src/react/tests/useInfiniteQuery.test.tsx
- src/react/useBaseQuery.ts
This MR addresses the following things:
- Fixes bug where previously fetched pages were still remembered after setting new data with `setQueryData`.
- Prevent unnecessary renders while performing infinite queries.
- Reduce bundle size by around 10%.
- Also update `canFetchMore` when setting data with `setQueryData`.
> refactor: reduce infinite query renders and bundle size

- src/core/query.ts
- src/core/queryCache.ts
- src/core/queryObserver.ts
- src/react/tests/useQuery.test.tsx
This PR refactors internals, specifically how `scheduleStaleTimeout` and `scheduleGarbageCollection` works behind the scenes, but leaves the documented public API unaffected. An earlier version was begun in #728, but has been fleshed out here and made sense as it's own PR.
The main goal is to remove scheduling of timeouts from the constructor of Query and instead let the consumer creating a new Query mark when timeouts are ready to be scheduled. This is needed to implement hydration, but will also make it easier to remove scheduling of timeouts from the render-phase in `useBaseQuery` as a next step.
* Remove scheduling timeouts from `constructor`
* Require explicit timeout activation via new `query.activateTimeouts()`
- This only applies internally and specifically anyone using …
> Refactor query timeouts

- docs/src/pages/docs/guides/caching.md
I had some trouble understanding the purpose of the `cacheTime` in relation to the `staleTime` and discussed my understanding with @tannerlinsley. He was able to help clear it up by explaining the immediate cache return value concept while the `cacheTime` interval was active. This helped distinguish the difference for me. Hopefully this clarification in the docs will help someone else who is new to the library as well 😄
> Added further details to the Caching guides

- docs/src/pages/docs/comparison.md
- src/core/query.ts
- src/core/queryCache.ts
- src/core/queryObserver.ts
- src/core/tests/queryCache.test.tsx
- src/hydration/hydration.ts
- src/hydration/tests/hydration.test.tsx
- src/hydration/tests/react.test.tsx
- src/react/tests/useQuery.test.tsx
- src/react/tests/utils.tsx
This MR allows users to define different stale times for different situations. Instead of marking a whole query as stale, the staleness of a query is determined when consuming the query. The rationale for this can be found here: https://github.com/tannerlinsley/react-query/discussions/770#discussioncomment-42352 . This also resolves some of the confusion about what happens if different hooks define different stale times.
> feat: determine staleness locally instead of globally

- src/core/queryObserver.ts
- src/react/tests/useQuery.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/927
> fix: make sure initial data is used when switching queries

- docs/src/pages/docs/api.md
- docs/src/pages/docs/guides/ssr.md
- src/hydration/index.ts
- src/hydration/react.tsx
- src/hydration/tests/react.test.tsx
- src/hydration/tests/ssr.test.tsx
This MR removes the `hydration/ReactQueryCacheProvider` component and replaces it with a `Hydrate` component. The `hydration/ReactQueryCacheProvider` component has some mixed responsibilities and having two of them could be a bit confusing. Exposing a `Hydrate` component simplifies the API because we only export three things which all basically do the same thing: `hydrate()`, `<Hydrate />` and `useHydrate()`. @Ephem
> feat: remove ReactQueryCacheProvider from hydration

- src/core/query.ts
- src/core/queryCache.ts
- src/core/queryObserver.ts
- src/core/tests/queryCache.test.tsx
- src/hydration/hydration.ts
- src/react/tests/ssr.test.tsx
- src/react/tests/useQuery.test.tsx
Currently the query configuration is dependent on the order in which hooks are rendered and this could result in unexpected behaviour. This MR will make sure the query configuration is only changed on execution. Related to https://github.com/tannerlinsley/react-query/discussions/932
> fix: always use config from last query execution

- src/core/query.ts
- src/core/queryCache.ts
- src/react/tests/useQuery.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/947
> fix: make sure queries with only inactive observers are also invalidated

- docs/src/pages/docs/api.md
- docs/src/pages/docs/comparison.md
- src/core/config.ts
- src/core/query.ts
- src/core/queryCache.ts
- src/core/queryObserver.ts
- src/core/types.ts
- src/react/tests/useInfiniteQuery.test.tsx
- src/react/tests/useQuery.test.tsx
- src/react/useMutation.ts
- tsconfig.json
Some applications might not have indicators in the UI to indicate if data is stale or if some query is refetching/revalidating. In these cases, the UI also does not need to re-render if any of these states change. It would be sufficient to only re-render when the actual `data` or `error` properties change. This flag resembles the `notifyOnNetworkStatusChange` flag from Apollo.
> feat: add notify flag for controlling re-renders

- src/core/query.ts
- src/core/queryObserver.ts
Fixes https://github.com/tannerlinsley/react-query/issues/873
> fix: ignore errors from background fetches

- src/core/query.ts
- src/core/queryCache.ts
- src/core/setFocusHandler.ts
- src/core/setOnlineHandler.ts
- src/react/tests/useQuery.test.tsx
On window refocus or reconnect, trigger the first observer which indicates it should be refetched.
> fix: use hook config on refocus or reconnect

- src/react/tests/useQuery.test.tsx
I spotted a typo in a comment when reading through the tests.
> fix: typo in useQuery.test

- src/core/query.ts
- src/hydration/hydration.ts
- src/hydration/tests/hydration.test.tsx
- src/hydration/tests/react.test.tsx
Fixes #951 
This makes it so hydrating queries that have newer data according to `updatedAt` will set this new data to the existing query in the cache (with the correct `updatedAt`).
This PR also moves some internal stuff around in hydration as well as changes the shape of the hydration payload. Hydrated queries are no longer set with `initialData`, instead `query.setData` with the new internal `updatedAt`-option is used.
> fix(hydration): overwrite the existing data in the cache if hydrated data is newer

- docs/src/pages/docs/guides/suspense.md
- src/react/ReactQueryErrorResetBoundary.tsx
- src/react/index.ts
- src/react/tests/suspense.test.tsx
- src/react/useBaseQuery.ts
Because error boundaries are only applicable to a certain a tree, I think it would be good if the error reset would also only be applicable to that specific tree.
The `ReactQueryResetErrorBoundary` component enables this functionality, while allowing users to keep their own error boundary component. This does mean users will need to wrap their queries in two boundaries. We could streamline this by providing a `ReactQueryErrorBoundary` component similar to `react-error-boundary`. But maybe there are arguments against this?
This change should be backwards compatible and would allow us to remove `queryCache.resetErrorBoundaries()` and `query.state.throwInErrorBoundary` in v3 to make the core less knowledgable about React.
> feat: add reset error boundary component

- src/core/tests/utils.test.tsx
- src/core/utils.ts
Looks like this function is not used anymore so I just deleted it.
> refactor: remove unused deepEqual function

- src/core/query.ts
- src/core/utils.ts
- src/react/tests/useInfiniteQuery.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/972 and https://github.com/tannerlinsley/react-query/issues/880
> feat: cancel current fetch when fetching more

- docs/src/pages/docs/api.md
Fixes https://github.com/tannerlinsley/react-query/issues/960
> docs: update api docs

- src/react/ReactQueryErrorResetBoundary.tsx
- src/react/tests/ReactQueryResetErrorBoundary.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/1015
> fix: should throw error when using useErrorBoundary

- docs/src/pages/docs/comparison.md
Hey! I noticed 3rd party library website links don't work properly on [comparison](https://react-query.tanstack.com/docs/comparison) page . This PR fixes it.
> docs: fix comparison 3rd party website links

- docs/src/pages/docs/api.md
Hi,
I removed storing the return value of `queryCache.removeQueries` as it doesn't return anything.
BTW, is it an expected behavior that `queryCache.removeQueries` only removes `inactive` queries?
Thanks.
> Remove storing the return value of queryCache.removeQueries

- src/react/tests/ReactQueryResetErrorBoundary.test.tsx
- src/react/useBaseQuery.ts
Fixes https://github.com/tannerlinsley/react-query/issues/1053
> fix: query should try and throw again after error boundary reset

- docs/src/pages/docs/guides/queries.md
We need `user?.id` instead of `user.id` in order to correctly handle the `null` case.
> docs: fix `user.id` access in case user is null

- docs/src/pages/docs/api.md
Removed storing the return value of `queryCache.cancelQueries` as it doesn't return anything.
> Remove storing the return value of queryCache.cancelQueries

- docs/src/pages/docs/guides/important-defaults.md
I was reading the docs and noticed this wasn't quite correct. I assume "it makes your app more performant" is what's intended here, but "it will make your app more performant" could work as well.
> docs: fix typo in Important Defaults

- docs/src/pages/docs/installation.md
Noticed that simple and basic links were missing from the installation code block.
This also revealed a css usability issue regarding anchor tags in `blockquote` elements. As the colors of the `a` are being inherited. Currently that would be gray, `:visited `is unaffected.
> docs(installation): Add missing links

- docs/src/components/markdown.module.css
As noted in #1094
> This also revealed a css usability issue regarding anchor tags in `blockquote` elements. As the colors of the `a` elements are being inherited. Currently that would be gray, `:visited `is unaffected.
> docs: blockquote anchor color

- examples/custom-hooks/README.md
- examples/custom-hooks/package.json
Fix failing build for the [custom-hooks](https://github.com/tannerlinsley/react-query/tree/master/examples/custom-hooks) example.
Making a fresh clone and running the custom-hooks example after `npm install` gives the following error:
I've added the required package that fixes this build error.
Operating system: Ubuntu 20.04.1 LTS
> Add eslint-config-prettier to devDependencies in custom-hooks example

- docs/src/pages/docs/guides/queries.md
There's a bit of a learning curve to react-query, especially when it comes to understanding the difference between queries and mutations and how to use react-query for a POST method.
I've added some explanation to the docs based on the discussion in #801 
Currently, the algolia search for "post" leads to results from the "Invalidation from Mutations" document which might not exactly be relevant for someone just trying to make a basic POST call. 
This change will hopefully make the "Queries" section show up in results for "post" too since a simple query might be ideal to use when the POST function isn't modifying server data. The docs currently don't mention clearly that queries can work fine for POST calls.
Please feel free to edit the words to a better-suited language if possible but …
> docs: Elaborate on usage of queries

- docs/src/pages/guides/invalidations-from-mutations.md
- docs/src/pages/guides/mutations.md
- docs/src/pages/guides/updates-from-mutation-responses.md
- docs/src/pages/quick-start.md
- docs/src/pages/reference/useMutation.md
- examples/auto-refetching/pages/index.js
- examples/focus-refetching/pages/index.js
- examples/optimistic-updates/pages/index.js
- examples/playground/src/index.js
- src/core/types.ts
- src/react/tests/useInfiniteQuery.test.tsx
- src/react/tests/useMutation.test.tsx
- src/react/tests/utils.tsx
- src/react/types.ts
- src/react/useMutation.ts
- src/react/utils.ts
Currently the `mutate` function returns a promise which by default returns `undefined` on error. This behavior seems to confuse some people as they initially expect the promise to behave like a regular promise. There is a `throwOnError` option to make the promise behave like a regular promise, but this option seems to be overlooked and does not work well with the types. Returning a different type based on an option is possible (although a bit cumbersome), but it's impossible to guarantee the correctness because it can also be defined globally. This PR splits the functionality into `mutate` and `mutateAsync`. The `mutate` function returns nothing and the `mutateAsync` function returns a regular promise.
Issue https://github.com/tannerlinsley/react-query/issues/1111
> feat: split mutate into mutate and mutateAsync

- docs/src/pages/docs/devtools.md
- docs/src/pages/docs/installation.md
Thankfully, `--save` hasn't been necessary with NPM for some time now :)
> Remove unnecessary --save in install instructions

- .gitpod.yml
- CONTRIBUTING.md
- README.md
Hi. 
I work for Gitpod(an online Open Source VS Code like IDE which is free for Open Source) and we're currently on a mission to simplify contributors/maintainers onboarding for cool Open Source projects. 
This Pr adds Gitpod config to the repo to fully automate the dev setup for this project i.e with this config anyone interested in contributing to this project would be able to start a workspace where it will automatically:
- clone the `react-query` repo.
- install all the dependencies in `/` and `/docs`.
- run `yarn start` in the root(`/`) to Auto-build files.
- run `yarn dev` in `/docs`.
This way anyone interested in contributing can start straight away without any friction.
This is how it looks:
You can give it a try on my fork of the repo via the following link: …
> Easier Contributions.

- docs/src/pages/docs/api.md
From my understand, the `manual` property was changed to `enabled`. This pull request updates the documentation to reflect that change.
> docs(api): change manual to isEnabled

- docs/src/pages/reference/useQuery.md
From my understand, the `manual` property was changed to `enabled`. This pull request updates the documentation to reflect that change.
**Mirroring the changes of #1166**
> docs(useQuery): change manual to enabled

- docs/src/pages/docs/typescript.md
When using with typescript, the error type cannot be inferred and appears as 'unknown'.
This adds an explicative note and example as it might not be obvious how a custom hook should be created.
> docs(typescript): add note for custom hooks types

- docs/src/pages/docs/guides/infinite-queries.md
In the example, the error on line 60 - `error.message` - is undefined. This adds the error to the destructured return value of useInfiniteQuery.
Thanks for an awesome lib and fantastic docs!
> docs(infiniteQuery guide): include missing error

- docs/src/pages/docs/api.md
Fixing typo for the type of `defaultConfig`
> docs: fix typo for options used in querycache

- src/core/queryObserver.ts
Jest's modern timers break because the stale timeout is created with `setTimeout` but cleared with `clearInterval`. This stops them from breaking because we are now clearing the timer with `clearTimeout`.
```
Error: Uncaught [Error: Cannot clear timer: timer created with setTimeout() but cleared with clearInterval()]
at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
at innerInvokeEventListeners (/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
at invokeEventListeners (/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
at HTMLUnknownElementImpl._dispatch (/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
at HTMLUnknownElementImpl.dispatchEvent …
```
> fix: clearTimeout instead of clearInterval

- docs/src/pages/guides/migrating-to-react-query-3.md
- src/react/QueryClientProvider.tsx
After migrating to v3, I had a number of tests fail because I was not using an explicit queryCache before the migration. Another option is to create a default query client, but I prefer having to do this step yourself personally. 
The error I got was `Error: Uncaught [TypeError: Cannot read property 'defaultMutationOptions' of undefined]`
Added a error message so this is now the error my tests give:
> Throw error when QueryClientProvider has not been used to set a query client

- src/core/infiniteQueryBehavior.ts
- src/react/tests/useInfiniteQuery.test.tsx
- src/react/tests/useQuery.test.tsx
- src/react/tests/utils.tsx
Currently queries aren't canceled when using useInfiniteQuery.
> fix: cancellations for useInfiniteQuery

- src/core/query.ts
- src/react/useBaseQuery.ts
Fixed
Only work once when forceFetchOnMount is ture or refetchOnMount is 'always'
> fixed(queryObserver): fetch data twice when mounted 

- docs/src/pages/docs/guides/query-cancellation.md
Add sample code to manually cancel a query.
> docs: Update query-cancellation.md

- src/react/useInfiniteQuery.ts
- src/react/usePaginatedQuery.ts
- src/react/useQuery.ts
> change the order of overridden functions so that correct type inference is picked for **Object syntax**
```
// **A)** Parameter syntax with optional config
export function useQuery<TResult = unknown, TError = unknown>(
queryKey: QueryKey,
queryConfig?: QueryConfig<TResult, TError>
): QueryResult<TResult, TError>
// **B)** Object syntax
export function useQuery<TResult = unknown, TError = unknown>(
config: UseQueryObjectConfig<TResult, TError>
): QueryResult<TResult, TError>
```
I am using a query builder that creates a typed structure of **config** with generics.
when invoked with useQuery(configThatIsAlreadyTyped), it is picking syntax **A** instead of syntax **B** with Object syntax. 
This is because of the order of overridden methods. By changing the order the correct type is picked
> fix(types): change the order of types so that correct type inference is picked for **Object syntax**

- src/core/query.ts
Fixes #1370 
Although it seems to fix the issue, nothing makes sure that this value is not set to `undefined` elsewhere in the code (or prevent to set it in the future) since it's typed as `any`.
What do you think about introducing a [JsonValue](https://github.com/sindresorhus/type-fest/blob/master/source/basic.d.ts#L53) type for values that must be serializable?
> fix(hydration): set fetchMeta to null by default to make it serializable

- docs/src/pages/guides/migrating-to-react-query-3.md
- docs/src/pages/guides/queries.md
Fix typos in guides/migrating-to-react-query-3 and guides/queries.
Fixes #1378
> docs: fix typos in migration and queries guide

- docs/src/pages/docs/guides/testing.md
The first draft of #1244 was waiting for the nock expectation. But it was later changed to use the useQuery's isSuccess variable. This PR makes it explicit.
> docs: make hook return all necessary variables

- docs/src/pages/guides/mutations.md
Fix typos in guides/mutations.
> docs(typos): fix typos in mutations guide

- docs/src/pages/reference/QueryClient.md
- src/core/queryClient.ts
- src/core/tests/queryCache.test.tsx
- src/core/types.ts
- src/react/tests/useQuery.test.tsx
This is a follow up to #1375 that, I think, makes `resetQueries` more useful and less surprising.
> feat: resetQueries refetches active queries

- src/core/tests/utils.test.tsx
- src/core/utils.ts
> fix(queryCache): stop deepIncludes exception comparing null

- docs/src/pages/guides/default-query-function.md
Unfortunately the example on the `defaultQueryFn` guide page doesn't appear to work as-written for `v3.2.0`, but the example in `examples/default-query-function` _does_ work. 
This PR aims to fix this minor inconsistency in the docs.
Thanks for your work on this library -- it's extremely useful!
> docs: fix example in defaultQueryFn guide page

- src/core/query.ts
- src/core/tests/queryCache.test.tsx
- src/hydration/hydration.ts
- src/hydration/tests/hydration.test.tsx
Fixes for https://github.com/tannerlinsley/react-query/issues/1432 .
1. Prevents queries from getting cancelled in flight when a low cache time is set.
2. Do not hydrate cache time because environments can have different caching requirements.
> fix: allow queries to be fetched with zero cache time and do not hydrate it

- src/react/tests/useInfiniteQuery.test.tsx
- src/react/tests/useQuery.test.tsx
- src/react/useBaseQuery.ts
Fixes https://github.com/tannerlinsley/react-query/issues/1413
> fix: always render the latest observer state

- docs/src/pages/guides/mutations.md
> docs(mutations): fix typo in example url

- src/core/infiniteQueryBehavior.ts
- src/core/infiniteQueryObserver.ts
- src/core/query.ts
- src/core/queryCache.ts
- src/core/queryClient.ts
- src/core/queryObserver.ts
- src/core/retryer.ts
- src/core/types.ts
- src/react/tests/useQuery.test.tsx
- src/react/types.ts
- src/react/useBaseQuery.ts
- src/react/useInfiniteQuery.ts
- src/react/useQuery.ts
Fix for https://github.com/tannerlinsley/react-query/issues/1445 .
This PR swaps the query result type and query function result type inference. The first generic will now define the query function result type, and then the default query result type is inferred from this instead of the other way around.
Might be good to do a thorough review on this one as it is quite a big change.
> fix: infer result data type from query fn return type instead of the reverse

- src/core/types.ts
- src/react/tests/useQuery.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/1462
> fix: make sure typed query fn contexts are accepted

- src/core/queryObserver.ts
- src/react/tests/suspense.test.tsx
- src/react/tests/useInfiniteQuery.test.tsx
- src/react/tests/useQuery.test.tsx
- src/react/useBaseQuery.ts
With the change in https://github.com/tannerlinsley/react-query/pull/1449 components will always render the latest result instead of waiting for an update from the `QueryObserver`. This means that in some cases, the update is redundant because it has already been rendered. This PR will prevent those redundant renders.
Might fix: https://github.com/tannerlinsley/react-query/issues/1482
> fix: prevent redundant renders

- src/core/query.ts
- src/core/queryObserver.ts
- src/core/types.ts
- src/react/tests/QueryResetErrorBoundary.test.tsx
- src/react/useBaseQuery.ts
This PR contains two fixes:
- Always set query in `loading` state when fetching and no data is cached.
- Make sure components suspend and error when needed.
Fixes https://github.com/tannerlinsley/react-query/issues/1471
> fix: make sure queries are retried after an error boundary reset

- docs/src/pages/guides/initial-query-data.md
- src/core/query.ts
- src/core/types.ts
- src/react/tests/useQuery.test.tsx
Adds an `initialDataUpdatedAt` option to the query options. This allows initialData to be "tagged" with an updatedAt timestamp. Previously, it was possible for old initialData to be considered fresh if a `staleTime` was also provided to the query. Now, you can easily use both `initialData` and `staleTime` together without this edge case.
> feat: options.initialDataUpdatedAt

- docs/src/pages/reference/MutationCache.md
- docs/src/pages/reference/QueryCache.md
- src/core/mutation.ts
- src/core/mutationCache.ts
- src/core/query.ts
- src/core/queryCache.ts
- src/core/tests/mutationCache.test.tsx
- src/core/tests/queryCache.test.tsx
This PR adds global `onError` callbacks to `QueryCache` and `MutationCache`.
```js
const queryCache = new QueryCache({
onError: error => {
console.log(error)
},
})
const mutationCache = new MutationCache({
onError: error => {
console.log(error)
},
})
```
While it is possible to set `onError` in `defaultOptions`, it will not be called when a hook defines its own `onError`.
> feat: add error callback for queries and mutations

- docs/src/pages/guides/query-cancellation.md
Looking through the docs I noticed that the manual cancellation example refers to `cancelQueries` as part of `QueryCache` when it's actually part of `QueryClient`.
> Update manual cancellation section to refer to QueryClient

- src/devtools/devtools.tsx
Hello it is my pleasure to help in enhancing React-Query,
the button it turned to be more of  an orange but it have almost double contrast ratio
> Changing the new invalidate button color to have more contrast

- docs/src/pages/guides/initial-query-data.md
The documentation of `initialDataUpdatedAt` added in #1493 erroneously specifies the option as taking a unix timestamp, while it actually takes a JS timestamp.
> docs: fix initialDataUpdatedAt timestamp information

- src/core/query.ts
- src/react/tests/useQuery.test.tsx
When initialDataUpdatedAt is a falsy numeric value (e.g. 0), it will cause it to be replaced with Date.now(). This leads to unexpected behaviour, as one would expect the query to be invalidated instantly, if staleTime is set to an amount less than the result of Date.now(). This change will check if the value is numeric, and if so, always use this numeric value.
BREAKING: This changes the behaviour of the plugin for those users that have specified initialDataUpdated at <= 0.
> fix: :bug: Make sure queries which have dataUpdatedAt of 0 will be run

- src/devtools/devtools.tsx
Adding type attribute tells browser what type of button it is. For most browsers the default type is submit if no type is specified. This causes a full page post back in older legacy server rendered frameworks like asp.net webforms which render entire app inside a form tag.
> Added type attribute to all button elements

- docs/src/pages/guides/query-keys.md
The prop referenced `completed` But the variable used was `todoId`.
> Docs: Fixes incorrect prop variable in Todos example

- docs/src/pages/guides/initial-query-data.md
✍️ Remove a small typo from the docs
> docs: fix typo on Initial Query Data page

- src/react/tests/suspense.test.tsx
- src/react/tests/useInfiniteQuery.test.tsx
- src/react/tests/useQuery.test.tsx
- src/react/useBaseQuery.ts
Reverts the render optimization from https://github.com/tannerlinsley/react-query/pull/1487 because it is not guaranteed React will actually commit the render when a hook is called (renders might be discarded). Added a test to cover this behavior.
Fixes https://github.com/tannerlinsley/react-query/issues/1535
> fix: prevent missing renders

- docs/src/pages/guides/testing.md
Updated ReactQueryCacheProvider with QueryClientProvider as current testing documentation does not work when using React Query V3
> Update testing docs to match React Query V3

- docs/src/pages/reference/QueryClient.md
This is in accordance with issues faced when trying use certain query options in `prefetchQuery` and `prefetchInfiniteQuery`. I opened a [discussion](https://github.com/tannerlinsley/react-query/discussions/1596) and was [suggested](https://github.com/tannerlinsley/react-query/discussions/1596#discussioncomment-267856) to open a PR to mention/describe the options available.
> docs: mention query options strictly for useQuery

- docs/src/pages/guides/dependent-queries.md
Fix typo from 'achive' to 'achieve'. :)
> docs: Fix typos in dependent-queries.md

- docs/src/pages/guides/ssr.md
Fix typo in the [SSR guide](https://react-query.tanstack.com/guides/ssr#on-the-server)
`client` does not exist (should be `queryClient`)
> docs: fix typo in ssr guide

- docs/src/pages/reference/useQuery.md
Fixes some links which navigate to 404
> docs: fix guides references

- docs/src/pages/reference/useMutation.md
We've discussed in https://github.com/tannerlinsley/react-query/issues/241 and 
still same in `3.5.11` when you use `useMutation.mutate.onSuccess`, but `useMutation( , { onSuccess: ... })` doesn't.
I also made an example: https://codesandbox.io/s/sleepy-haze-s9p7z?file=/src/App.js
#1573
> docs: describe exceptional behavior of onSuccess of useMutation.mutate

- docs/src/pages/plugins/persist-localstorage.md
Clarify the docs around `persistWithLocalStorage` as overriding the default `cacheTime` appears to be necessary when creating the `QueryClient` instance.
Closes #1600
> Clarify setting cacheTime for persistWithLocalStorage to work properly

- src/core/query.ts
- src/core/tests/query.test.tsx
Fixes #1594.
Tested manually by resetting a query using dev tools while it's refetching. 
Added a test to cover this behaviour.
(My first PR here – happy to make further changes if I've missed anything!)
> fix: stop returning cancelledError on reset during fetch

- README.md
- docs/src/components/Nav.js
- docs/src/pages/index.js
Since folks are still on v2 and asking about those docs this adds a couple front-facing spots to find them: 
1. main repo README
2. main RQ docs nav
> docs: add v2 docs links

- docs/src/pages/reference/useQuery.md
The useQuery reference was missing some return value documentation as well as some option values.
**Options**
`initialDataUpdatedAt` was added to the list of options accepted and the api explanation
**Returns**
`dataUpdatedAt`, `errorUpdatedAt`, `isLoadingError`, and `isRefetchError` was added to the list of return values
`dataUpdatedAt` and `errorUpdatedAt` was added to the api explanation
> docs (useQuery): add some missing items to api

- examples/auto-refetching/package.json
- examples/basic-graphql-request/package.json
- examples/basic/package.json
- examples/custom-hooks/package.json
- examples/default-query-function/package.json
- examples/focus-refetching/package.json
- examples/load-more-infinite-scroll/package.json
- examples/optimistic-updates-typescript/package.json
- examples/optimistic-updates/package.json
- examples/pagination/package.json
- examples/prefetching/package.json
- examples/simple/package.json
- examples/star-wars/package.json
- examples/suspense/package.json
To get rid of nasty npm warning when running examples. 
```bash
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
```
> chore(examples): update axios version in examples folder

- src/core/infiniteQueryObserver.ts
- src/core/queryObserver.ts
- src/core/tests/queryClient.test.tsx
- src/core/tests/queryObserver.test.tsx
- src/react/tests/useQuery.test.tsx
Theoretically query observers can miss updates from a query if there was a query update between creating the observer and subscribing to the observer. With this change the observer will check if anything changed on subscribing and update if needed. Hopefully fixes https://github.com/tannerlinsley/react-query/issues/1657 .
> fix: notify on updates between mounting and subscribing

- docs/src/pages/reference/useQuery.md
- src/core/types.ts
> feat(types): Add optional cancelRefetch field to ResultOptions interface

- src/react/useBaseQuery.ts
- src/react/useIsFetching.ts
- src/react/useIsMounted.ts
- src/react/useMutation.ts
- src/react/useQueries.ts
Fixes https://github.com/tannerlinsley/react-query/issues/1724
> fix: make sure state is not updated when unmounted

- src/core/onlineManager.ts
Fixes https://github.com/tannerlinsley/react-query/issues/1503
> fix: check if the navigator global is available before usage

- src/core/queryObserver.ts
- src/core/tests/queryObserver.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/1639
> feat: run selector if reference changes to enable use of dependencies

- src/core/queryCache.ts
- src/core/tests/queryClient.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/1725
> fix: single query methods should be exact by default

- src/core/infiniteQueryBehavior.ts
- src/hydration/tests/ssr.test.tsx
- src/react/tests/useInfiniteQuery.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/1412
> fix: stop fetching pages when an infinite query unmounts

- src/core/queryObserver.ts
- src/core/tests/queryObserver.test.tsx
- src/react/tests/useQuery.test.tsx
Fixes https://github.com/tannerlinsley/react-query/issues/1540
> fix: handle select errors

- docs/src/pages/reference/useQuery.md
Add missing documentation for `retryOnMount` option.
[Relevant discussion here](https://github.com/tannerlinsley/react-query/discussions/1772#discussioncomment-355739)
> docs(useQuery): add retryOnMount option

- docs/src/pages/reference/useInfiniteQuery.md
I added a link to `/guides/default-query-function` because I was confused what that was referring to when I first started.
I also added a reminder to return the data AND the `pageParam`, because with `useQuery` I was used to only returning the data, so I wasn't sure how to properly reference the `page` in `useInfiniteQuery`.
> Add default query function reference + pageParam clarity

- docs/src/pages/guides/testing.md
The first testing example didn't work because useCustomHook returns undefined when first rendering.
Now we're waiting for useCustomHook to succeed and expect afterwards.
> fix(docs): fix testing example

- docs/src/pages/guides/query-functions.md
I tried to run the example in a React Native project and it gave me the following error:
`Error: Objects are not valid as a React child (found: TypeError: Cannot read property 'text' of undefined). If you meant to render a collection of children, use an array instead.`
I guess the `useQuery` hook tries to access the text property of the response which is not available when returning `json()`.
> docs: fixes fetch example which throws error

- src/core/query.ts
- src/core/tests/query.test.tsx
- src/react/tests/useInfiniteQuery.test.tsx
- src/react/tests/useQuery.test.tsx
Follow up on: https://github.com/tannerlinsley/react-query/issues/1412
> fix: queries should not end up in an error state when a component unmounts

- src/devtools/devtools.tsx
The toggle button can take up the full height of the page when using a `top-*` position.
> fix: toggle button position

- docs/src/pages/guides/mutations.md
not a native speaker but pretty sure this should be a "than" :)
may I as: in 
> This can be used to trigger component-specific side effects.
what does "component" refer to? A react component? I just find it a little uncertain in that context, but it might be because it's late here 😄  
Thanks!
> docs: fix typo

- docs/src/pages/reference/useQuery.md
I could not tell if this was left out intentionally or simply an oversight.
> docs: add isFetched to useQuery

- src/core/types.ts
- src/core/utils.ts
Mutable arrays can be passed to functions expecting readonly arrays but readonly arrays can't be passed to functions expecting mutable arrays. Since `react-query` doesn't actually mutate query keys, it should use the more permissive `ReadonlyArray` for `QueryKey` (and `MutationKey`) instead.
This allows users to do things like this without having to strip `readonly` from the inferred types:
```
const query = [["my.query.key", "abc"], () => fetch("/my/resource")] as const
```
> Prefer ReadonlyArray for query keys

- docs/src/pages/guides/initial-query-data.md
https://react-query.tanstack.com/guides/initial-query-data#initial-data-from-the-cache-with-initialdataupdatedat
```
- Getting initial data from the cache means the source query you're using to look up the initial data from is likely old, but `initialData`
+ Getting initial data from the cache means the source query you're using to look up the initial data from is likely old, but `initialData`.
```
> docs (initial-query-data): Add missing period

- src/core/queryClient.ts
- src/core/tests/queryClient.test.tsx
This PR fixes the issue reported here: https://github.com/tannerlinsley/react-query/issues/1931
When a query was invalidated and `refetchActive` was set to `false`, the query would still be refetched, unless `refetchInactive` was set to `true`. 
The PR fixes this by not letting the `inactive` option in the query filters default to `false` if it was actually `undefined`.
> fix: Do not refetch active queries if "refetchActive" is set to "false"

- docs/src/pages/reference/useQuery.md
> docs(useQuery): add doc for `queryKeyHashFn`

- docs/src/pages/examples/nextjs.mdx
> docs(next-example): correct typo (SSR -> SSG)

- src/core/infiniteQueryObserver.ts
- src/core/types.ts
> fix(useQuery): type of initialData now corresponds to the type returned by the query-fn

- docs/src/components/markdown.module.css
- docs/src/pages/guides/migrating-to-react-query-3.md
In version 2 the `QueryStatus` typing was:
```typescript
export enum QueryStatus {
Idle = 'idle',
Loading = 'loading',
Error = 'error',
Success = 'success',
}
```
https://github.com/tannerlinsley/react-query/blame/8aeb209c3b9c84382a88059afbc398be93a69b33/src/core/types.ts#L183
And now in version 3 is:
```typescript
export type QueryStatus = 'idle' | 'loading' | 'error' | 'success'
```
https://github.com/tannerlinsley/react-query/blame/7b14ef519a544d725f2cff99574f0a01f92b8c94/src/core/types.ts#L257
- documented the change described above
- added underline to links that are children of headings
this affects anchor links but these already have an underline property set, so I think there's no issue with that
> docs(QueryStatus): change from enum to union type

- src/core/queryClient.ts
- src/core/tests/queryClient.test.tsx
- src/core/types.ts
This PR fixes the issue outlined in #2099.
I noticed that `prefetchInfiniteQuery` did not have any generic types. Was this done on purpose, and if not, need they be added?
> fix(types): adds queryKey generic to queryClient functions

- docs/src/pages/guides/infinite-queries.md
This code sample has two problems:
"oldPagesArray?.pages" only contains an array of different page arrays, so we should not write "page.data" to filter because "page.data" is undefined and we should write "page" instead.
Another mistake is the value pushed to the "newPagesArray" and the following value must be replaced: "newData"
> docs(useInfiniteQuery): Correction of two mistakes in the code sample

- src/core/types.ts
- src/react/types.ts
[useMutation](https://react-query.tanstack.com/reference/useMutation) has void return type but in code has not
In my code
```js
const onMutate = () => {
const previous = queryClient.getQueryData<CartProductsDataType>(queryKey);
return previous;
};
const onError = (error: any, variable: AddOptionItem, context: CartProductsDataType | undefined) => {
queryClient.setQueryData(queryKey, context);
};
return useMutation(QueryKey.CARTS, mutateFn, {
onMutate,
onError,
});
```
onMutate return `CartProductsDataType or undefind` because of `getQueryData` but in useMutation error!!!
because useMutation onMutate function type only return `Promise<Context> or Context` not has `undefined`
so i try to add `undefined` type in onMutate return type
> Add `undefined` return type in onMutate 

- src/devtools/devtools.tsx
- src/devtools/utils.ts
As noticed in [This PR](https://github.com/tannerlinsley/react-query/pull/2110) `isStale` utility function is redundant.
Therefore removing this utility function in favor of directly calling the function that is always available.
> refactor: remove redundant isStale utility

- docs/src/pages/reference/useQuery.md
`useErrorBoundary` is listed as a valid option in the useQuery [API reference](https://react-query.tanstack.com/reference/useQuery), however, an actual explanation is missing. This PR adds one.
> docs(useQuery): add the useErrorBoundary option

- src/hydration/react.tsx
- tsconfig.json
- tsconfig.types.json
Closes #2112 
This PR changes the relative import of `useQueryClient` to an absolute one (`from 'react-query'`). As described in the issue, this is important to avoid bundling parts of the main package into the hydration entry point and fixes a bug caused by the `QueryClientProvider`-context not lining up between the different entry points.
I've verified this fixes the broken NextJS-example as well as our code base at work.
Also added TS-resolves for this path so TS knows where to look for the types.
There are more relative imports in the hydration package, but they are all related to types which is fine.
> Fix "No queryClient set" when hydrating

- src/core/infiniteQueryObserver.ts
- src/react/tests/suspense.test.tsx
- src/react/useBaseQuery.ts
Closes: https://github.com/tannerlinsley/react-query/issues/2095
This fixes the useInfiniteQuery suspense bug where `options.behavior` was missing and so `infiniteQueryBehavior.onFetch` was not being called, resulting incorrect query `data`.
> Fix useInfiniteQuery suspense bug

- src/core/query.ts
- src/core/types.ts
- src/react/tests/useQuery.test.tsx
This PR fixes the following edge case issue in typings:
```ts
import { QueryFunction, useQuery } from "react-query";
type MyData = number;
type MyQueryKey = readonly ["my-data", number];
const getMyData: QueryFunction<MyData, MyQueryKey> = async ({
queryKey: [, n],
}) => {
return n + 42;
};
// ...
const myData = useQuery({
queryKey: ["my-data", 100],
queryFn: getMyData,
});
```
**Before**
```
No overload matches this call.
Overload 1 of 3, '(options: UseQueryOptions<number, unknown, number, (string | number)[]>): UseQueryResult<number, unknown>', gave the following error.
Type 'QueryFunction<number, MyQueryKey>' is not assignable to type 'QueryFunction<number, QueryKey>'.
Type 'QueryKey' is not assignable to type 'MyQueryKey'.
Type 'string' is not assignable to type 'readonly ["my-data", …
```
> Add TQueryKey to QueryFunction generic type in QueryOptions, remove ensureArray from Query

- docs/src/pages/overview.md
Added double quotes to improve readability.
> fix: added quotes to improve reliability of line

- docs/src/pages/guides/mutations.md
Updated the link to the React event pooling docs and updated the info to apply to React 16 and earlier.
> fix: event pooling info

- src/core/focusManager.ts
Typings did not allow passing a function taking `setFocused` to addEventListener
Fixing by using the same typings as in `onlineManager.ts`, tweaked to allow default Window.Event behavior
This allows setting the React Native focus handler like this:
```ts
focusManager.setEventListener((setFocused) => {
const listener = (status: AppStateStatus) => setFocused(status === "active");
AppState.addEventListener("change", listener);
return () => AppState.removeEventListener("change", listener);
});
```
> fix: focus handler typings

- docs/src/pages/guides/filters.md
1. Make comment in the code snippet for `removeQueries` more exact
2. correct comment for `refetchQueries` used for `posts` query key, to use 'posts' instead of 'post'.
> docs(Query Filters): Correct/Make More Exact: Query Filter Object Code Snippet Comments

- docs/src/pages/guides/updates-from-mutation-responses.md
This adds curly brackets to the arrow function which "disables" the implicit return value for TypeScript users, who see an error for this example.
CodeSandbox, which shows the error:
https://codesandbox.io/s/laughing-chaplygin-u1mdr?file=/src/App.tsx
> Add curly brackets to mutation example for TypeScript error

- src/core/query.ts
- src/core/tests/query.test.tsx
- src/devtools/devtools.tsx
- src/devtools/utils.ts
- src/react/tests/suspense.test.tsx
Adding 'getObserversCount' util
Reson for making this change:
The [observers](https://github.com/tannerlinsley/react-query/blob/master/src/core/query.ts#L159) on the query is private property, therefore Typescript is complaining when trying to use it.
DevTools is using the length of the observers in a couple of places like [here](https://github.com/tannerlinsley/react-query/blob/master/src/devtools/utils.ts#L23)
Since this property should probably stay as private, I have added utility to get the observers count as a getter method.
> feat(query): add 'getObserversCount' util

- docs/src/pages/plugins/persistQueryClient.md
- src/persistQueryClient-experimental/index.ts
The reason to add this is to be able to customize the hydrate/dehydrate behaviour on the persistQueryClient. For instance, I don't want a network error to remove a cache entry from my persisted state, I want the client cache to be equivalent to the persisted cache at all time, with dehydrate options, I can achieve this behaviour.
> Added hydrate and dehydrate options to the persistQueryClient function

- src/devtools/devtools.tsx
- src/devtools/theme.tsx
Move the default theme to the proper file.
Fix types for `theme.tsx`
No functional changes.
> refactor(devtools): move default theme to theme file, fix types

- devtools/package.json
Simple fix to remove the `DeprecationWarning: Invalid 'main' field` warning that comes up now on Node 16.x . I just fixed the `main` and `module` paths in `devtools/package.json` to be relative to their current directory.
Fixes #2233
> fix: Node 16 Invalid 'main' field warning from devtools

- docs/src/pages/guides/testing.md
Update testing documentation to V3.
> docs: update testing

- docs/src/pages/reference/QueryClient.md
I noticed my default `staleTime` wasn't applying after I introduced a utility to namespace query keys. This was because I'd assumed `setDefaultOptions` would merge with previously-defined defaults, but it doesn't.
I fixed this in my project by merging with a default config object:
```diff
+ import { merge } from "lodash";
```
And then:
```diff
- queryClient.setDefaultOptions({
-     queries: {
-         queryKeyHashFn: myFunction,
-     },
- });
+ queryClient.setDefaultOptions(
+     merge<DefaultOptions, DefaultOptions>(
+         {
+             queries: {
+                 queryKeyHashFn: myFunction,
+             },
+         },
+         DEFAULT_QUERY_CLIENT_OPTIONS
+     )
+ );
```
I'm opening this PR to discuss mentioning this behavior in the docs. Additionally, `setDefaultOptions` …
> docs: document that setDefaultOptions overwrites previous defaults

- docs/src/pages/reference/hydration/HydrateComp.md
In docs for `Hydrate` component, fixes reference to outdated `useQueryCache` hook, plus minor grammatical edits.
> docs: fix typo/outdated hook reference

- src/devtools/devtools.tsx
Catch the error using noop when refetching the query via devtools
fixes #2014
> fix(devtools): fix devtools crash on rejected promises on refetch

- docs/src/pages/guides/mutations.md
docs(mutations): Update mutations page side effects section
There should be information that `mutate` callbacks won't run when component will be unmounted.
> docs(mutations): Update mutations page side effects section

- devtools/index.js
As discussed with @tannerlinsley in #2381, this PR changes the current Devtools render behavior to only render the component when `NODE_ENV === 'development'`.
The current verification only disables Devtools for production mode, which causes Devtools to be rendered when `NODE_ENV === 'test'` and creates some issues on tests such as Devtools being rendered on snapshots and triggering a lot of jests warnings. This PR solves this issue.
> fix: display devtools only in development

- docs/src/pages/comparison.md
I just noticed this detail while I was reading the comparison.
> updating rtk-query links in Normalized Caching topic in the docs

- src/devtools/devtools.tsx
Fixes #2375.
Previously, opening and closing the devtools only changed it opacity (and subscribed/unsubscribed to queries).  That meant that it was still possible to tab through the elements in the panel, even when it was closed.
With this change, when the panel starts out closed, we set a `visibility: hidden` style, so that it is gone from both the accessibility tree and the tab order.  I've also set up transition listeners so that before a transition starts, if the devtools are opening, we turn visibility to visible, so that the opacity fade-in works correctly.  Likewise, on a transition end, we check if the panel is closed, and turn visibility to hidden.
I tested this by compiling, copying the built files into my project's node_modules, and running my app, and it worked as I expected. …
> Hide devtools when closed, prevent focus

- docs/src/pages/comparison.md
Stale While Revalidate contains incorrect information in the comparison table.
See Apollo [docs here](https://www.apollographql.com/docs/react/data/queries/#cache-and-network) which explain: 
> Apollo Client executes the full query against both the cache and your GraphQL server. The query automatically updates if the result of the server-side query modifies cached fields.
Addresses #2151
> Stale While Revalidate - Update comparison.md

- docs/src/pages/guides/query-functions.md
[Per the v3 breaking changes, query key parts are not automatically spread to query functions.](https://react-query.tanstack.com/guides/migrating-to-react-query-3#query-key-partspieces-are-no-longer-automatically-spread-to-the-query-function)
I've removed an old usage example that did it this way and added an example using `context.queryKey` instead.
> docs: update query function usage examples

- src/core/queryObserver.ts
- src/react/tests/useQuery.test.tsx
the added test case confirms the issue - it fails on master.
closes #1876
> fix(useQuery): don't inform observers about CancelledErrors

- src/core/queryClient.ts
- src/core/tests/queryClient.test.tsx
- src/core/tests/utils.test.tsx
- src/core/types.ts
- src/core/utils.ts
> fix: update matchQuery logic to cater for all permutations

- docs/src/pages/guides/testing.md
When testing my app with jest + enzyme I had a lot of problems trying to resolve the `useQuery` api call, then I found on [this blog post](https://tkdodo.eu/blog/testing-react-query#turn-off-retries) explaining that disabling the default retries can make things easier, and that indeed worked for me.
So I just took a piece of the doc written on that blog post (because it was already well written and clear) and added it to the official docs, I really think that'll help out new react-query users test their apps if they come across that issue 🤘
> docs: Update testing with disabled retries

- docs/src/pages/plugins/createAsyncStoragePersistor.md
- src/createAsyncStoragePersistor-experimental/index.ts
This function was being called as `createAsyncStoragePersistor` in the docs but was exported as `asyncStoragePersistor`
> fix: rename asyncStoragePersistor to createAsyncStoragePersistor

- src/devtools/devtools.tsx
- src/devtools/tests/devtools.test.tsx
- src/devtools/tests/utils.tsx
- ✅.  Added the following tests for devtools (except query details explorer)
- Opening and closing the devtools panel
- Displaying the correct states for queries
- Displaying all the query hash in the rows and opening the query details explorer upon clicking it
- Searching the queries
- Sorting the queries via different sorting filters available
- ♿️    Added accessibility labels to buttons and inputs, which not only helped in writing good tests but also improved the overall accessibility of devtools
- 🐛.  Fixed a bug that sorted queries incorrectly. While adding the test cases for sorting queries, I found that the sorting was not working as expected because of an incorrect key name being used (`updatedAt` instead of `dataUpdatedAt`)
Fixes #2371
> test(devtools): Add base tests for react-query devtools

- src/core/types.ts
- src/react/types.ts
Hey maintainers,
As I can see, `Promise<A> | Promise<B>` is stricter than `Promise<A | B>` and to the point that it won't work with async functions.
In the case of `onMutate`, because we currently define its type as
```ts
onMutate?: (variables: TVariables) => Promise<TContext> | Promise<undefined> | TContext | undefined;
```
,  when we set an async function to it we'll receive a type error but it's very obscure and appears at another place.
So in this PR, I set the return type of `onMutate` to `Promise<TContext | undefined>` instead of `Promise<TContext> | Promise<undefined>` to relax it to make it work with async functions.
> fix(MutationOptions): improve the type of onMutate

- docs/src/pages/guides/query-cancellation.md
Importing `CancelToken` imports type. The propose change matches [recent docs for cancellation of axios here](https://github.com/axios/axios#cancellation).
> fix: example of axios cancelling request 

- docs/src/pages/reference/QueryClient.md
- src/core/queryClient.ts
- src/core/tests/queryClient.test.tsx
Similar to `setQueriesData`, a "get" version to fuzzily return multiple matching queries.
Based the code off of `setQueriesData` and `getQueryData` - couldn't get typing quite right without the assertion to `TData` in the map. I'm sure there's a better way to go with that.
Hope this at least points in the right direction!
> feat (QueryClient): getQueriesData for matching multiple queries

- src/core/queriesObserver.ts
Fixing typo and renaming `prevOberversMap` to `prevObserversMap`
> style(queriesObserver): Renames to prevObserversMap

- src/core/queryObserver.ts
- src/core/tests/queryObserver.test.tsx
- src/react/tests/useQuery.test.tsx
by checking for the idle state. this will make idle queries with placeholderData show up as success queries for the observer immediately
closes #1749
> fix (useQuery): apply placeholderData also to disabled queries

- src/core/queryObserver.ts
- src/react/tests/suspense.test.tsx
- src/react/tests/useQuery.test.tsx
Related issue: https://github.com/tannerlinsley/react-query/issues/2187
Change `shouldFetchOptionally` condition to not change the `status` of result to `loading` when `state.status` is `error`.
1. `result.isLoading` is `true` in [this line](https://github.com/tannerlinsley/react-query/blob/master/src/react/useBaseQuery.ts#L110) when `result.error != null`
2. So the error did not propagate to the error boundary. (next condition)
3. Check the `createResult` function and `shouldFetchOptionally` function
Fixes tannerlinsley/react-query#2187
> Special thanks to @flybayer
> fix(core): change `shouldFetchOptionally` condition

- src/core/queryObserver.ts
- src/react/tests/suspense.test.tsx
- src/react/tests/useQuery.test.tsx
> related pull request: #2556 
Change `prevQuery` to `query` in `shouldFetchOptionally` because of checking query key changed
situation.
- This PR(#2556) fixes a bug which an error was not caught when the query was reset.
- When query key changed, infinity re-request is reproduced.
- prevQuery.state.status === 'success'
- query.state.status === 'error'
> fix(core): change `prevQuery` to `query` in `shouldFetchOptionally` function

- docs/src/pages/guides/infinite-queries.md
- docs/src/pages/reference/QueryClient.md
- src/core/infiniteQueryBehavior.ts
- src/core/queryClient.ts
- src/core/queryObserver.ts
- src/core/tests/queryClient.test.tsx
- src/core/types.ts
- src/react/tests/useInfiniteQuery.test.tsx
> feat(infiniteQuery): add possibility to decide which pages should be refetched

- docs/src/pages/react-native.md
I've been using this Flipper plugin and it does the job well! Not super polished, but to have React Query devtools on React Native is a massive step up.
(I'm not affiliated, just found it the other day).
Also grammar improvements.
> docs: Add link to 3rd party React Native devtools

- src/devtools/devtools.tsx
- src/devtools/utils.ts
This PR makes the DevTools client-side-only to avoid hydration issues (see https://github.com/tannerlinsley/react-query/issues/1774).
It renders `ReactQueryDevtools` as `null` during SSR, and then renders normally after mount.
I'm experiencing a failed test on my machine, even on the `master` branch without any change of mine:
```
Expected: "[\"query-2\"]"
Received: "[\"query-1\"]"
324 |     fireEvent.change(sortSelect, { target: { value: 'Last Updated' } })
325 |     queries = await screen.findAllByText(/\["query-[1-3]"\]/)
> 326 |     expect(queries[0]?.textContent).toEqual(query2Hash)
|                                     ^
327 |     expect(queries[1]?.textContent).toEqual(query3Hash)
328 |     expect(queries[2]?.textContent).toEqual(query1Hash)
329 | 
at …
```
> Do not render DevTools during SSR

- src/core/hydration.ts
- src/core/index.ts
- src/core/tests/hydration.test.tsx
- src/hydration/index.ts
- src/hydration/react.tsx
- src/react/Hydrate.tsx
- src/react/index.ts
- src/react/tests/Hydrate.test.tsx
- src/react/tests/ssr-hydration.test.tsx
Following: https://github.com/tannerlinsley/react-query/discussions/2370
Move hydration utilities to the core.
Retain old exports for backward compatibility.
Export additional type that was missed before.
> feat(hydration): move hydration utilities to core, keeping old exports

- docs/src/pages/reference/QueryClient.md
- docs/src/pages/reference/useMutation.md
- docs/src/pages/reference/useQuery.md
- src/core/types.ts
- src/react/tests/suspense.test.tsx
- src/react/tests/useQuery.test.tsx
- src/react/types.ts
- src/react/useBaseQuery.ts
- src/react/useMutation.ts
- src/react/utils.ts
This adds a `shouldThrowError` option that can be used when `useErrorBoundary`/`suspense` to decide whether an error should be thrown or handled locally on the `error` state.
It's nice to have errors thrown to error boundaries. However sometimes you have some errors you do want to handle within the component instead of having them thrown to external boundaries.
e.g. In a product list page you may want to handle an "invalid product filter" from the server with an in-list error instead of it being thrown out to an error boundary. But you still may want to use an error boundary so 500 errors from the server and network errors still get thrown out to a shared error boundary.
> Allow handling some errors locally while using error boundaries

- src/core/mutationObserver.ts
- src/core/types.ts
- src/react/types.ts
fixes https://github.com/tannerlinsley/react-query/issues/2601
This PR refactors useMutationResult type to follow the same approach/logic of useQueryResult type.
> fix(UseMutationResult): result type should be more specific to allow type narrowing

- src/core/queryClient.ts
- src/core/queryObserver.ts
- src/core/types.ts
two issues:
1) The types inferred for the `refetch` function returned from useInfiniteQuery were wrong, as the input to the function is not of type InfiniteData; It's quite hard to infer the correct type, so making the function generic and defaulting to unknown is the safer choice. Users can now still explicitly provide the generic.
2) for all other methods on the queryClient, generics were mising and types for pages / allPages were always unknown. Adding a generic to refetchQueries / invalidateQueries / resetQueries that also defaults to unknown fixes that and makes those function easier to work with
> fix(types): fix generics for refetchPage function

- package.json
- src/devtools/Logo.tsx
- src/devtools/devtools.tsx
- src/devtools/styledComponents.ts
- src/devtools/theme.tsx
- src/devtools/useLocalStorage.ts
- src/devtools/useMediaQuery.ts
- src/devtools/utils.ts
- yarn.lock
Make devtools and all related helpers type safe
> Add types for devtools

- src/react/useInfiniteQuery.ts
- src/react/useMutation.ts
- src/react/useQuery.ts
when using the overloaded version with multiple arguments, passing the same value inside options doesn't have any effect and is ignored at runtime, e.g.: `useQuery(key, fetchIt, { queryKey: 'foo' })`. With this fix, we disallow that on type level
closes #2647
> fix(types): exclude queryKey / queryFn from options if they have been provided as a separate argument

- docs/src/pages/reference/QueryClient.md
Adding this information since I think it wasn't mentioned and may cause some confusion for other people.
Add side effects from using `setQueryData`.
I only know successful `setQueryData` will trigger `onSuccess` callback from that query, but if there is any more side effects that can be added, please let me know.
Thanks.
> docs: Add side effects from using setQueryData

- src/persistQueryClient-experimental/index.ts
Import hydration utilities directly from the core.
Apparently, it caused issues after https://github.com/tannerlinsley/react-query/pull/2497 got merged.
> fix: import hydration utils from core in persistQueryClient

- package.json
Currently development and production bundles have differences that affects React Query batching update. Changing `sideEffects` makes both `setBatchUpdatesFn` and `setLogger` to be included on final production bundle without affecting development. 
The thing here is to add index.js files to sideEffects as they calls the side effect directly. A similar code is available on webpack docs, which explains which files should be added there
- fix(core): add index.js files to sideEffects
https://github.com/tannerlinsley/react-query/issues/2675
https://github.com/tannerlinsley/react-query/issues/2644
> Missing batch updates on Production

- docs/src/pages/devtools.md
I was struggling to understand why the devTools were not rendering in our application. The docs currently state that if `process.env.NODE_ENV === 'production'`, they will not be included in the build.
However, this is misleading, because the actual logic as [you can see here](https://github.com/tannerlinsley/react-query/blob/master/devtools/index.js) is to only include the devTools if `process.env.NODE_ENV === 'development'`.
In the app I was working on, during development, our `NODE_ENV` was actually set to `dev`. While I understand it's a convention in the node world to use `process.env.NODE_ENV === 'development'`, for whatever reason this app was setup slightly differently, and the docs were somewhat misleading here. Hopefully this should prevent someone else from experiencing the same …
> docs(devTools): Clarify node env logic for devtools

- docs/src/pages/guides/mutations.md
I know everyone loves the one-liner code. It looks awesome!
But in this certain case, I thought newTodo is the second argument to useMutation hook here `useMutation(newTodo => axios.post('/todos', newTodo))` which was very confusing for me when I tried to code and it didn't work. It took me a very long time to notice that small detail.
I think the return statement will drastically remove that confusion.
> Return Statement

- src/devtools/devtools.tsx
Change the `isOpen` prop for the ReactQueryDevtoolsPanel component to default
to true. The subscriptions aren't set up when no isOpen prop is passed, which makes
the panel not show any updates when used without the isOpen prop.
Closes #2745
> fix(devtools): Default ReactQueryDevtoolsPanel isOpen to true

- src/devtools/Explorer.tsx
- src/devtools/devtools.tsx
- src/devtools/styledComponents.ts
closes https://github.com/tannerlinsley/react-query/issues/2756
- Changes all instances of `rem` to `em` to prevent styling conflict for developers.
> fix(style): replace all instances of rem with em.

- src/core/query.ts
- src/core/queryClient.ts
- src/core/retryer.ts
- src/core/types.ts
Background: it would be nice if I didn't have to do [this](https://github.com/trpc/trpc/pull/1186#discussion_r738841851) :)
Technically, this is a breaking change - the other idea I had was to just expose these types in the `types.ts`-file but then the linter complained about circular dep.
It's hard structuring what is "internal" and what is "external" types - the way I go about it in tRPC is that I have folders called `internal/` in various places and I make sure to only cherry-pick from those, and they aren't cherry-picked I do `export *`
> expose `CancelOptions` & `SetDataOptions` 

- docs/src/pages/plugins/createAsyncStoragePersistor.md
- docs/src/pages/plugins/createWebStoragePersistor.md
- src/createAsyncStoragePersistor-experimental/index.ts
- src/createWebStoragePersistor-experimental/index.ts
Right now the (experimental) persistor functionality or at least the two built-in ones use simple JSON `stringify` and `parse`.
This is fine, but I'd like to get some more control over the serialization and deserialization of the data.
For example, the data I store in `react-query`'s cache is already JS objects which are not valid JSON in some cases - e.g. `Date` reviving upon `fetch`ing from the server:
```js
const data = fetch('https://my-api.com')
.then(response => response.text())
.then(text => JSON.parse(text, dateReviver); // see https://gist.github.com/davehax/2f32e7b09c3da3531601e6543fcff82e for an example for a `dateReviver` implementation
```
More details in https://github.com/tannerlinsley/react-query/discussions/2771
> feat: add optional functions to serialize and deserialize from Storage Persistors

- docs/src/pages/guides/query-cancellation.md
Explained that this new AbortSignal feature was introduced at 3.30.0 and that users need to either upgrade (recommended) or use the old cancel function.
> docs: add note on AbortSignal version availability

- .github/workflows/test-and-publish.yml
- codecov.yml
> Add code coverage report

- src/devtools/Explorer.tsx
Resolved bug mentioned in this [comment](https://github.com/tannerlinsley/react-query/pull/2760#issuecomment-961812722)
Fix progressively smaller font size for Explorer entries in devtools
Set Entry font-size to 1em, because it is indented multiple time within each other.
This causes the font to get smaller and smaller as `em` is relative to the parent font size.
> Fix progressively smaller font size for Explorer

- jest.config.js
- src/createWebStoragePersistor-experimental/index.ts
- src/createWebStoragePersistor-experimental/tests/storageIsFull.test.ts
fix #1701
when storage exceeded the quota.
1. try to clean the mutations (from old to new by creating time)
2. try to clean the queries (from old to new by updating time)
> try to clean the old persistented data when storage full

- docs/src/pages/reference/QueryCache.md
`queryCache.subscribe` `callback` documentation does not reflect the actual callback implementation:
Current doc:
```ts
const callback = query => {
console.log(query)
```
It should be:
```ts
const callback = event => {
console.log(event.type, event.query)
}
```
> docs(queryCache): fix subscribe callback argument: event instead of query

- src/react/tests/QueryResetErrorBoundary.test.tsx
- src/react/useBaseQuery.ts
fixes #2930 
one caveat is that the disabled query will be rendered with `status: 'error'`, because that's the state the query is in. Usually, with `useErrorBoundary`, you'd expect to _never_ see a query in error state. However, I think disabled queries can be in all resolved states (success, error, idle), so if you use `enabled`, that's what you get. This behaviour is documented with a separate test.
> fix(useQuery): make sure that disabled queries in error state don't throw

- src/react/tests/QueryResetErrorBoundary.test.tsx
- src/react/useBaseQuery.ts
the fix for disabled queries was wrong, because disabled queries still need to throw if they are fetching due to some other means, like `refetch`. However, if a query has just been reset, we want to skip throwing for one render cycle. The useEffect that clears the reset will then make sure that further errors will be thrown
> fix(useQuery): don't throw error if errorBoundary has just been reset

- docs/src/pages/guides/migrating-to-react-query-4.md
- docs/src/pages/reference/QueryClient.md
- docs/src/pages/reference/useQuery.md
- src/core/infiniteQueryObserver.ts
- src/core/query.ts
- src/core/queryClient.ts
- src/core/queryObserver.ts
- src/core/tests/queryClient.test.tsx
- src/core/tests/queryObserver.test.tsx
- src/react/tests/useQuery.test.tsx
> V4: streamline cancel refetch

- docs/src/pages/guides/query-cancellation.md
It is possible to set an `AbortSignal` in the `GraphQLClient` constructor.
```js
const query = useQuery('todos', ({ signal }) => {
const client = new GraphQLClient(endpoint, {
signal,
});
return client.request(query, variables)
})
```
But unfortunately, it is not possible to define a `signal` per request:
https://github.com/prisma-labs/graphql-request/issues/182
It means that the GraphQL Code Gen React Query plugin cannot support a `signal` for the moment with graphql-request :pensive:
The solution is to:
- PR graphql-request to support a signal per request
- PR GraphQL Code Gen React Query Plugin to send the signal to the graphql-request request.
> docs(cancel): add graphql-request example

- docs/src/pages/reference/useMutation.md
- src/core/mutation.ts
- src/core/mutationCache.ts
- src/core/types.ts
- src/react/tests/useMutation.test.tsx
- src/react/types.ts
the same meta that already exists in Query and is accessible in
queryCache is now also usable in mutationCache and can be passed in
useMutation, just as in useQuery
Context: https://github.com/TkDodo/blog-comments/issues/29#issuecomment-963095663
> feat: meta to Mutation

- docs/src/pages/guides/migrating-to-react-query-4.md
- src/core/infiniteQueryBehavior.ts
- src/core/query.ts
- src/core/retryer.ts
- src/core/tests/query.test.tsx
- src/core/tests/queryClient.test.tsx
- src/reactjs/tests/useInfiniteQuery.test.tsx
- src/reactjs/tests/useQuery.test.tsx
- Removes cancel method from wherever possible
- Updates query cancellation tests to use abort controller and remove tests using the older method
- Update the migration docs
Fixes #2915
> refactor: Remove deprecated promise cancel

- src/react/useQueries.ts
> Add useMemo() to useQueries() to avoid constant rerendering

- src/core/queriesObserver.ts
- src/core/tests/queriesObserver.test.tsx
- src/core/utils.ts
- src/react/tests/useQueries.test.tsx
#closes 2680
When `keepPreviousData` is on, search for a query observer no longer used instead of relying on observer order and indexing. Trying to match observers by index could cause infinite request loops when switching queries. See #2680 for more 
This does complicate the `getOptimisticResult` and `updateObservers` calls a bit. Now they both essentially do the same search for unused observers. The observers lists for the `queriesObserver` are only updated in the `updateObservers`, though. 
This does cause some extra updates, as can be seen in the tests. If I understand correctly, they probably are due to the `setOptions` calls being called both on `getOptimisticResult` and `updateObservers` calls. I tried for quite a while to get rid of the extra updates, but couldn't find a way that …
> fix(useQueries): search for unused observers if keepPreviousData (#2680)

- src/core/query.ts
- src/core/retryer.ts
- src/react/tests/useQuery.test.tsx
> 3031 continue retries

- docs/src/pages/reference/MutationCache.md
- src/core/mutation.ts
- src/core/mutationCache.ts
- src/core/tests/mutationCache.test.tsx
following up on https://github.com/tannerlinsley/react-query/discussions/3035 this pr allows adding a `onMutate` callback to the global `MutationCache`. this enables e.g. managing toast notifications for mutations in one central place (see example below). note that it is not allowed to return a context value from the `onMutate` callback.
example:
```js
import { MutationCache, QueryClient, QueryClientProvider } from "react-query";
import { Toaster, toast } from "react-hot-toast";
import { useState } from "react";
export default function App({ Component, pageProps }) {
const [client] = useState(() => {
return new QueryClient({
mutationCache: new MutationCache({
onMutate(variables, mutation) {
toast.loading("Submitting...", { id: mutation.mutationId });
},
onSuccess(data, variables, context, …
```
> Add `onMutate` to `MutationCache`

- docs/src/pages/react-native.md
When using React Query with React Native you often have to handle the following use cases:
- Online status management
- Refetch on App focus
- Refetch on Screen focus
The React Native page now includes ready to use examples for these common cases.
> docs(react-native): add  code examples for common use cases

- src/core/queriesObserver.ts
- src/react/tests/useQueries.test.tsx
Fix for `queriesObserver.getOptimisticResult` to correctly call `getOptimisticResult` on the observers. 
This was an issue I introduced in PR #2866. There I had needed to tweak [two](https://github.com/tannerlinsley/react-query/pull/2866/files#diff-27ab6cf11862f134526488fd6c22381bf484a5ad9a6d7dc36535e1d3e2d5aa42R209) [original](https://github.com/tannerlinsley/react-query/pull/2866/files#diff-27ab6cf11862f134526488fd6c22381bf484a5ad9a6d7dc36535e1d3e2d5aa42R131) tests, which now in hindsight were off due to this issue. I now reverted those tests back to the original form.
Now testing the issue, I also noticed a small issue with the order of the observers returned by `findMatchingObservers`: with `keepPreviousData: true`, any repurposed observers would be returned last, potentially in …
> fix(queriesObserver): fix getOptimisticResult, order of returned observers

- docs/src/pages/guides/does-this-replace-client-state.md
* changed "any boilerplate code that use"  to boilerplate code that was used" to improve the clarity of the sentence.
> docs: Update does-this-replace-client-state.md

- docs/src/pages/guides/window-focus-refetching.md
- Fixed incorrect function signature of AppState change event listener
- Update cleanup function as `removeEventListener` is [deprecated](https://reactnative.dev/docs/appstate#removeeventlistener)
> docs: Make react-native example up-to-date

- src/core/infiniteQueryObserver.ts
- src/react/tests/suspense.test.tsx
- src/react/tests/useInfiniteQuery.test.tsx
by correctly forwarding notifyOptions
closes #3068
> fix(useInfiniteQuery): fix infinite re-renders when select produced a new result

- docs/src/pages/guides/migrating-to-react-query-4.md
- docs/src/pages/guides/parallel-queries.md
- docs/src/pages/reference/useQueries.md
- src/reactjs/tests/useQueries.test.tsx
- src/reactjs/useQueries.ts
Update the `useQueries` API to take an object as input. This way we can define top level options that are true for all queries and a list of queries.
```js
useQueries({ 
queries: [{ queryKey1, queryFn1, options1 }, { queryKey2, queryFn2, options2 }, ... ] 
})
```
> feat(useQueries): v4 api to take an object as input

- src/core/queryObserver.ts
- src/reactjs/tests/useQuery.test.tsx
- src/reactjs/useBaseQuery.ts
adding "error" to the list of tracked properties will result in us _only_ tracking error if we want to track all properties implicitly by _not_ observing any properties (because we check for trackedProps.size). Moving the adding of "error" to _after_ the size check fixes this
> fix(queryObserver): defer tracking of error prop when useErrorBoundary is on

- src/core/queryObserver.ts
- src/react/tests/useQuery.test.tsx
closes #3095 
we compute the result optimistically, and then one more time when calling setOptions. Both times run the select function because only setOptions will update the previous result and previous options. storing the "previous" selectFn separately on the observer whenever it was invoked (independent of the fact from where it was called) side-steps the issue
> fix(queryObserver): make sure that memoized select function only runs once per input

- src/core/query.ts
- src/react/tests/useQuery.test.tsx
to be aligned with the types, as `loading` cannot have an `error` set.
closes #3090
> fix(query): set error to null when going to loading state

- src/devtools/styledComponents.ts
fixes #3114
add explicit color inherit on `Code` styled component to avoid default color set via external stylesheets.
> fix(devtools): code  color is not inherited from panel color (#3114)

- src/react/types.ts
Using core types, instead of custom ones for `useMutation`.
One question though. Why `variables` and `_defaulted` exist for `MutationObserver` but not for `useMutation`?
@TkDodo
> fix(types): use core types in useMutation instead of redefining them

- src/core/queryObserver.ts
- src/react/tests/useQuery.test.tsx
not all runs to createResult are saved on `this.currentResult` (optimistically created updates do not - we just create the result again later). With the fix from #3098, we made sure that memoized select does not run again in those cases by storing every run. However, that now means that we cannot rely on `prevResult.data` because it might still contain outdated data.
The solution is to store a pair of previous selectFn + data and return the exact data that was computed from the previous select fn if we get the exact same function passed
closes #3139
> fix(queryObserver): memoized select functions should not return outdated values

- examples/playground/src/index.js
Just something I found when playing around in the development enviroment of this project. No biggie - but still :).
> refactor(fetchTodoById): use tripple equal instead of double equal

- docs/src/manifests/manifest.json
- docs/src/pages/examples/react-native.mdx
New React Native example (Expo snack). 
Basic React Native App with List / Details screens with some useful hooks.
> docs(examples): add react native expo snack example

- docs/src/pages/reference/useMutation.md
This makes the default value more apparent and adds `retry` and `retryDelay` to the example code.
I had to read through [the code](https://github.com/tannerlinsley/react-query/blob/aec640a5952f3787fc0efd0f39d7b51431110d43/src/core/mutation.ts#L248) to figure out what the default is.
Thanks for the AWESOME library!
> docs(useMutation): clarify retry default value

- examples/load-more-infinite-scroll/pages/index.js
Fixes [issue](https://github.com/tannerlinsley/react-query/issues/3171).
Scope: **[Load More / Infinite Scroll example]**
The top button contained wrong text due to wrong variables used in the corresponding condition that determines its text. 
This PR fixes the use of the wrong variables.
> fix(examples/load-more-infinite-scroll): fix wrong condtion

- src/core/queryObserver.ts
- src/react/tests/useQuery.test.tsx
by making sure to memoize the structurally shared version of data rather than the raw one
closes #3181
> fix(queryObserver): fix data stability

- docs/src/pages/plugins/persistQueryClient.md
- docs/src/pages/reference/hydration.md
- src/persistQueryClient/index.ts
Per discussion #3129 
1. Break down `persistQueryClient` into its various tasks
2. Return an unsubscribe callback when subscribing a persister
3. Update docs
holding on the other updates to keep it more straightforward for now.
> Break down `persistQueryClient`

- examples/react-native/.gitignore
- examples/react-native/src/lib/api.ts
This fix the missing `src/lib` folder.
> fix(examples): react-native: update .gitignore to exclude lib folder

- src/core/queryClient.ts
- src/core/types.ts
Export QueryClientConfig interface, so it can be easily reused in wrapper libraries
> fix: export QueryClientConfig interface

- src/react/tests/useQueries.test.tsx
- src/react/useQueries.ts
Include `TQueryKey` in the type inference for `useQueries`.
fixes [#3208](https://github.com/tannerlinsley/react-query/issues/3208)
> fix(useQueries): fix types with strongly typed QueryFunction + QueryKey

- docs/src/pages/guides/ssr.md
This adds a small section for a caveat about hydration when using some specific feature/configuration of Next.js.
See initial RQ discussion: https://github.com/tannerlinsley/react-query/discussions/3192
See Next.js issue: https://github.com/vercel/next.js/issues/33028#issuecomment-1012126770
---
I'm not sure if we should additionally reference the Next.js issue for this topic in the RQ docs, but my hopes are not high that the issue will be fixed "this time", as it is not really a bug per se, so I didn't here.
> docs(ssr): Hydration caveat for Next.js rewrites

- src/core/notifyManager.ts
- src/core/tests/notifyManager.test.tsx
incrementing and decrementing transactions need to happen in an atomic operation, no matter what happens in between; if we increment, but never decrement, we will get to a state where transactions can never become zero - we're basically "leaking" an open transaction. This leads to no observers being informed ever again because we think we still have an open transaction
this can be fixed by using try/finally to always decrement the transactions
closes #3215
> fix(core): make sure batching finishes if exception is thrown

- docs/src/pages/guides/caching.md
PR rebased on alpha as requested in [comment](https://github.com/tannerlinsley/react-query/pull/3102#issuecomment-1000151067).
The example contains at least one inacurate statement,
> It will then cache the data using `'todos'` and `fetchTodos` as the unique identifiers for that cache.
and could benefit from more precise language.
> docs: clarify caching behavior

- docs/src/pages/reference/useIsMutating.md
- src/react/useIsMutating.ts
Fix TypeScript annotations and update the useIsMutating doc:
use MutationKey instead of QueryKey
> fix(useIsMutating): use MutationKey instead of QueryKey

- src/core/query.ts
- src/core/queryClient.ts
- src/core/tests/queryClient.test.tsx
- src/devtools/devtools.tsx
- src/reactjs/tests/useQuery.test.tsx
with refetchQueries or invalidateQueries + refetchType "inactive"
disabled queries (=queries that have observers which are all enabled:false) are matched as "inactive"; this is okay when searching for them via findAll or for removeQueries, but the docs clearly state that refetchQueries / invalidateQueries do not refetch disabled queries, and that the only way to refetch them is via refetch returned from useQuery; this is important when using enabled to signal that some dependencies are not yet ready
some tests needed to be adapted because we used disabled observer + refetchQueries a lot. The easiest way to emulate the observers we wanted here was mostly with initialData + staleTime, and to get a real inactive query, we just need to subscribe + unsubscribe immediately
closes #3202
> fix(core): do not refetch disabled queries

- examples/load-more-infinite-scroll/pages/index.js
On the first render, `hasNextPage` is `undefined`, but converted to `true` by the default value.
For intersection observer to trigger correctly without clicking more button, `hasNextPage` needs type casting.
> Fix to infinite scroll without clicking more button

- docs/src/pages/guides/query-cancellation.md
[graphql-request v4.0](https://www.npmjs.com/package/graphql-request#cancellation) now supports setting an AbortSignal per request.
A new Query cancellation example has been added.
Related PR https://github.com/prisma-labs/graphql-request/pull/303
> docs(cancellation): add graphql request v4 example

- src/react/tests/useQueries.test.tsx
- src/react/useQueries.ts
Relates to discussion https://github.com/tannerlinsley/react-query/discussions/3242, and very similar to PR https://github.com/tannerlinsley/react-query/pull/3214 - this update ensures we also pass down the QueryKey type when working with regular array parameters (i.e. not a variadic tuple), making it easier to create wrappers around `useQueries`.
> fix(types): useQueries to also handle array-params with typed QueryKey

- docs/src/pages/reference/QueryClient.md
- Makes setQueriesData more searchable by adding keyword `partial` there
- Change mention of fuzzily matching to partial matching since fuzzy matching is more arbitrary algorithm
- Mention setQueriesData in setQueryData to avoid confusion of behaviours
The purpose of this change is to make setQueriesData a bit more searchable from the docs to avoid confusion like this: https://github.com/tannerlinsley/react-query/discussions/3239
> docs(setQueriesData): Make setQueriesData more searchable

- docs/src/pages/guides/migrating-to-react-query-4.md
- docs/src/pages/reference/QueryClient.md
- docs/src/pages/reference/useQuery.md
- src/core/query.ts
- src/core/queryClient.ts
- src/core/tests/query.test.tsx
- src/core/tests/queryClient.test.tsx
- src/core/tests/queryObserver.test.tsx
- src/core/types.ts
- src/reactjs/tests/ssr.test.tsx
- src/reactjs/tests/suspense.test.tsx
- src/reactjs/tests/useQueries.test.tsx
- src/reactjs/tests/useQuery.test.tsx
closes #2925 
@TkDodo here is the wildly simpler PR we have all been hoping for :-)
> Bail out if query data undefined

- docs/src/pages/plugins/createWebStoragePersister.md
Add an example on how to `compress`/`decompress` data from local storage in case you need to cache large payloads.
Context: https://github.com/tannerlinsley/react-query/pull/2864#issuecomment-1034604428
> Document compression use case for `createWebStoragePersister`

- docs/src/pages/reference/useQuery.md
Was missing the placeholderData field on the `useQuery` options signature... but its listed in detail on the latter part of the page.
> Update useQuery.md doc

- src/devtools/styledComponents.ts
fix(devtools): Prevent `code` element's backround from being overwritten. This can happen when some global styles are imported in an app (e.g. bootstrap).
> Devtools: add code element's backround

- src/createAsyncStoragePersister/asyncThrottle.ts
- src/createAsyncStoragePersister/index.ts
- src/createAsyncStoragePersister/tests/asyncThrottle.test.ts
closes #3331
fix(createAsyncStoragePersister): persistClient not respect throttleTime and not persisted final state queryClient (#3331).
And add unit test for asyncThrottle.
> fix(createAsyncStoragePersister): persistClient not respect throttleTime and not persisted final state queryClient (#3331)

- examples/simple/src/index.js
Hey there,
I recently stumpled across a [misunderstanding](https://github.com/tannerlinsley/react-query/issues/2258#issuecomment-1034707667) of the library and the [referenced simple example](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/simple).
Since the example contains an error handling with respect to the UI, it should also correctly recognize occurring errors. As mentioned in the docs, [fetch and other clients do not throw by default](https://react-query.tanstack.com/guides/query-functions#usage-with-fetch-and-other-clients-that-do-not-throw-by-default) an error - so I added the error handling to the example within the result handler.
> docs: Extend simple example to handle failed request

- src/devtools/Explorer.tsx
- src/devtools/tests/Explorer.test.tsx
Add types to Explorer component with as minimal functional changes as
possible while still getting type safety
#2742
> refactor(devtools): add types to Explorer

- src/react/tests/useIsFetching.test.tsx
- src/react/useIsFetching.ts
fixes #3437
if a fetch happens in the same render cycle as useIsFetching is mounting, but it is mounted after the query, what happens is that:
- the initial state of `isFetching` is `0` because the effect to fetch the query hasn't started yet
- the query effect runs before the isFetching effect, which means we miss the event, thus the next event we get from the subscription gives us 0 again
so we need to check for isFetching in the effect that runs to set up the subscription as well. This catches fetches that basically started in the same effect cycle, but before "our" effect ran
> fix(useIsFetching): account for fetches happening in the same render cycle

- src/devtools/Explorer.tsx
- src/devtools/tests/Explorer.test.tsx
- src/devtools/utils.ts
closes #3082 
I detected the issue `TypeError: Do not know how to serialize a BigInt` was caused by `JSON.stringify` in the devtools explorer. I created a separate function so I could also write a test. 
This is my first contribution here, so please, let me know how I can improve this implementation. 😄
> fix(devtools): serialize bigint types

- src/devtools/Explorer.tsx
Added missing key prop to map fns on `Explorer.tsx`
Used `entry.label` as key, which assumes that label is unique
Discovered after converting Explorer component to typescript [here](https://github.com/tannerlinsley/react-query/pull/2949#issuecomment-1078772381)
A way to avoid this issue in the future could be to enable [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react)'s [react/jsx-key](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md) rule
> fix(devtools): add keys to mapped entries for Explorer

- .eslintrc
Rule is set to error.
option checkFragmentShorthand option set to true,  meaning the rule is used for shorthand fragment syntax too.
option will default to true next major eslint-plugin-react version
See rule docs [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md)
> chore(eslint): Add react/jsx-key lint rule

- examples/suspense/package.json
- examples/suspense/src/components/Button.js
- examples/suspense/src/index.js
This is the possible fix for #3453
> docs: fix suspense example

- docs/src/pages/react-native.md
It was not obvious what `useRefreshOnFocus` hook does at first glance. This PR refactors it to use a `firstTimeRef` ref to make it clear that we are skipping the first time `useFocusEffect` is called.
> docs: Improve readability of `useRefreshOnFocus`

- README.md
add a link in README.md pointing to the v4 beta doc
> docs: add a link to the v4 beta doc

- src/core/tests/query.test.tsx
- src/core/types.ts
- src/persistQueryClient/tests/PersistQueryClientProvider.test.tsx
- src/reactjs/tests/useQueries.test.tsx
- src/reactjs/tests/useQuery.test.tsx
fixes issue #3483 
This new helper `QueryFunctionData` was introduced in the latest branch:
```typescript
type QueryFunctionData<T> = T extends undefined ? never : T
type QueryFunction<
T = unknown,
TQueryKey extends QueryKey = QueryKey
> = (
context: QueryFunctionContext<TQueryKey>
) => QueryFunctionData<T> | Promise<QueryFunctionData<T>>
```
Looks like when a conditional expression is duplicated like this in a union, it's not able to pass along any `infer` logic correctly.
[(TS Playground link with a simplified example - not restricted to promises though... you can replace `Promise<X>` with `Array<X>` for the same effect)](https://www.typescriptlang.org/play?#code/C4TwDgpgBAigrhATiAYnAdgY2ASwPboAiAhsMQDwAqAfFALxSVQQAewE6AJgM5QacQAZjnQROUAPxRRANyRQAXIwBQy0JCgB5OO0QBVdPnRVaDeElQZsRkmRNQAPl …
> fix(types): fix promise inference in useQueries

- src/devtools/devtools.tsx
- src/devtools/styledComponents.ts
> fix(devtools): QueryKey height

- src/devtools/devtools.tsx
- src/devtools/tests/devtools.test.tsx
* pass nonce to devtools
* __webpack__nonce__
* set style scoped 
fix #3495
> nonce for devtools style

- src/devtools/Explorer.tsx
Adds `ExpandButton` component for styling the expand button correctly (removes browser default styles)
Before:
After:
closes #3538
> fix(devtools): Fix expand button styling

- src/devtools/devtools.tsx
- src/reactjs/useBaseQuery.ts
- src/reactjs/useIsFetching.ts
- src/reactjs/useIsMutating.ts
- src/reactjs/useMutation.ts
- src/reactjs/useQueries.ts
https://github.com/tannerlinsley/react-query/pull/3521#issuecomment-1109810824
> Use fully-specified path to import use-sync-external-store/shim

- docs/src/pages/react-native.md
- [react-native-appstate-hook](https://github.com/amrlabib/react-native-appstate-hook) is not updated regularly. It currently has a `peerDependencies` problem for React 17 and 18.
- It actually does the same thing with `AppState.addEventListener('change', ...)` when you only specify `onChange` property on `useAppState()`.
> docs: Remove react-native-appstate-hook

- src/devtools/devtools.tsx
- src/devtools/tests/devtools.test.tsx
Added button wrapper on react query logo which onClick closes devtools window
Tested locally
Closes #3067
> feat(devtools): update react query logo to close devtools

- src/core/query.ts
- src/core/queryClient.ts
- src/core/queryObserver.ts
- src/core/tests/queryClient.test.tsx
queries can be fetching _while_ we are making a manual update are still fetching, so we have to set fields that affect the fetch conditionally (fetchStatus, fetchFailureCount)
fixes #3594
> fix(query): updating with setQueryData should not affect fetchStatus

- src/core/queryClient.ts
- src/core/tests/queryClient.test.tsx
the only runtime tests we had didn't use the previous value, so the generic defaults to unknown; the TS error becomes apparent when providing a generic to setQueryData
> fix(queryClient): make sure that setQueryData can return undefined from the updater function on type level

- src/core/mutation.ts
- src/core/types.ts
Fixes   https://github.com/tannerlinsley/react-query/issues/3652
changes context to optional in onSuccess callback
> fix(*): change types

- src/reactjs/useSyncExternalStore.native.ts
- src/reactjs/useSyncExternalStore.ts
> fix: useSyncExternalStore re-export

- docs/src/pages/plugins/persistQueryClient.md
- src/createAsyncStoragePersister/index.ts
- src/createWebStoragePersister/index.ts
- src/persistQueryClient/persist.ts
because we can now pass in undefined for persisters during SSR, and the persisters themselves are not window related anymore, as we don't use window.localStorage directly
> fix(persist): remove environment check

- src/core/tests/query.test.tsx
- src/core/types.ts
- src/reactjs/tests/useQueries.test.tsx
- src/reactjs/tests/useQuery.test.tsx
- src/reactjs/useQueries.ts
discussed in #3541 
trying to enforce not-void + not-undefined on the queryFn return type is creating pockets of complexity / unexpected typing behaviour, as TS is trying to both enforce and infer too many things at the same time.
removing for now, and adding some additional tests to check for the pieces that were clashing with the non-void constraint
- able to use fetch() in queryFn with `Promise<any>` return type
- able to use wrapped queries with custom fetcher functions typed to return `TQueryFnData`
> fix(types): remove non-void constraint from queryFn result

- src/core/infiniteQueryBehavior.ts
- src/core/infiniteQueryObserver.ts
Currently i face with this problem that i defined a `InfiniteQueryObserverOptions` that contains `QueryKey`. and then i pass it into `InfiniteQueryObserver`. but unfortunately its not compatible with options of  `InfiniteQueryObserver`'s constructor
> feat: make InfiniteQueryObserver's type more robust

- src/core/tests/utils.test.tsx
- src/core/utils.ts
It turns out that the `replaceDeepEqual` function wasn't returning the intended value for objects that are non-plain arrays.
E.g.
```tsx
const prev = Object.assign([1, 2], { a: { b: 'b' }, c: 'c' })
const next = Object.assign([1, 2], { a: { b: 'b' }, c: 'c' })
replaceDeepEqual(prev, next) // result: [1, 2]
```
This data structure is used in libraries such as [ethers](https://docs.ethers.io/v5/) and their [contract `Result` value](https://docs.ethers.io/v5/api/utils/abi/interface/#Result).
I'm not sure if we should perform structural sharing on these values as they are not really "JSON-compatible" values as mentioned in the [docs](https://react-query.tanstack.com/guides/important-defaults), so I added a change which just checks if the given array is a "plain array", and if it is not, it …
> fix: `replaceDeepEqual` special case for non-plain arrays

- src/createWebStoragePersister/index.ts
Currently RQ has `createWebStoragePersistor` and `createAsyncStoragePersistor` which assumes that non-web platforms can have async storages only, which is not true. React Native has performant synchronous MMKV adapters support, which can't be used with RQ 3 right now directly because of interface incompatibility and `window` check(already fixed in v4).
Related discussion: https://github.com/tannerlinsley/react-query/discussions/3667
Introduce own `Storage` interface to make possible using `createWebStoragePersistor` in React Native without TS errors.
> fix(persist): introduce in-house synchronous Storage interface

- docs/plugins/persistQueryClient.md
Update subtitle `PeristQueryClientProvider` to `PersistQueryClientProvider`.
> docs: fix the typo in persistQueryClient.md

- docs/react-native.md
- docs/reference/onlineManager.md
For react-native + typescript users, we changed a very minor phrase.
to
```
onlineManager.setEventListener((setOnline) => {
return NetInfo.addEventListener((state) => {
setOnline(!!state.isConnected);
});
});
```
> docs: Update for typescript

- docs/guides/ssr.md
> docs: fix typo in ssr.md

- src/core/query.ts
- src/core/queryObserver.ts
[`clearInterval` and `clearTimeout` are expensive to run](https://jsbench.me/mjl4ybxzwe/1) and should only be ran if there is for sure an id to be cleared. This PR adds the checks in as discussed in #3756
> fix(core): added in timer and interval id checks before clearing

- package-lock.json
- packages/react-query-persist-client/src/__tests__/PersistQueryClientProvider.test.tsx
- packages/react-query/src/__tests__/tsconfig.json
- packages/react-query/src/__tests__/useQuery.test.tsx
- packages/react-query/src/__tests__/useQuery.types.test.tsx
- packages/react-query/src/types.ts
- packages/react-query/src/useQuery.ts
> Added a proof of concept for initialData making TData never undefined

- packages/react-query-devtools/src/__tests__/devtools.test.tsx
- packages/react-query-devtools/src/devtools.tsx
Fix for: [#3639: DevTools doesn't remember the sort function](https://github.com/TanStack/query/issues/3639)
[This effect](https://github.com/TanStack/query/blob/19d755cb875056e34ac09d2a7aedeaf05632ebf3/src/devtools/devtools.tsx#L445-L449) is causing the problem. Good news is that it's also completely unneeded as it's doubling what's already done [via useLocalStorage](https://github.com/TanStack/query/blob/19d755cb875056e34ac09d2a7aedeaf05632ebf3/src/devtools/devtools.tsx#L431-L434). And if the runs after (which it usually does), it disregards the value that's read by `useLocalStorage` hook - which is exactly what causes the bug.
This is easily fixable by simply removing the effect.
> fix(devtools): make sure that sort function is properly read from localStorage

- packages/react-query/package.json
There was a typo in react-query `package.json` that pointed to query-core types instead of react-query types. Tagging @tannerlinsley : I've seen your releases today and this bug was included in the v4.
> Fix react-query package types import path

- package.json
- packages/react-query-devtools/package.json
- rollup.config.ts
Just noticed that someone also made a PR #3883 . But we should export the noop version.
> fix(react-query-devtools): support cjs in noop build

- docs/src/pages/examples/auto-refetching.mdx
- docs/src/pages/examples/basic-graphql-request.mdx
- docs/src/pages/examples/basic.mdx
- docs/src/pages/examples/custom-hooks.mdx
- docs/src/pages/examples/default-query-function.mdx
- docs/src/pages/examples/focus-refetching.mdx
- docs/src/pages/examples/load-more-infinite-scroll.mdx
- docs/src/pages/examples/nextjs.mdx
- docs/src/pages/examples/optimistic-updates-typescript.mdx
- docs/src/pages/examples/optimistic-updates.mdx
- docs/src/pages/examples/pagination.mdx
- docs/src/pages/examples/playground.mdx
- docs/src/pages/examples/prefetching.mdx
- docs/src/pages/examples/react-native.mdx
- docs/src/pages/examples/rick-morty.mdx
- docs/src/pages/examples/simple.mdx
- docs/src/pages/examples/star-wars.mdx
- docs/src/pages/examples/suspense.mdx
- docs/src/pages/guides/suspense.md
- docs/src/pages/index.js
- docs/src/pages/overview.md
make examples point to v3 instead of main
> docs: make examples point to v3 instead of main

- packages/react-query/src/useQuery.ts
On `react-query` v3, users were allowed to pass custom options to `useQuery` and `useInfiniteQuery` without needing of passing `initialData`.
```ts
function useQueryPosts(isAdmin, options?: UseQueryOptions<number, Error, number>) {
return useQuery<number, Error, number>(["posts"], () => 10, {
enabled: isAdmin,
...options
});
}
```
With the launch of `react-query` v4, this is not possible anymore as all the overload functions of `useQuery` forces the user to pass `initialData`:
```ts
function useQueryPosts(isAdmin, options?: UseQueryOptions<number, Error, number>) {
return useQuery<number, Error, number>(["posts"], () => 10, {
enabled: isAdmin,
initialData: () => null,
...options
});
}
```
So, this Pull Request adds a new overload function which allow users to pass options without forcing …
> fix(react-query): allow passing options to useQuery without initialData

- docs/overview.md
- Fixed `Open in CodeSandbox` link in [overview](https://react-query-v3.tanstack.com/overview#enough-talk-show-me-some-code-already) page.
> docs: fix codesandbox link of overview example code

- docs/guides/suspense.md
- Fixed `Suspense Example` codesandbox link. 
Resolves #3895
> docs: fix `Suspense Example` codesandbox link

- docs/guides/disabling-queries.md
```diff
- declartive
+ declarative
```
> docs(disabling-queries): fix typo of missing 'a' in declarative

- docs/adapters/react-query.md
Plenty examples that aren't working - I'll work my way through and get them sorted where I see them.
> Missing QueryClientProvider import in example.

- docs/installation.md
Updated the documentation link from the old react-query to the new @tanstack/react-query
Old:
```md
<script src="https://unpkg.com/react-query/dist/react-query.production.min.js"></script>
```
New:
```md
<script src="https://unpkg.com/@tanstack/react-query@4/build/umd/index.production.js"></script>
```
In installation.md
Fixes #3852
> docs: :memo: Update documentation to point to the new CDN link

- packages/query-core/src/queryClient.ts
(╯°□°)╯︵ ┻━┻
Typescript doesn't like it when we are checking if we're on production twice. First we check at Line 566 `if (process.env.NODE_ENV !== 'production') {` and then again @ line 573. 
```Failed to compile.
../../node_modules/@tanstack/query-core/src/queryClient.ts:573:13
Type error: This condition will always return 'true' since the types '"development" | "test"' and '"production"' have no overlap.
```
Simple fix 🥇
> Already checked in line 566.

- docs/reference/useQuery.md
Clarify that the `select` function passed to `useQuery` does not affect what gets cached; it only affects what gets returned to the consumer.
> docs(useQuery): clarify behaviour of useQuery "select" with regard to caching

- docs/reference/QueryCache.md
The docs were showing that to fetch data from the query cache, you pass a string into the `find` and `findAll` method. That is incorrect as in react query v4, keys are arrays only.
> Fixed incorrect syntax in QueryCache docs

- docs/guides/ssr.md
When using the example code I got the following error in the terminal:
```
As of v4, queryKey needs to be an Array. If you are using a string like 'repoData', please change it to an Array, e.g. ['repoData']
```
That makes me think this code example in particular got outdated when v4 was released.
> Update code example to use v4 convention

- .github/workflows/ci.yml
Allows to manually dispatch publish workflow, while also giving ability to override `tag`.
This is useful for `minor` or `patch` pre-releases, when we want to first test some functionality before releasing it as a regular version.
1. merge changes that you want to test to `beta` branch (ideally should be in sync with `main`)
2. trigger workflow manually from the [actions](https://github.com/TanStack/query/actions) tab overriding `tag` to a version higher with suffix. Ex `v4.0.11-beta.0` and branch to `beta` (available only to maintainers)
> chore: allow to dispatch publish with tag override

- packages/query-async-storage-persister/package.json
- packages/query-broadcast-client-experimental/package.json
- packages/query-sync-storage-persister/package.json
- packages/react-query-devtools/package.json
- packages/react-query-persist-client/package.json
- packages/react-query/package.json
- rollup.config.ts
This should allow for automatic deps install on sub packages. Currently when you try to install one of those, you might get an error about missing imports.
@TkDodo This should go to beta for pre-release
> fix: subpackage dependencies

- docs/guides/query-functions.md
Removes `.md` from the end of links.
> docs(query-functions.md): fix broken links

- docs/guides/testing.md
The testing page is missing some language metadata, so TS is incorrectly showing up as Bash.
> docs: add missing languages

- packages/query-core/src/mutationCache.ts
- packages/query-core/src/mutationObserver.ts
- packages/query-core/src/queryCache.ts
- packages/query-core/src/queryObserver.ts
- packages/query-core/src/tests/queryObserver.test.tsx
- packages/react-query/src/__tests__/useQuery.test.tsx
https://github.com/TanStack/query/issues/2741
> feat: notify about observer options change

- examples/react/optimistic-updates-typescript/package.json
using `main` property in package.json we can point CodeSandbox to a file we want it to open on load in the embedded version
> docs(examples): fix codesandbox of optimistic updates typescript example

- packages/query-core/src/types.ts
- packages/react-query/src/types.ts
Since there is always cache data, the `isLoading` of type `DefinedUseQueryResult`  should be false. Besides, the `Omit` is not required.
> feat(react-query): isLoading of type DefinedUseQueryResult is always false

- docs/guides/important-defaults.md
- docs/reference/useQuery.md
- packages/query-core/src/tests/queryClient.test.tsx
- packages/query-core/src/types.ts
- packages/query-core/src/utils.ts
As discussed [here](https://github.com/TanStack/query/discussions/3715) and [here](https://github.com/TanStack/query/discussions/3690), this allows the provision of a function as the `structuralSharing` value, which effectively acts as a replacement for `replaceEqualDeep`. This way, consumers can still achieve the performance benefits of retained references even when cache data contains non-serializable values.
> feat: allow custom merge function for structuralSharing

- packages/react-query-devtools/cjs.fallback.js
- packages/react-query-devtools/package.json
@TkDodo This is a potential fix for bundlers that does not support `development` conditional in `exports`
This will work only with `cjs`.
For `esm` i do not see any easy fix.
> fix: cjs devtools fallback

- packages/query-async-storage-persister/package.json
- packages/query-broadcast-client-experimental/package.json
- packages/query-core/package.json
- packages/query-sync-storage-persister/package.json
- packages/react-query-devtools/package.json
- packages/react-query-persist-client/package.json
- packages/react-query/package.json
- rollup.config.ts
@TkDodo
This should fix:
- some bundlers picking up `browser` entry in package.json (`umd` build instead of `cjs` or `esm`)
- unusual size of `react-query`, due to missing rollup global definition for react-dom
This won't fix:
- bundlers that support `exports`, but does not support `development/production` conditionals (https://webpack.js.org/guides/package-exports/#optimizations)
This might be the case as those conditionals were mostly proposed by `webpack`.
We could potentially overcome this by linking `exports/./default/default` not to `noop.js`, but to intermediate `js` file that conditionally require devtools based on `NODE_ENV`, like in the v3.
This however i would like to test separately.
Previous beta release also have a side effect that `react-query` UMD build does not contain …
> fix: remove browser entry, fix umd size

- docs/reference/useQuery.md
The current definition is incorrect, since `status` might be `loading` even if `isFetching` is false (e.g. when query is disabled)
> Update the docs for `loading` state of `status` field

- docs/plugins/createAsyncStoragePersister.md
Add new documentation guides about using `PersistQueryClientProvider` instead of using `persistQueryClient`.
> Add new guides for React Native createAsyncStoragePersister

- docs/src/pages/examples/auto-refetching.mdx
- docs/src/pages/examples/basic-graphql-request.mdx
- docs/src/pages/examples/basic.mdx
- docs/src/pages/examples/custom-hooks.mdx
- docs/src/pages/examples/default-query-function.mdx
- docs/src/pages/examples/focus-refetching.mdx
- docs/src/pages/examples/load-more-infinite-scroll.mdx
- docs/src/pages/examples/nextjs.mdx
- docs/src/pages/examples/optimistic-updates-typescript.mdx
- docs/src/pages/examples/optimistic-updates.mdx
- docs/src/pages/examples/pagination.mdx
- docs/src/pages/examples/playground.mdx
- docs/src/pages/examples/prefetching.mdx
- docs/src/pages/examples/react-native.mdx
- docs/src/pages/examples/rick-morty.mdx
- docs/src/pages/examples/simple.mdx
- docs/src/pages/examples/star-wars.mdx
- docs/src/pages/examples/suspense.mdx
- docs/src/pages/guides/suspense.md
- docs/src/pages/index.js
- docs/src/pages/overview.md
I noticed this issue myself while looking through the docs last week:
https://github.com/TanStack/query/issues/4054
This PR resolves issues with the example links, which are currently linking to the `main` branch when they should be linking to the `v3` branch.
> docs: Updating v3 example links

- package-lock.json
- packages/react-query-devtools/src/devtools.tsx
- packages/react-query-devtools/src/screenreader.tsx
> Recreated from https://github.com/TanStack/query/pull/3854
While testing our local site with our [accessibility testing tool](https://github.com/bbc/bbc-a11y), we recieved the following error:
```
✗ Main Dashboard
* Forms: Labelling form controls: Fields must have labels or titles
- Button has no text: //div[@id='ReactQueryDevtoolsPanel']/div[2]/div[1]/button
- Button has no text: //main[@id='main-content']/aside/button
```
The issue is that not all screenreaders support aria values, and so this test is checking that buttons at least have a text value within them, which can be visibility hidden if so required.
To resolve this, this PR adds visually hidden text to the button.
> fix: Adding screenreader text to the DevTools open icon

- packages/react-query-devtools/src/devtools.tsx
This PR comes after this recent PR for adding screenreader text to the open/close button:
https://github.com/TanStack/query/pull/4063
In this PR, I'm adding screenreader text to the offline mock button, which I must not have noticed in my previous PR, and a new version of our a11y testing tool seems to pick it up, when our old tool did not (sorry about that).
> fix: Adding screenreader text to the dev tools offline mock button

- packages/react-query-devtools/package.json
@TkDodo For this to work, you need to have a proper TS version (>= 4.7) and chnage `moduleResolution` to `NodeNext`
> fix: reintroduce production export

- docs/guides/migrating-to-react-query-4.md
I suggest adding backslashes to the codemod commands which makes them easier to copy-paste.
I was having trouble executing the commands before I realized my shell was ignoring half of the command because of the newline characters.
Hoping this change could be helpful to others following the migration guide.
> docs(migration-guide): multiline codemod commands

- docs/adapters/react-query.md
- docs/guides/background-fetching-indicators.md
- docs/guides/query-cancellation.md
Keeping consistency in which query keys need to be an array.
> docs: query keys consistency

- docs/reference/useMutation.md
- packages/query-core/src/types.ts
Hey, in [`useMutation` options docs](https://tanstack.com/query/v4/docs/reference/useMutation) description for `onSuccess`, `onError`  and  `onSettled` says 
> If a promise is returned, it will be awaited and resolved before proceeding
So in this example, the mutation will wait for the promise in `onSuccess` to be resolved before changing mutation status and data
```tsx
{
const { data, isLoading } = useMutation(
() => {
/**Some async stuff */
},
{
onSuccess: () => {
/** Will wait to be resolved before changing the mutation status */
return delay(5000);
},
}
);
}
```
It also says in `mutate` options 
> Remaining options extend the same options described above in the useMutation hook.
But if used like this the promise will not be awaited
```tsx
const { data, isLoading, mutate } = …
```
> Docs: update mutate options description

- docs/community/lukemorales-query-key-factory.md
- docs/config.json
- docs/guides/query-keys.md
Hey Tanner and TkDodo, here's the PR adding the Query Key Factory package to the Community section on Docs.
I tried to make the examples as less prone to changes as possible, as well as match the examples already provided in the docs (using todos, same patterns, code style etc).
Please let me know if you'd like for me to make any changes.
> docs(community): add query key factory community contribution

- examples/react/rick-morty/src/Character.jsx
- examples/react/rick-morty/src/Episode.jsx
- examples/react/star-wars/src/Character.jsx
- examples/react/star-wars/src/Film.jsx
This small PR rewrites some query keys from specific example apps to match the recommended standard in the docs.
There has not been a single mention of a query key that is made of a string literal for quite a while, so probably these few cases in the example apps are from old implementations and make sense to update them to the way the docs recommend shaping the query keys
> refactor(examples): rewrite query keys to recommended standard

- packages/query-async-storage-persister/package.json
- packages/query-broadcast-client-experimental/package.json
- packages/query-core/package.json
- packages/query-sync-storage-persister/package.json
- packages/react-query-devtools/package.json
- packages/react-query-persist-client/package.json
- packages/react-query/package.json
- rollup.config.ts
@TkDodo Quick check:
- scripts v4
- scripts 5
Both seems to work
Could you please check with react-native 🙏 
Fixes: https://github.com/TanStack/query/issues/4155
> fix: serve esm.js for webpack 4

- packages/react-query-persist-client/package.json
For yarn 3 pnp, having react-query as a normal dependencies causes it to be bundled multiple times. The query client set in react-query-persist-client is not visible for the normal useQuery imports from react-query. Setting react-query as a peerDependency instead fixes this issue.
Fixes #4161
> fix(react-query-persist-client): Make dependencies to peerDependencies

- packages/react-query/src/useSyncExternalStore.native.ts
- packages/react-query/src/useSyncExternalStore.ts
- rollup.config.ts
@TkDodo
This is a potential fix following the same pattern as other `.native` files.
Unfortunately i do not have a good way to test it out. So people that have a reliable native setup should say if it works as intended.
fixes #4154
> fix: react native uSES

- docs/guides/window-focus-refetching.md
- docs/react-native.md
As stated in the issue raised here: https://github.com/TanStack/query/issues/4135. There is an inconsistency with the instructions provided on how to refetch on app focus.
The change contained in this PR addresses the inconsistency and updates the documentation to provide a single way to implement this functionality.
> docs: update react native app focus instructions

- docs/guides/migrating-to-react-query-4.md
This adds a statement to uninstall `react-query` and install `@tanstack/react-query` to the `v3` to `v4` migration guide.
> Add un-/install statement to `v3` to `v4` migration guide

- docs/community/liaoliao666-react-query-kit.md
this PR is for adding `react-query-kit` package to the docs.
I recently wrote this package to get rid of the tedious management of `queryKey` and make `queryKey` strongly related to `queryFn`.
Maybe some people would like to use it.
> docs: add react query kit community contribution

- packages/query-core/src/query.ts
- packages/query-core/src/tests/query.test.tsx
@TkDodo As per our chat on Discord, I made a small change in the error that throws in `createRetryer`'s `onSuccess` callback if the fetched data turns out to be `undefined`. The error now includes the affected `queryKey` - I have confirmed this in my personal project and successfully resolved the issue I had that way.
Open to any suggestions.
Thanks!
> feat(query-core): log queryKey in createRetryer

- packages/react-query-devtools/src/Explorer.tsx
- packages/react-query-devtools/src/__tests__/Explorer.test.tsx
Resolves: https://github.com/TanStack/query/issues/3681
Original PR (https://github.com/TanStack/query/pull/3687) has been abandoned. Here I just copied the relevant changes.
> fix(devtools): prevent devtools explorer from collapsing when data is being fetched

- docs/guides/migrating-to-react-query-3.md
The v3 migration docs say that `usePaginatedQuery` was only deprecated, but it was actually removed entirely.
> `usePaginatedQuery` was removed in v3, not just deprecated

- packages/react-query-devtools/src/devtools.tsx
Add dir="ltr" to devtools panel beacause the devtools appear inverted when direction of a parent is rtl
Fixes #4282
> fix(devTools styles): add direction style

- docs/devtools.md
- packages/react-query-devtools/src/__tests__/devtools.test.tsx
- packages/react-query-devtools/src/devtools.tsx
- packages/react-query-devtools/src/utils.ts
closes https://github.com/TanStack/query/issues/2994
Added the option to move dev tools to one of these sides `left`,  `right`, `top`, and `bottom` and refactored the code to accommodate the new capability
@TkDodo  sorry the previous PR got closed somehow when I updated my fork, I fixed your comments from the previous PR
> feat(devtools): Add move devtools select menu

- packages/solid-query/src/__tests__/createQuery.test.tsx
- packages/solid-query/src/__tests__/suspense.test.tsx
- packages/solid-query/src/createBaseQuery.ts
#4288 uncovered a bug in createBaseQuery.tsx, this PR aims to solve this. 
`createBaseQuery` uses a SolidJS store to persist the queryObserver result and exposes it when `createQuery` is called. Scenarios when a query is reset or when a new query key is mounted on the same observer, The queryObserver result initially updates into this state -> `{ data: undefined, isLoading: true; }`.  Updating the store with `setStore` when `data` is `undefined` removes the `data` property from the store. ref: [Updating Stores in SolidJS](https://www.solidjs.com/docs/latest/api#updating-stores)
This is why this fix uses an empty `Symbol` in place of undefined data to prevent SolidJS from deleting the data key and keeps the state consistent between updates.
> fix(solid-query): fix disappearing data key during fetching state

- docs/reference/useQueries.md
This PR documents the issue described in #4187.
I considered adding it to `Parallell queries` as well, but since it's such a specific issue I decided not to.
> docs(useQueries): duplicate query keys disclaimer

- docs/reference/MutationCache.md
- docs/reference/useMutation.md
- packages/query-core/src/mutation.ts
- packages/query-core/src/mutationCache.ts
- packages/query-core/src/tests/mutationCache.test.tsx
global mutation cache callbacks are always invoked, just like the callbacks on useMutation; however, they were not awaited, so you couldn't really do invalidations in them
> fix(query-core): await global mutation cache callbacks

- docs/reference/useQueryClient.md
Sources:
> https://github.com/TanStack/query/blob/1d57f01c94360e71e502e6dcce6ef36af3330e6b/packages/react-query/src/QueryClientProvider.tsx#L42
> https://github.com/TanStack/query/blob/1d57f01c94360e71e502e6dcce6ef36af3330e6b/packages/react-query/src/types.ts#L17-L22
I used the description wording used in other docs pages, though, not the exact wording in the source code comment above. For example:
> https://github.com/TanStack/query/blob/1d57f01c94360e71e502e6dcce6ef36af3330e6b/docs/reference/useQuery.md?plain=1#L194-L195
> docs(useQueryClient): add `context` option

- docs/reference/QueryClient.md
Hi, I'm a react-query lover!!
I found that `queryClient.setQueryData` type is wrong in docs.
`updater: TQueryFnData | (oldData: TQueryFnData | undefined) => TQueryFnData | undefined`
`updater: TQueryFnData | undefined | ((oldData: TQueryFnData | undefined) => TQueryFnData | undefined)`
I think return type of `updater` should include undefined type.
Cause original updater type is this.
```ts
updater: Updater<TQueryFnData | undefined, TQueryFnData | undefined>
Updater<TInput, TOutput> = TOutput | DataUpdateFunction<TInput, TOutput>
```
`Updater` returns TOutput and incoming generic type of `updater` is `TQueryFnData | undefined`.
So, return type of `Updater` should aceept `TQueryFnData | undefined`.
And I think `oldData: TQueryFnData | undefined) => TQueryFnData | undefined` would be better …
> docs(QueryClient): fix setQueryData updater type

- docs/guides/testing.md
Closes https://github.com/TanStack/query/issues/4319
As described in the issue above, the provided example doesn't work. Expected data has to be awaited instead of `isFetching` helpers.
> docs(testing): fix infinite query testing example

- packages/vue-query/src/__tests__/useMutation.test.ts
- packages/vue-query/src/useMutation.ts
- packages/vue-query/src/utils.ts
non-plain object is no longer destructured. tests added to prevent similar bugs from occuring going forward. improve parseMutationArgs function
> fix(vue-query): fix bug where ref is destructured

- examples/vue/basic/package.json
- packages/vue-query/src/types.ts
- pnpm-lock.yaml
proper typing got lost in this commit: https://github.com/TanStack/query/pull/4339/files#diff-888f1e51a9068ca7a2a4551335ab573f35892ca6ecddc60438fc1b9405ad8bebL12
Closes: https://github.com/TanStack/query/issues/4366
> fix(vue-query): proper function types in MaybeRefDeep

- docs/graphql.md
Hi 👋🏼 
I am Charly, from [The Guild](https://the-guild.dev), leading of [GraphQL Code Generator](https://the-guild.dev/graphql/codegen).
GraphQL Code Generator has greatly changed in the past months and improved its integration with GraphQL Clients to deliver a frictionless experience of GraphQL operations typing.
This PR showcases the new capabilities of type-safety by code generation achieved by using GraphQL Query with `graphql-request` and GraphQL Code Generator.
> doc(graphql): update "Type-Safety and Code Generation" section

- packages/vue-query/src/useQuery.ts
Closes: https://github.com/TanStack/query/issues/4387
> fix: unwrap queryKey in queryFn for overloads

- docs/guides/background-fetching-indicators.md
- docs/guides/important-defaults.md
- docs/guides/query-functions.md
I'm doing a full read-through of the docs, and I noticed a few minor things along the way.  I'm very low-ego about these changes, but thought I'd submit them.  I'd be happy to pull each commit into separate PRs if you like, but each commit has a description and should be atomic.
Definitely more to come, but I thought I'd submit what I have for today.
> docs(guides): minor fixes and typos

- packages/react-query-devtools/src/devtools.tsx
- packages/react-query-devtools/src/utils.ts
Fix issue https://github.com/TanStack/query/issues/3082
> Fix JSON formatting in detailed view.

- packages/query-core/src/query.ts
- packages/query-core/src/queryObserver.ts
- packages/react-query/src/__tests__/useQuery.test.tsx
- packages/solid-query/src/__tests__/createQuery.test.tsx
closes #4415 
previousData is data that we want to show from a previous observer if we don't have any good data in the cache already. InitialData is always considered good data, just as if it were data that has been fetched. It might be potentially stale, but that's something that can be controlled via staleTime and initialDataUpdatedAt.
So that means we shouldn't show previousData if we also have initialData
> fix(core): initialData should take precedence over keepPreviousData

- docs/config.json
- docs/guides/dependent-queries.md
- docs/guides/disabling-queries.md
- docs/guides/filters.md
- docs/guides/initial-query-data.md
- docs/guides/optimistic-updates.md
- docs/guides/paginated-queries.md
- docs/guides/placeholder-query-data.md
- docs/guides/queries.md
- docs/guides/query-cancellation.md
- docs/guides/query-functions.md
- docs/guides/query-invalidation.md
- docs/guides/query-keys.md
- docs/guides/ssr.md
- docs/guides/testing.md
- docs/guides/updates-from-mutation-responses.md
- docs/guides/window-focus-refetching.md
- docs/typescript.md
- examples/react/optimistic-updates-typescript/pages/index.tsx
Hi ([again](https://github.com/TanStack/query/pull/4419)): I finished my cover-to-cover-readthrough of the docs and I thought I'd contribute back some remaining minor things I found.  All fairly minor and atomically committed (so feel free to drop any commit you don't want without notice :+1:).
> docs(guides) some more minor fixes

- packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.test.ts
- packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.ts
> fix(eslint-plugin): handle first argument reference edge case

- packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.test.ts
- packages/eslint-plugin-query/src/utils/ast-utils.ts
> fix(eslint-plugin): get identifiers from unary, chain, and ts-non-null expressions

- packages/query-core/src/infiniteQueryBehavior.ts
- packages/query-core/src/mutation.ts
- packages/query-core/src/mutationCache.ts
- packages/query-core/src/query.ts
- packages/query-core/src/queryCache.ts
- packages/query-core/src/tests/query.test.tsx
this simplifies code because we don't need to pass meta around manually; we can keep the same public interface with a getter
> refactor(core): derive meta from options

- docs/reference/useInfiniteQuery.md
- packages/query-core/src/infiniteQueryObserver.ts
- packages/react-query/src/__tests__/useInfiniteQuery.test.tsx
- packages/solid-query/src/__tests__/createInfiniteQuery.test.tsx
Rationale discussed under https://github.com/TanStack/query/discussions/3744
> Make isRefetching false when fetching next/previous page in an infinite query

- docs/eslint/eslint-plugin-query.md
This change adds the CLI flags to install the ESLint plugin as a dev dependency instead of a normal dependency.
> docs(eslint-plugin-query): Prefer dev install

- docs/guides/query-invalidation.md
Adds a missing closing ] bracket in the second code example of [Query Matching with invalidateQueries](https://tanstack.com/query/v4/docs/guides/query-invalidation#query-matching-with-invalidatequeries)
> docs(Query Invalidation): Adds a missing square bracket

- packages/react-query-devtools/src/__tests__/devtools.test.tsx
- packages/react-query-devtools/src/__tests__/utils.tsx
- packages/react-query-devtools/src/devtools.tsx
> fix(devtools): unset padding for resetting after closed

- packages/query-core/src/queriesObserver.ts
- packages/react-query/src/__tests__/suspense.test.tsx
- packages/react-query/src/suspense.ts
- packages/react-query/src/useBaseQuery.ts
- packages/react-query/src/useQueries.ts
> feat: suspense for useQueries

- packages/react-query-devtools/package.json
- pnpm-lock.yaml
because the newer versions have trouble with esm and webpack4
fixes #4396
> fix: lock dependency of @tanstack/match-sorter-utils to 8.1.1

- packages/react-query/src/__tests__/suspense.test.tsx
this is my first pr in query. 
added tests
- shouldn't unmount before all promises fetched
- should suspend all queries in parallel - global configuration
> test: add useQueries with suspense tests

- packages/react-query-devtools/package.json
- pnpm-lock.yaml
match-sorter-utils should no longer have the bad transpilation problem anymore.
> chore(react-query-devtools): upgrade match-sorter-utils

- docs/reference/useInfiniteQuery.md
The [useInfiniteQuery docs](https://tanstack.com/query/v4/docs/reference/useInfiniteQuery) were  showing the property `isRefetching` on the options section when it is a returned property.
> docs(useInfiniteQuery): add isRefetching to returned properties docs

- examples/react/pagination/pages/index.js
In the useQuery call we set "keepPreviousData", so we must make sure that for fetching the next page we don't base our logic on the data from potentially two pages away.
If user would click very fast to get to the last page we would potentially load the eleventh page and that could result in an error depending on the backend implementation.
> docs(examples/react): fix prefetch pagination logic when trying to quickly get to the last page

- packages/query-core/src/utils.ts
because document is not defined in react-native
additionally, we can check for `Deno` being available on the window to support the Deno runtime
fixes #4584
> fix(query-core): revert isServer check to check for window

- docs/guides/query-cancellation.md
Apparently these were missed in https://github.com/TanStack/query/commit/a1050eb0d7c7c44731fc7e6839e77f69f83bab67.
It is confusing because the [Migration to v4 guide](https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4#the-cancel-method-on-promises-is-no-longer-supported) states that the `cancel` property in promises is no longer supported, but the current docs for Query Cancellation seem to imply that it is.
I assume that it is not supported anymore based on the commit linked above, the migration guide and my own testing.
If that is indeed the case, let's clean this up.
Also, please make sure that this new phrasing reflects actual behavior. That is, promises get cancelled when the signal is consumed and no `cancel` prop is needed.
> docs(query-cancellation): remove more references to old cancel fn

- packages/vue-query/src/__tests__/useQueries.test.ts
- packages/vue-query/src/useQueries.ts
Closes: https://github.com/TanStack/query/issues/4615
> feat(vue-query): allow to pass queryClient directly in useQueries options

- packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.test.ts
- packages/eslint-plugin-query/src/rules/prefer-query-object-syntax/prefer-query-object-syntax.ts
- packages/eslint-plugin-query/src/utils/ast-utils.ts
fixes https://github.com/TanStack/query/issues/4630
> fix(eslint-plugin): support rule prefer-object-syntax with multi lines

- packages/query-async-storage-persister/src/index.ts
- packages/react-query/src/__tests__/suspense.test.tsx
interfaces like localforage return a Promise<T> from setItem; we don't really care, as long as it's a Promise
> fix(query-async-storage-persister): support wider range of types

- packages/query-async-storage-persister/src/index.ts
- packages/query-core/src/focusManager.ts
- packages/query-core/src/infiniteQueryBehavior.ts
- packages/query-core/src/onlineManager.ts
- packages/query-core/src/retryer.ts
- packages/query-core/src/utils.ts
- packages/query-sync-storage-persister/src/index.ts
- packages/react-query-devtools/src/devtools.tsx
- packages/react-query-devtools/src/useMediaQuery.ts
- packages/vue-query/src/__tests__/useInfiniteQuery.types.test.tsx
- packages/vue-query/src/__tests__/useMutation.types.test.tsx
- packages/vue-query/src/__tests__/useQuery.types.test.tsx
- tsconfig.base.json
close TanStack/query/issues/4607
> fix: disallow implicit returns

- packages/vue-query/src/useBaseQuery.ts
- packages/vue-query/src/useIsFetching.ts
- packages/vue-query/src/useIsMutating.ts
- packages/vue-query/src/useMutation.ts
Just replace all `isRef(val) ? val.value : val` to `unref(val)` where possible.
> `unref` is a sugar function for `val = isRef(val) ? val.value : val`.
> refactor(vue-query): Calls `isRef` replaced by `unref` where possible

- docs/vue/installation.md
The docs were showing `vue-query` instead of `@tanstack/vue-query` for installing in Vue
> docs(vue import): fix import path for Vue plugin

- docs/react/graphql.md
- docs/react/overview.md
- docs/react/typescript.md
- docs/vue/guides/initial-query-data.md
- docs/vue/guides/mutations.md
- docs/vue/guides/paginated-queries.md
- docs/vue/guides/queries.md
- docs/vue/guides/ssr.md
- docs/vue/guides/suspense.md
- docs/vue/overview.md
- docs/vue/typescript.md
- examples/vue/dependent-queries/vite.config.ts
- examples/vue/persister/vite.config.ts
- fixed some content tokens
- fixed imports `vue-query` -> `@tanstack/vue-query`
> docs(vue-query): fix vue-query imports in docs, correct section replacements

- docs/react/react-native.md
The React Query plugin for Reactotron allows you to debug and inspect the cache and queries of your React Query application in Reactotron. This can be useful for understanding how your React Query application is behaving and identifying any potential issues or problems.
> Add `reactotron-react-query` plugin

- docs/react/guides/important-defaults.md
- docs/react/guides/migrating-to-react-query-5.md
- docs/react/reference/useQuery.md
- packages/query-core/src/queryObserver.ts
- packages/query-core/src/tests/queryClient.test.tsx
- packages/query-core/src/tests/queryObserver.test.tsx
- packages/query-core/src/types.ts
- packages/query-core/src/utils.ts
This PR remove the options ```isDataEqual``` from useQuery
> feat(isDataEqual): Remove is data equal from useQuery

- docs/react/guides/window-focus-refetching.md
I read the current documentation that there is no mention of the default value of refetchOnWindowFocus, and the current way of writing it makes me re-verify that only refetch when the data is stale, it took me 15 minutes to read the code to verify how it works, so I want to update the docs for more clear.
> docs(guides refetchOnWindowFocus): more clear instructions for the use

- packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.rule.ts
Just fix a description for @tanstack/query/exhaustive-deps. Looks like it was copypasted from prefer-query-object-syntax
> fix: update eslint-exhaustive-deps rule description

- package.json
Current preinstall script only supports UNIX based platforms. This causes issues for developers on Windows.
> fix(env): cross platform preinstall CI check.

- docs/react/reference/hydration.md
- packages/query-core/src/hydration.ts
- packages/query-core/src/index.ts
Export `defaultShouldDehydrateQuery` and `defaultShouldDehydrateMutation` to make it easier to retain the default behavior when extending these in the `dehydrateOptions`
> Export default hydration methods for easier extension in `dehydrateOptions`

- docs/config.json
- docs/svelte/installation.md
- docs/svelte/overview.md
This adds links to the examples in the sidebar - I've seen a few people asking for help using this in SvelteKit and this makes examples more accessible. I'm assuming that the actual examples pages are auto-generated by the Remix site.
Also added in an installation page and fixed a not-quite-bug in the overview demo.
> docs(svelte-query): Add example links and installation instructions

- docs/config.json
- docs/svelte/overview.md
- docs/svelte/ssr.md
I saw this [comment on Reddit](https://old.reddit.com/r/sveltejs/comments/10718ef/tanstack_querys_svelte_adapter_released/j3kycpw/) which showed an incredibly easy way to SSR data for svelte-query (it had an async bug that I've fixed), so I wanted to share this ASAP :)
I've also changed the prism codeblock renderer from `svelte` (unsupported) to `markdown` (I've seen some other projects use this).
> docs(svelte-query): Add SSR and SvelteKit guide

- docs/react/guides/important-defaults.md
- docs/react/guides/window-focus-refetching.md
- docs/react/reference/focusManager.md
- packages/query-core/src/focusManager.ts
- packages/query-core/src/tests/focusManager.test.tsx
- packages/query-core/src/tests/query.test.tsx
- packages/react-query/src/__tests__/useQuery.test.tsx
- packages/solid-query/src/__tests__/createQuery.test.tsx
As discussed in #4797, `focus` event has many caveats, as it's triggered in the following scenarios:
- When interacting with an iframe.
- When opening/closing a browser dialog (`alert`, `confirm`).
- When moving between the page and DevTools.
- When opening/closing a file picker.
I think the original idea behind `refetchOnWindowFocus` was to refetch the queries when the user "comes back" to the page, and that's achievable using `visibilitychange`.
You can see that the query is being refetched in many unexpected scenarios, while the user didn't leave the page.
<video src="https://user-images.githubusercontent.com/30146019/212169502-a4078286-eab6-4d1e-8914-4a24f968aab1.mp4" />
The query is refetched only when the user stop using the app, and comes back.
<video …
> fix(focusManager): stop listening for `focus` events

- docs/react/devtools.md
This can save others some time browsing around trying to get it to work
> Update devtools.md with note that mutations are not tracked

- docs/react/guides/caching.md
- docs/react/guides/placeholder-query-data.md
- packages/vue-query/README.md
Corrected typo "quey" to "query".
> docs: fix typo (quey -> query)

- docs/config.json
- docs/svelte/overview.md
- docs/svelte/ssr.md
I forgot to add the `enabled: browser` logic down to a lower section :/ Last change to this page for a while, I promise!
I've also bumped the page up the sidebar since it is important for anyone using SvelteKit.
> docs(svelte-query): Add recommended defaults to prefetchQuery setup

- docs/react/guides/migrating-to-v5.md
- docs/react/guides/ssr.md
- docs/react/reference/hydration.md
- examples/react/nextjs/pages/_app.js
- packages/react-query/src/HydrationBoundary.tsx
- packages/react-query/src/__tests__/HydrationBoundary.test.tsx
- packages/react-query/src/index.ts
- Rename `Hydrate` -> `HydartionBoundary`
- Remove `useHydrate` hook
- Update migration guide
Fixes #4692
> Rename `Hydrate` -> `HydrationBoundary`

- docs/react/reference/useMutation.md
This pull request clarifies the `useMutation` `mutationFn` option default as being the global mutation configuration `mutationFn`. 
- This change came out of a conversation had in the TanStack Discord server between another member, Dominik, and me. 
- Please let me know if an issue would be useful for tracking.
> docs(useMutation): clarify `mutationFn` option default

- packages/svelte-query/src/__tests__/CreateMutation.svelte
- packages/svelte-query/src/__tests__/createMutation.test.ts
- packages/svelte-query/src/createMutation.ts
- packages/svelte-query/src/types.ts
I was adding svelte-query into my own project and I was being told I needed 1-2 arguments for a mutation... since near-identical code was working in react-query I had a feeling this was a bug!
> fix(svelte-query): Fix createMutation for functions that take no arguments

- packages/query-core/src/mutationObserver.ts
- packages/query-core/src/tests/mutations.test.tsx
- packages/react-query/src/__tests__/useMutation.test.tsx
https://github.com/TanStack/query/discussions/4804
> fix: mutate callbacks called if mutation started after unmount

- packages/react-query/src/__tests__/useInfiniteQuery.test.tsx
- packages/react-query/src/__tests__/useQuery.test.tsx
- packages/solid-query/src/__tests__/createInfiniteQuery.test.tsx
- packages/solid-query/src/__tests__/createQueries.test.tsx
- packages/solid-query/src/__tests__/createQuery.test.tsx
- packages/vue-query/src/__tests__/useInfiniteQuery.types.test.tsx
- packages/vue-query/src/__tests__/useIsFetching.test.ts
- packages/vue-query/src/__tests__/useIsMutating.test.ts
- packages/vue-query/src/__tests__/useMutation.test.ts
- packages/vue-query/src/__tests__/useMutation.types.test.tsx
- packages/vue-query/src/__tests__/useQuery.test.ts
- packages/vue-query/src/__tests__/useQuery.types.test.tsx
- packages/vue-query/src/mutationCache.ts
- packages/vue-query/src/queryCache.ts
- packages/vue-query/src/queryClient.ts
- packages/vue-query/src/types.ts
- packages/vue-query/src/useBaseQuery.ts
- packages/vue-query/src/useInfiniteQuery.ts
- packages/vue-query/src/useIsFetching.ts
- packages/vue-query/src/useIsMutating.ts
- packages/vue-query/src/useMutation.ts
- packages/vue-query/src/useQueries.ts
- packages/vue-query/src/useQuery.ts
- packages/vue-query/src/utils.ts
@TkDodo I beleive this PR was auto-closed, since it was targeting another PR , not v5 directly...
I beleive github previously just switched the branch in such PR, but in this case it got closed.
https://github.com/TanStack/query/pull/4838
> fix(vue-query): simplify vue hooks, fix types

- docs/svelte/ssr.md
Just adding my two cents here. Here's a small documentation fix around the sveltekit data load function.
`posts` wasn't defined nor extracted from `data`. So I just added `data.posts` to make it make sense.
btw I love TanStack Query! 🙌🏼 Congrats to the team!
> docs(svelte-query): Fix variable reference issue on sveltekit doc

- docs/svelte/ssr.md
A minor issue but the types for some `+layout.svelte` data prop was incorrect. This PR addresses that issue.
> docs(svelte-query): Correctly type layout data when using prefetchQuery

- packages/svelte-query/src/__tests__/CreateMutation.svelte
- packages/svelte-query/src/__tests__/CreateQueries.svelte
- packages/svelte-query/src/__tests__/CreateQuery.svelte
- packages/svelte-query/src/__tests__/createMutation.test.ts
- packages/svelte-query/src/__tests__/createQueries.test.ts
- packages/svelte-query/src/__tests__/createQuery.test.ts
- packages/svelte-query/src/createQueries.ts
Fixes #4832. The results from createQueries were being incorrectly typed as each being svelte stores, as they were using the CreateQueryResult type. This changes each result to directly use QueryObserverResult. I've also added a very simple test.
Also @TkDodo I noticed that svelte-query alone takes an array of queries directly into createQueries (e.g. `createQueries([...])`) while the other packages all use an object with the queries key (e.g. `useQueries({ queries: [...] })`). Is this something I should change in v4, or wait until v5?
> fix(svelte-query): Fix createQueries result type

- packages/query-core/src/query.ts
- packages/query-core/src/tests/query.test.tsx
- packages/svelte-query/src/__tests__/createQuery.test.ts
This is important if data comes into the cache via a non-fetching method (like setQueryData or hydration) AND there is no active observer for them. Without this, they would never be gc'ed, but they should be after the default cacheTime
closes #4887
> fix(core): make sure queries that never fetched can be garbage collected

- packages/query-persist-client-core/package.json
- pnpm-lock.yaml
Moves `query-core` to dependencies of `query-persist-client-core` so packages using `query-persist-client-core` don't have an unmet peer dependency warning
Closes #4885
> fix(query-persist-client-core): Move query-core to dependencies

- packages/query-core/src/mutationCache.ts
- packages/query-core/src/tests/queryClient.test.tsx
when resumePausedMutations is called multiple times, we are starting the second paused mutation even though the first one has not yet finished. This can happen when a focus event and an online event happen in short succession
closes #4896
> fix(core): make sure pausedMutations always execute in serial

- docs/react/reference/useQuery.md
It seems like return value `isInitialLoading` is missing in top part of the docs (although its correctly listed in second part of the page with all the rest descriptions).
> fix(useQuery.md): add missing isInitialLoading as possible return

- docs/react/guides/ssr.md
I'm using Razzle as a SSR framework, I've found this issue while integrating react-query.
> docs(react): Fix SSR custom framework guide -  `dehydratedState ` should be deconstructed

- packages/query-core/src/tests/infiniteQueryBehavior.test.tsx
Tests added for `infiniteQueryBehavior` to reach 100% code coverage.
Done using v5 branch.
> test(query-core): v5: infiniteQueryBehavior: 100% code coverage

- packages/query-core/src/hydration.ts
- packages/query-core/src/tests/hydration.test.tsx
Fixes a bug which caused the `fetchStatus` to be `fetching` forever with persisters when a successful query was refetching in background and the app was quit before the fetch succeeds
> Set `fetchStatus` to `idle` when dehydrating

- packages/query-core/src/infiniteQueryBehavior.ts
- packages/query-core/src/query.ts
- packages/query-core/src/queryClient.ts
- packages/query-core/src/tests/query.test.tsx
- packages/query-core/src/tests/queryClient.test.tsx
- packages/query-core/src/types.ts
- packages/react-query/src/types.ts
- packages/react-query/src/useInfiniteQuery.ts
- pnpm-lock.yaml
Added typing, tell me if it's what you needed ?
> feat: add PageParam typing

- pnpm-lock.yaml
This was broken in a [recent commit](https://github.com/TanStack/query/commit/813962f8073a498c99abadaf2039f08e735582c2) merging main into v5.
> Fix pnpm workspace links

- packages/vue-query/src/vueQueryPlugin.ts
Fixes: https://github.com/TanStack/query/issues/4953
> fix(vue-query): prevent memory leak in server environment

- packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.rule.ts
- packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.test.ts
fixes https://github.com/TanStack/query/issues/5022
> fix(eslint-plugin): handle new & as const

- packages/react-query-devtools/src/devtools.tsx
Sort options (asc / desc, and sort function) were hidden when filter was set.
Sort options are now shown along with the filter, even when a filter is set.
Closes #4989
> fix(react-query-devtools): do not hide sort options when filter is used

- .github/workflows/pr.yml
- package.json
- packages/solid-query/package.json
- scripts/publish.ts
- scripts/validate-packages.ts
> chore: extract package validation to an extra script

- README.md
The v2 site is down. Updating the link for v2 docs to point to the source code as highlighted in this comment:
https://github.com/TanStack/query/issues/4919#issuecomment-1412660461
Alternatively, also in favour of removing the mention of v2 from README altogether since it is to be considered unmaintained.
> docs: update link for v2 docs

- packages/react-query-devtools/src/devtools.tsx
Do not stretch query status label (fresh, fetching, paused, stale, inactive) shown on Query Details view.
before:
after:
> fix(react-query-devtools): do not stretch query status label

- docs/react/guides/optimistic-updates.md
> via the dedicated `useMurationState` hook
to
> via the dedicated `useMutationState` hook
> "muration" typo

- packages/query-core/src/index.ts
Hi everyone, based on our [previous discussion](https://github.com/TanStack/query/discussions/5064), I would like to open a PR that allows clients to import `matchQuery` from the `core` package. I attach the content of the original thread as a reference below.
Because this change exposes `matchQuery` as part of the public API, I assume it should be covered with tests independently - as far as I understand, it is currently only covered implicitly by the tests in `queryCache.test.ts`. I'll start to work on these as soon as I get a go. I also wonder about documentation: are inline docs sufficient or would you like to have the function documented somewhere else?
Thank you very much in advance for looking into this PR.
Since the entrypoints of the core package are limited using `exports` in …
> feat(core): re-export matchQuery from utils

- docs/react/reference/useMutation.md
Following up on the discussion about `variables` being returned by `useMutation` but not documented: https://github.com/TanStack/query/discussions/5082#discussioncomment-5213598
- add `variables` to the reference docs for `useMutation`
> docs(useMutation): add `variables` to `useMutation` reference docs

- packages/query-core/src/mutation.ts
- packages/query-core/src/mutationObserver.ts
- packages/query-core/src/tests/mutations.test.tsx
this fixes an issue around stale closures where callbacks are not updated, thus are called with wrong values in the closure
fixes #5056
> fix(core): make sure mutations get updated options

- packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.rule.ts
- packages/eslint-plugin-query/src/rules/exhaustive-deps/exhaustive-deps.test.ts
- packages/eslint-plugin-query/src/utils/ast-utils.ts
fixes https://github.com/TanStack/query/issues/5069
> fix(eslint-plugin): improve object property checks

- packages/react-query/src/__tests__/useQueries.test.tsx
- packages/react-query/src/useQueries.ts
- packages/solid-query/src/__tests__/createQueries.test.tsx
- packages/solid-query/src/__tests__/useIsFetching.test.tsx
- packages/solid-query/src/__tests__/useIsMutating.test.tsx
- packages/solid-query/src/createBaseQuery.ts
- packages/solid-query/src/createInfiniteQuery.ts
- packages/solid-query/src/createMutation.ts
- packages/solid-query/src/createQueries.ts
- packages/solid-query/src/createQuery.ts
- packages/solid-query/src/useIsFetching.ts
- packages/solid-query/src/useIsMutating.ts
- packages/svelte-query/src/createQueries.ts
- packages/vue-query/src/__tests__/useQueries.test.ts
- packages/vue-query/src/__tests__/vueQueryPlugin.test.ts
- packages/vue-query/src/useQueries.ts
- `useQueries` accept `queryClient` as second parameter just like other hooks
- solid `useIsFetching` and `useIsMutating` accept `queryClient` as second parameter
> fix: queryClient consistent as a second parameter

- docs/react/guides/queries.md
Origin version: 
> error - If the query is in an isError state, the error is available via the error property.
> data - If the query is in a success state, the data is available via the data property.
Compared with the previous sentence,  `a success` should be changed to `an isSuccess`
> docs(queries): rename `success` -> `isSuccess`

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- nx.json
- package.json
- pnpm-lock.yaml
<div align="left">
<a href="https://www.youtube.com/watch?v=5M9-l5IciLU" target="blank">
</a>
</div>
+ Implements local task-caching [currently] only for the `test:lib` task (with Nx)
+ I also update the root `test-lib` script to run with nx's run-many command, as well as the `Test` workflow in `.github/workflows/pr.yml`
+ While not directly affected, the `Run Test` step of the `ci` pipeline is adjusted as well as `test:ci` will call `pnpm run test:lib`
+ My testing shows a 20s time boost to the `Test` job of the `pr` pipeline (see https://github.com/ZackDeRose/query/pull/1#issuecomment-1464847177 for my findings)
+ Note that any `test:lib:dev` commands are not affected and work exactly as they did before
I wanted to make this PR bite-sized (as opposed to my last one!) but would be happy …
> `test:lib` task-caching w/ Nx

- nx.json
@TkDodo - quick update on alpha: no need for a workspace root level `vitest.config.ts` file, as we don't have one!
> fix: adjusting nx json for the alpha branch

- package.json
- pnpm-lock.yaml
see: https://stackoverflow.com/questions/70309135/chalk-error-err-require-esm-require-of-es-module
> chore: downgrade chalk to v4 because v5 is ESM only

- .github/workflows/ci.yml
- .github/workflows/pr.yml
+ adds retries to cover the flakiness around the tests
+ this should allow local caching from other efforts to benefit in the case of retries
> Adding in retries to cover flakiness in tests

- package.json
- packages/react-query/src/errorBoundaryUtils.ts
- packages/react-query/src/reactBatchedUpdates.ts
- packages/react-query/src/useBaseQuery.ts
- packages/react-query/src/useInfiniteQuery.ts
- packages/react-query/src/useIsFetching.ts
- packages/react-query/src/useIsMutating.ts
- packages/react-query/src/useMutation.ts
- packages/react-query/src/useQueries.ts
- packages/react-query/src/useQuery.ts
- packages/react-query/src/useSyncExternalStore.ts
- pnpm-lock.yaml
- rollup.config.ts
Fixes #4933
* Pulls in `rollup-plugin-preserve-directives` and adds it to all un-bundled builds to preserve 'use client' directives
* See rollup issue https://github.com/rollup/rollup/issues/4699
* Adds `'use client'` to all files that should have it (I think)
This makes everything work as documented with Next app router, that is, developers should no longer need to:
* Wrap our imports in `"use client"` themselves (just import and use `Hydrate` directly for example)
* Import from `@tanstack/query-core` in RSCs (can now import directly from `@tanstack/react-query`)
> For anyone reading along: Note that React Query-support for the Next app router is still experimental!
I tested it like this (basically quick version of the docs):
```jsx
// Providers.jsx
// This wraps the entire app in root …
```
> Preserve 'use client' directives

- .github/workflows/ci-v3.yml
- .github/workflows/ci.yml
adds the access token from our secrets vault to the ci workflow files, so these can populate the cache as well.
> adding nx cloud access token to ci workflow files

- docs/react/reference/QueryCache.md
This PR revert the docs for QueryCache
from
```ts
find({queryKey: QueryKey})
```
to
```ts
find(queryKey)
```
> chore(docs): revert docs for QueryCache

- examples/solid/basic-graphql-request/package.json
- examples/solid/basic-typescript/package.json
- examples/solid/default-query-function/package.json
- examples/solid/simple/package.json
- examples/solid/solid-start-streaming/package.json
- examples/solid/solid-start-streaming/src/root.css
- examples/solid/solid-start-streaming/src/root.tsx
- examples/solid/solid-start-streaming/src/routes/hydration.tsx
- package.json
- packages/solid-query/package.json
- packages/solid-query/src/createBaseQuery.ts
- pnpm-lock.yaml
- rollup.config.ts
~### 1. Don't use `onCleanup` on the server~
~It's still not safe to rely on `onCleanup` on the server, so I've re-added the `!isServer` check for the time being. I was able to isolate + reproduce the `onCleanup` behavior, and opened an issue in the solidjs repo - we'll see what Ryan + team thinks -> https://github.com/solidjs/solid/issues/1599.~
Nevermind! Ryan fixed the https://github.com/solidjs/solid/issues/1599 in solid v1.6.13 - I verified it solves the problem here in solid-query, and bumped the minimum solid-js version to 1.6.13.
**Before**
Any page with more than one query on it cannot be rendered in SSR (streaming or regular async render). Try firing up the example and loading `http://127.0.0.1:3000/deferred` - it will load indefinitely.
**After**
Routes with more than one query …
> fix(solid-query): ssr fixes

- packages/solid-query/src/createBaseQuery.ts
Noticed that the recent changes brought a regression that caused pre fetched server queries from hydrating. This issue happens because `refetch` is a function on the QueryObserverresult and functions are non-serializable. This causes the queryResource to skip hydrating the resource on the client. This fix removes the refetch function from the hydrating payload.
> fix(solid-query): Fix non hydrating queries

- docs/react/typescript.md
Fixed typos in the new V5 React documentation
> docs(react): fix typo in TypeScript.md

- packages/query-core/src/queriesObserver.ts
This optimizes the `findMatchingObservers` function in `queriesObserver` which becomes very slow on large data sets in `useQueries`. 
Below are the results with latest react query without this change on a dataset of 5000 objects.
We can see it takes 1.3 seconds only inside the `findMatchingObservers` function, which leads to a very laggy UX.
The majority of this time is spent inside 2 functions in `findMatchingObservers`.
- The first function `.flatMap` is O(n*m) as it runs Array.find on every single element in `defaultedQueryOptions`. By using a map we bring this down to O(m), where m is the number of elements in `defaultedQueryOptions`. Yes using a map will add more space complexity but the overhead is extremely minimal compared to the performance gain.
- The second function is where we …
> perf(useQueries): optimize findMatchingObservers fn in queriesObserver for large datasets

- packages/query-core/src/mutationCache.ts
- packages/query-core/src/queryCache.ts
- packages/query-core/src/queryClient.ts
- packages/vue-query/src/__tests__/mutationCache.test.ts
- packages/vue-query/src/__tests__/queryCache.test.ts
params passed to function from consumers should be treated as readonly and thus shouldn't be modified
> fix: do not mutate input

- docs/react/guides/migrating-to-v5.md
I think the rocket emoji is causing a visual bug too but since I edited this through GitHub's UI, I couldn't confirm.
> docs: update migrating-to-v5

- docs/config.json
- docs/react/community/suspensive-react-query.md
Hi Tanner and TkDodo, this is Pull Request to add the @suspensive/react-query package to the Community section on Docs.
In this Pull Request, I wrote the motivation for using @suspensive/react-query, how to install it, and an example of how to use it as simply as possible. I tried to avoid changes as much as possible by writing more details in [the official documentation](https://suspensive.org/).
Please let me know if you'd like for me to make any changes.
> docs(community): add @suspensive/react-query community contribution

- packages/query-core/src/queryObserver.ts
- packages/query-core/src/tests/queryObserver.test.tsx
- packages/react-query/src/__tests__/useQuery.test.tsx
Howdy! 
This PR fixes an issue in v5 when we use placeholderData fn in conjunction with the select fn. The current bug 
is that the previousData available in the params of the placeholderData fn is the selected data from the previous query and not the cached data from the previous query. This causes an issue that would be better explained with the following example:
https://codesandbox.io/s/gallant-gates-dslrlm?file=/src/App.js
I have also added one test case that shows the desired (fixed) behavior. Please let me know if I can add any other test cases to make this bulletproof! 
Thanks,
Aryan
> fix(query-core): correct placeholderData prevData value with select fn

- packages/solid-query/src/QueryClient.ts
- packages/solid-query/src/QueryClientProvider.tsx
- packages/solid-query/src/__tests__/createInfiniteQuery.test.tsx
- packages/solid-query/src/__tests__/createQuery.test.tsx
- packages/solid-query/src/__tests__/utils.tsx
- packages/solid-query/src/createBaseQuery.ts
- packages/solid-query/src/createInfiniteQuery.ts
- packages/solid-query/src/createMutation.ts
- packages/solid-query/src/createQueries.ts
- packages/solid-query/src/createQuery.ts
- packages/solid-query/src/index.ts
- packages/solid-query/src/types.ts
- packages/solid-query/src/useIsFetching.ts
- packages/solid-query/src/useIsMutating.ts
- packages/solid-query/tsconfig.json
This pull request proposes a new feature for `solid-query` that allows for more precise updates to query data. The new `reconcile` option enables updates to be made between state updates, while the structuralSharing option is removed since it doesn't work well with `solid-js'` data diffing patterns.
Consider this following example that fetches data for a users list with createQuery.
```tsx
interface User {
id: number
name: string
last_online: string
}
const usersList = createQuery(() => ({
queryKey: ['users_list'],
queryFn: async () => {
const users = await fetch(`${API_URL}/users`).then(res => res.json()) 
return users as User[]
},
}))
return (
<div>
<button onClick={usersList.refetch}>Refetch</button>
<For each={usersList.data}>
{user => (
<div>
<div>{user.name}</div> …
```
> feat(solid-query): Add `reconcile` option

- packages/solid-query/src/createBaseQuery.ts
This fix removes potentially unserializable values from `createBaseQuery`. They also are not needed for hydrating queries
> fix(solid-query): Remove unserializable values

- docs/react/guides/migrating-to-v5.md
- docs/react/guides/suspense.md
- docs/react/reference/QueryClient.md
- docs/react/reference/QueryErrorResetBoundary.md
- docs/react/reference/useMutation.md
- docs/react/reference/useQuery.md
- docs/solid/overview.md
- packages/query-core/src/queryClient.ts
- packages/query-core/src/queryObserver.ts
- packages/query-core/src/types.ts
- packages/react-query/src/__tests__/QueryResetErrorBoundary.test.tsx
- packages/react-query/src/__tests__/suspense.test.tsx
- packages/react-query/src/__tests__/useMutation.test.tsx
- packages/react-query/src/__tests__/useQueries.test.tsx
- packages/react-query/src/__tests__/useQuery.test.tsx
- packages/react-query/src/errorBoundaryUtils.ts
- packages/react-query/src/useBaseQuery.ts
- packages/react-query/src/useMutation.ts
- packages/react-query/src/useQueries.ts
- packages/solid-query/src/__tests__/createMutation.test.tsx
- packages/solid-query/src/__tests__/createQuery.test.tsx
- packages/solid-query/src/__tests__/suspense.test.tsx
- packages/solid-query/src/createBaseQuery.ts
- packages/solid-query/src/createMutation.ts
to be aligned with the options we already have on imperative methods, like `invalidateQueries`
> feat: rename throwErrors to throwOnError

- docs/react/videos.md
Hey, just a quick accessibility fix to add titles to the video iFrames on the videos page, according to this rule:
https://dequeuniversity.com/rules/axe/4.7/frame-title
I just used the titles of the videos, figured that made the most sense :). (I'm not quite sure how all screen readers might handle `&quot;` so I just removed the quotes)
> fix: a11y - adding titles to the video iframes

- docs/react/guides/migrating-to-v5.md
- docs/react/reference/QueryCache.md
- packages/query-core/src/queryCache.ts
- packages/query-core/src/tests/queryCache.test.tsx
having the option to customize the internal store sound nice, but the problem is that the store holds Query instances, not data. So, the setter is only called once, not on every data update. This makes it relatively useless - every time we thought we could leverage createStore, it fell short of our requirements because of this.
The better way is usually to subscribe to the QueryCache directly
> chore: remove createStore option

- packages/eslint-plugin-query/package.json
- packages/svelte-query/package.json
- packages/svelte-query/src/__tests__/CreateMutation.svelte
- packages/svelte-query/src/__tests__/CreateQueries.svelte
- packages/svelte-query/src/__tests__/CreateQuery.svelte
- packages/svelte-query/src/__tests__/createMutation.test.ts
- packages/svelte-query/src/__tests__/createQueries.test.ts
- scripts/config.ts
- scripts/types.ts
- scripts/validate-packages.ts
According to [publint](https://publint.dev/@tanstack/svelte-query@4.29.5):
`This entrypoint has types at build/lib/index.d.ts but it is not exported from pkg.exports. Consider adding it to pkg.exports["."].types to be compatible with TypeScript's "moduleResolution": "bundler" compiler option. ([More info](https://publint.dev/rules.html#types_not_exported))`
This _was_ actually working with bundler mode because the `.d.ts` files are adjacent to the `.js` files. However, this is obviously more correct, and the other query packages do this already.
I've added a check to validate-packages.ts to look for exports['.']['default'], and also moved the entries logic into config.ts. In the future, it might be possible to add publint to this file - however I ran into a CJS/ESM error which I will …
> chore: Validate "exports" field in package.json
